// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConversationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "conversations",
		Short:       "Conversation inventory and full extraction",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newConversationsGetCmd(flags))
	cmd.AddCommand(newConversationsGetTreeCmd(flags))
	cmd.AddCommand(newConversationsListCmd(flags))
	cmd.AddCommand(newConversationsListMessagesCmd(flags))
	cmd.AddCommand(newConversationsSearchCmd(flags))
	cmd.AddCommand(newConversationsStreamStatusCmd(flags))
	return cmd
}
