// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newConversationsListCmd(flags *rootFlags) *cobra.Command {
	var flagOffset string
	var flagLimit int
	var flagOrder string
	var flagIsArchived bool
	var flagIsStarred bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Chronological conversation list — offset/limit pagination; total is a min(realTotal, offset+limit+1) hint",
		Example:     "  chatgpt-pp-cli conversations list",
		Annotations: map[string]string{"pp:endpoint": "conversations.list", "pp:method": "GET", "pp:path": "/backend-api/conversations", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/backend-api/conversations"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "conversations", path, retainCLIQueryParams(cmd, map[string]string{
				"offset":      formatCLIParamValue(flagOffset),
				"limit":       formatCLIParamValue(flagLimit),
				"order":       formatCLIParamValue(flagOrder),
				"is_archived": formatCLIParamValue(flagIsArchived),
				"is_starred":  formatCLIParamValue(flagIsStarred),
			}, map[string][]string{"offset": {"offset"}, "limit": {"limit"}, "order": {"order"}, "is_archived": {"is-archived"}, "is_starred": {"is-starred"}}, "", "offset"), nil, flagAll, "", "offset", "limit", 28, "", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&flagOffset, "offset", "0", "Pagination offset")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Page size (max 100; 999 rejected as 422)")
	cmd.Flags().StringVar(&flagOrder, "order", "updated", "Sort key (updated accepted; created returns 500 — sort client-side)")
	cmd.Flags().BoolVar(&flagIsArchived, "is-archived", false, "Filter archived conversations")
	cmd.Flags().BoolVar(&flagIsStarred, "is-starred", false, "Filter starred conversations")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
