// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// learn_init.go is the spec-driven init shim for the self-learning loop.
// newLearnConfig builds the per-CLI *entities.Config the cobra teach /
// recall / learnings commands thread through every call site;
// initLearn seeds the entity_lookups table from the canonical-+-aliases
// table declared in spec.Learn.EntityLookupSeeds. Both run once at
// startup; subsequent calls are idempotent (INSERT OR IGNORE on the
// store side, fresh Config build on the registration side).
//
// Soft validation: a runtime regex compile failure (which spec parse
// already rejects at load time) logs to stderr and continues without
// the pattern instead of aborting the CLI. Empty Learn config produces
// a Config with built-in stopwords and a no-op initLearn.

package cli

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"regexp"
	"sync"

	"chatgpt-pp-cli/internal/learn/entities"
	"chatgpt-pp-cli/internal/learn/lookups"
	"chatgpt-pp-cli/internal/store"
)

// newLearnConfig returns the per-CLI entity extractor Config the
// teach / recall / normalize call sites pass into the learn package.
// Reads the printed-CLI's spec.Learn.TickerPatterns, Stopwords, and
// Synonyms; patterns that fail to compile at runtime (defense in
// depth — spec parse already validated them) log a warning and are
// skipped. Declared synonyms register on both the returned Config and
// the store package's write-side normalizer.
func newLearnConfig() *entities.Config {
	cfg := entities.NewConfig()
	var tickerPatterns []*regexp.Regexp
	if re, err := regexp.Compile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`); err != nil {
		fmt.Fprintf(os.Stderr, "warning: chatgpt-pp-cli: ticker pattern %q failed to compile: %v\n", `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`, err)
	} else {
		cfg.RegisterTickerPattern(re)
		tickerPatterns = append(tickerPatterns, re)
	}
	if len(tickerPatterns) > 0 {
		store.RegisterTickerPatterns(tickerPatterns)
	}
	// Spec-declared same-referent synonym folds, registered on BOTH
	// normalizers: the entities.Config drives the read side (recall
	// family keys) and store.RegisterQuerySynonyms the write side
	// (teach query patterns). One map, two registrations — the
	// two-normalizer symmetry the learn loop's key space depends on.
	learnSynonyms := map[string]string{
		"chat":   "conversation",
		"thread": "conversation",
	}
	cfg.RegisterSynonyms(learnSynonyms)
	store.RegisterQuerySynonyms(learnSynonyms)
	return cfg
}

// initLearn seeds the entity_lookups table from the spec.Learn.
// EntityLookupSeeds declaration. INSERT OR IGNORE on the store side
// makes this idempotent — calling it twice produces the same DB state
// as calling it once. An empty seed map is a no-op (returns nil).
func initLearn(ctx context.Context, db *sql.DB) error {
	_ = ctx
	seeds := map[string][]lookups.SeedConfig{
		"model": {
			{Canonical: "gpt-5-6", Values: []string{"5.6", "sol", "56"}},
			{Canonical: "gpt-5-6-thinking", Values: []string{"thinking", "5.6 thinking", "56 thinking"}},
			{Canonical: "gpt-5-6-instant", Values: []string{"instant", "5.6 instant"}},
			{Canonical: "gpt-5-5", Values: []string{"5.5"}},
			{Canonical: "gpt-5-5-thinking", Values: []string{"5.5 thinking"}},
			{Canonical: "gpt-5-5-instant", Values: []string{"5.5 instant"}},
			{Canonical: "gpt-5-6-mini", Values: []string{"mini", "5.6 mini"}},
			{Canonical: "gpt-5-6-pro", Values: []string{"pro", "5.6 pro"}},
			{Canonical: "gpt-6-pro", Values: []string{"6 pro"}},
			{Canonical: "research", Values: []string{"deep research", "deepresearch"}},
		},
	}
	if _, err := lookups.SeedFromConfig(db, seeds); err != nil {
		return fmt.Errorf("initLearn: seed entity_lookups: %w", err)
	}
	return nil
}

// learnInitOnce gates runLearnInitOnce so the seed pass happens at
// most once per CLI process. The sync.Once keeps the cost off the
// hot path for repeat command invocations within an MCP session.
var learnInitOnce sync.Once

// runLearnInitOnce opens the canonical store path, fires initLearn
// once per process, and downgrades any failure to a stderr warning.
// Per the self-learning loop's soft-validation contract, a seed
// failure must never abort the CLI — the recall path returns the
// empty envelope if entity_lookups is missing rows, which is the
// same behavior an opt-out CLI sees.
func runLearnInitOnce(ctx context.Context) {
	learnInitOnce.Do(func() {
		dbPath := defaultDBPath("chatgpt-pp-cli")
		s, err := store.OpenWithContext(ctx, dbPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: chatgpt-pp-cli: learn init: open store: %v\n", err)
			return
		}
		defer s.Close()
		if err := initLearn(ctx, s.DB()); err != nil {
			fmt.Fprintf(os.Stderr, "warning: chatgpt-pp-cli: learn init: %v\n", err)
		}
	})
}

// learnCommonIdentityFields is the ordered, domain-neutral list
// ResourceEntitiesFromJSON walks when a resource has no more specific
// identity key. Missing JSON keys are skipped, so one list can serve
// every collection.
var learnCommonIdentityFields = []string{
	"name", "title", "display_name", "full_name", "short_name", "label",
	"slug", "key", "code", "id", "address",
}

// learnResourceTypeFields returns the per-resource identity-field map
// passed to Recall so entity_match can be exact when the stored JSON
// actually carries the identity.
func learnResourceTypeFields() map[string][]string {
	return map[string][]string{
		"chat":          {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"conversations": {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"global_search": {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"models":        {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"session":       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
	}
}

// learnIdentityFieldsFor returns the identity fields for one resource
// type, falling back to the common list when the type is unknown.
func learnIdentityFieldsFor(resourceType string) []string {
	if fields, ok := learnResourceTypeFields()[resourceType]; ok && len(fields) > 0 {
		return fields
	}
	return append([]string(nil), learnCommonIdentityFields...)
}
