// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"tickertape-pp-cli/internal/cli"
	"tickertape-pp-cli/internal/client"
	"tickertape-pp-cli/internal/cliutil"
	"tickertape-pp-cli/internal/config"
	"tickertape-pp-cli/internal/mcp/bound"
	"tickertape-pp-cli/internal/mcp/cobratree"
	"tickertape-pp-cli/internal/platform"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	s.AddTool(
		mcplib.NewTool("company_aggregated_deals",
			mcplib.WithDescription("Entitlement-aware company deal signals. Required: sid. Returns the JsonObject. (requires auth)"),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/aggregateddeals/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_ai_summary",
			mcplib.WithDescription("Entitlement-aware AI summary; preserves explicit 401 or locked access metadata. Required: sid. Returns the JsonObject. (requires auth)"),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/aiSummary/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_chart_inter",
			mcplib.WithDescription("Inter-day historical stock chart. Required: sid. Optional: duration. Returns the JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithString("duration", mcplib.Description("Chart duration supported by Tickertape.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/charts/inter/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}, {PublicName: "duration", WireName: "duration", Location: "query"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_chart_intra",
			mcplib.WithDescription("Intra-day stock chart. Required: sid. Returns the JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/charts/intra/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_checklist",
			mcplib.WithDescription("Public company investment checklist records. Required: sid. Returns array of JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/investmentChecklists/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_financials",
			mcplib.WithDescription("Company income statement, balance sheet, or cash flow rows. Required: statement, sid, period, view. Returns array of JsonObject."),
			mcplib.WithString("statement", mcplib.Required(), mcplib.Description("Statement name, such as income, balancesheet, or cashflow.")),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithString("period", mcplib.Required(), mcplib.Description("Annual or quarterly period selector.")),
			mcplib.WithString("view", mcplib.Required(), mcplib.Description("Tickertape financial view selector.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/financials/{statement}/{sid}/{period}/{view}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "statement", WireName: "statement", Location: "path"}, {PublicName: "sid", WireName: "sid", Location: "path"}, {PublicName: "period", WireName: "period", Location: "path"}, {PublicName: "view", WireName: "view", Location: "path"}}, []string{"statement", "sid", "period", "view"}),
	)
	s.AddTool(
		mcplib.NewTool("company_forecast",
			mcplib.WithDescription("Entitlement-aware analyst forecast envelope. Required: sid. Returns the JsonObject. (requires auth)"),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/estimates/forecast/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_info",
			mcplib.WithDescription("Company identity, labels, ratios, and quote metadata. Required: sid. Returns the JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/info/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_news",
			mcplib.WithDescription("Company news records. Required: sid. Returns array of JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/news/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_ratings",
			mcplib.WithDescription("Entitlement-aware analyst ratings envelope. Required: sid. Returns the JsonObject. (requires auth)"),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/ratings/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_ratios",
			mcplib.WithDescription("Key ratio records for a company. Required: sid. Returns array of JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/keyratioList/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_scorecard",
			mcplib.WithDescription("Six-dimension scorecard with locked, rank, callout, and element metadata. Required: sid. Returns array of JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://analyze.api.tickertape.in/stocks/scorecard/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_smallcases",
			mcplib.WithDescription("Public smallcase references associated with a company. Required: sid. Optional: count, offset. Returns array of JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithNumber("count", mcplib.Description("Number of records to return.")),
			mcplib.WithNumber("offset", mcplib.Description("Result offset.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/smallcases/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}, {PublicName: "count", WireName: "count", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("company_summary",
			mcplib.WithDescription("Financial summary, events, news, peers, forecast envelope, and presentations. Required: sid. Returns the JsonObject."),
			mcplib.WithString("sid", mcplib.Required(), mcplib.Description("Tickertape security ID or symbol slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stocks/summary/{sid}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sid", WireName: "sid", Location: "path"}}, []string{"sid"}),
	)
	s.AddTool(
		mcplib.NewTool("deals_ideas",
			mcplib.WithDescription("Public deal ideas and market-mover highlights. Returns array of JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://analyze.api.tickertape.in/stocks/deals/ideas", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("deals_insight",
			mcplib.WithDescription("Deal insights by type, duration, and sort; required values are source-specific. Required: type, duration, sort-by. Returns the JsonObject."),
			mcplib.WithString("type", mcplib.Required(), mcplib.Description("Tickertape deal type.")),
			mcplib.WithString("duration", mcplib.Required(), mcplib.Description("Tickertape duration selector.")),
			mcplib.WithString("sort-by", mcplib.Required(), mcplib.Description("Tickertape sort selector.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://analyze.api.tickertape.in/stocks/deals/insight", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "type", WireName: "type", Location: "query"}, {PublicName: "duration", WireName: "duration", Location: "query"}, {PublicName: "sort-by", WireName: "sortBy", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("homepage_events",
			mcplib.WithDescription("Paginated homepage events with optional asset and type filters. Optional: count, offset, sids (plus 1 more). Returns array of JsonObject."),
			mcplib.WithNumber("count", mcplib.Description("Page size.")),
			mcplib.WithNumber("offset", mcplib.Description("Page offset.")),
			mcplib.WithString("sids", mcplib.Description("Optional comma-separated security IDs.")),
			mcplib.WithString("type", mcplib.Description("Optional Tickertape event type.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://analyze.api.tickertape.in/v2/homepage/events", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "count", WireName: "count", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}, {PublicName: "sids", WireName: "sids", Location: "query"}, {PublicName: "type", WireName: "type", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("market_mood",
			mcplib.WithDescription("Current Market Mood Index and component indicators. Returns the JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mmi/now", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("market_quotes",
			mcplib.WithDescription("Snapshot quotes for comma-separated Tickertape security IDs. Required: sids. Returns array of JsonObject."),
			mcplib.WithString("sids", mcplib.Required(), mcplib.Description("Comma-separated security IDs.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://quotes-api.tickertape.in/quotes", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sids", WireName: "sids", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("market_status",
			mcplib.WithDescription("Market open, closed, holiday, and trading-window status. Required: market. Returns the JsonObject."),
			mcplib.WithString("market", mcplib.Required(), mcplib.Description("Market code, IN or US.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/market/{market}/status", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "market", WireName: "market", Location: "path"}}, []string{"market"}),
	)
	s.AddTool(
		mcplib.NewTool("market_us_latest_quotes",
			mcplib.WithDescription("Latest US quotes keyed by ticker. Required: tickers. Returns the JsonObject."),
			mcplib.WithString("tickers", mcplib.Required(), mcplib.Description("Comma-separated US tickers.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/quotes/US/latest", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "tickers", WireName: "tickers", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_chart_inter",
			mcplib.WithDescription("Mutual-fund historical NAV or return chart. Required: mf-id. Optional: duration. Returns the JsonObject."),
			mcplib.WithString("mf-id", mcplib.Required(), mcplib.Description("Tickertape mutual-fund ID, ISIN, or slug.")),
			mcplib.WithString("duration", mcplib.Description("Chart duration supported by Tickertape.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/{mf_id}/charts/inter", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "mf-id", WireName: "mf_id", Location: "path"}, {PublicName: "duration", WireName: "duration", Location: "query"}}, []string{"mf_id"}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_chart_sip",
			mcplib.WithDescription("Mutual-fund SIP chart. Required: mf-id. Returns the JsonObject."),
			mcplib.WithString("mf-id", mcplib.Required(), mcplib.Description("Tickertape mutual-fund ID, ISIN, or slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/{mf_id}/charts/sip", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "mf-id", WireName: "mf_id", Location: "path"}}, []string{"mf_id"}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_checklist",
			mcplib.WithDescription("Mutual-fund investment checklist records. Required: mf-id. Returns array of JsonObject."),
			mcplib.WithString("mf-id", mcplib.Required(), mcplib.Description("Tickertape mutual-fund ID, ISIN, or slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/{mf_id}/investmentChecklists", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "mf-id", WireName: "mf_id", Location: "path"}}, []string{"mf_id"}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_holdings",
			mcplib.WithDescription("Allocation history, current allocation, sectors, and red-flag counts. Required: mf-id. Returns the JsonObject."),
			mcplib.WithString("mf-id", mcplib.Required(), mcplib.Description("Tickertape mutual-fund ID, ISIN, or slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/{mf_id}/holdings", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "mf-id", WireName: "mf_id", Location: "path"}}, []string{"mf_id"}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_info",
			mcplib.WithDescription("Mutual-fund identity, AMC, NAV, option, and sector labels. Required: mf-id. Returns the JsonObject."),
			mcplib.WithString("mf-id", mcplib.Required(), mcplib.Description("Tickertape mutual-fund ID, ISIN, or slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/{mf_id}/info", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "mf-id", WireName: "mf_id", Location: "path"}}, []string{"mf_id"}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_list",
			mcplib.WithDescription("Mutual-fund universe and identifiers. Returns the JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/list", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_managers",
			mcplib.WithDescription("Fund-manager records. Required: mf-id. Returns array of JsonObject."),
			mcplib.WithString("mf-id", mcplib.Required(), mcplib.Description("Tickertape mutual-fund ID, ISIN, or slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/{mf_id}/fundmanagers", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "mf-id", WireName: "mf_id", Location: "path"}}, []string{"mf_id"}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_summary",
			mcplib.WithDescription("Mutual-fund peers, scheme information, ratios, CAGR, tax, and AMC details. Required: mf-id. Returns the JsonObject."),
			mcplib.WithString("mf-id", mcplib.Required(), mcplib.Description("Tickertape mutual-fund ID, ISIN, or slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/{mf_id}/summary", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "mf-id", WireName: "mf_id", Location: "path"}}, []string{"mf_id"}),
	)
	s.AddTool(
		mcplib.NewTool("mutualfund_widget",
			mcplib.WithDescription("Compact mutual-fund widget and score data. Required: mf-id. Returns the JsonObject."),
			mcplib.WithString("mf-id", mcplib.Required(), mcplib.Description("Tickertape mutual-fund ID, ISIN, or slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mutualfunds/{mf_id}/widget", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "mf-id", WireName: "mf_id", Location: "path"}}, []string{"mf_id"}),
	)
	s.AddTool(
		mcplib.NewTool("screener_equity_filters",
			mcplib.WithDescription("Equity screener filter metadata with premium and locked markers. Returns the JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/screener/filters", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("screener_equity_prebuilt",
			mcplib.WithDescription("Equity prebuilt screen catalog. Returns array of JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/screener/prebuilt", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("screener_equity_universes",
			mcplib.WithDescription("Equity screener universe metadata. Returns array of JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/screener/universes", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("screener_mf_filters",
			mcplib.WithDescription("Mutual-fund screener filter metadata. Returns the JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mf-screener/filters", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("screener_mf_prebuilt",
			mcplib.WithDescription("Mutual-fund prebuilt screen catalog. Returns array of JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mf-screener/prebuilt", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("screener_mf_universes",
			mcplib.WithDescription("Mutual-fund screener universe metadata. Returns array of JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mf-screener/universes", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("search_resource_suggest",
			mcplib.WithDescription("Suggest Indian assets and return search metadata. Required: q. Returns the JsonObject."),
			mcplib.WithString("q", mcplib.Required(), mcplib.Description("Search text, symbol, name, or slug.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/search/suggest", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "q", WireName: "q", Location: "query"}}, []string{"q"}),
	)
	s.AddTool(
		mcplib.NewTool("us_chart",
			mcplib.WithDescription("US security intra-day or inter-day chart. Required: ticker, kind. Optional: duration. Returns the JsonObject."),
			mcplib.WithString("ticker", mcplib.Required(), mcplib.Description("US ticker symbol.")),
			mcplib.WithString("kind", mcplib.Required(), mcplib.Description("Chart kind, intra or inter.")),
			mcplib.WithString("duration", mcplib.Description("Chart duration supported by Tickertape.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/US/securities/{ticker}/charts/{kind}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "ticker", WireName: "ticker", Location: "path"}, {PublicName: "kind", WireName: "kind", Location: "path"}, {PublicName: "duration", WireName: "duration", Location: "query"}}, []string{"ticker", "kind"}),
	)
	s.AddTool(
		mcplib.NewTool("us_etf_info",
			mcplib.WithDescription("US ETF identity and asset metadata. Required: ticker. Returns the JsonObject."),
			mcplib.WithString("ticker", mcplib.Required(), mcplib.Description("Comma-separated US ETF tickers.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/US/etfs/info", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "ticker", WireName: "ticker", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("us_etf_overview",
			mcplib.WithDescription("US ETF overview with type and top holdings. Required: ticker. Returns the JsonObject."),
			mcplib.WithString("ticker", mcplib.Required(), mcplib.Description("US ETF ticker symbol.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/US/etfs/{ticker}/overview", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "ticker", WireName: "ticker", Location: "path"}}, []string{"ticker"}),
	)
	s.AddTool(
		mcplib.NewTool("us_filters",
			mcplib.WithDescription("US security and ETF filter metadata. Returns the JsonObject."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/US/filters", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("us_financials",
			mcplib.WithDescription("US stock income, balance-sheet, or cash-flow financials. Required: ticker, statement. Optional: view. Returns the JsonObject."),
			mcplib.WithString("ticker", mcplib.Required(), mcplib.Description("US ticker symbol.")),
			mcplib.WithString("statement", mcplib.Required(), mcplib.Description("Statement, income, balancesheet, or cashflow.")),
			mcplib.WithString("view", mcplib.Description("Financial view selector.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/US/securities/{ticker}/financials/{statement}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "ticker", WireName: "ticker", Location: "path"}, {PublicName: "statement", WireName: "statement", Location: "path"}, {PublicName: "view", WireName: "view", Location: "query"}}, []string{"ticker", "statement"}),
	)
	s.AddTool(
		mcplib.NewTool("us_security_info",
			mcplib.WithDescription("US security identity and asset metadata. Required: ticker. Returns the JsonObject."),
			mcplib.WithString("ticker", mcplib.Required(), mcplib.Description("Comma-separated US tickers.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/US/securities/info", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "ticker", WireName: "ticker", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("us_security_overview",
			mcplib.WithDescription("US stock overview with metrics, labels, holdings, and peers. Required: ticker. Returns the JsonObject."),
			mcplib.WithString("ticker", mcplib.Required(), mcplib.Description("US ticker symbol.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://gms-api.tickertape.in/US/securities/{ticker}/overview", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "ticker", WireName: "ticker", Location: "path"}}, []string{"ticker"}),
	)
	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext(s),
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      See API docs: https://api.tickertape.in" +
					"\n      Run 'tickertape-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      See API docs: https://api.tickertape.in" +
					"\n      Run 'tickertape-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	return newMCPClientFromConfig(ctx, cfg)
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(ctx context.Context, cfg *config.Config) (*client.Client, *platform.Session, error) {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// MCP calls are live-only; the client never persists domain responses.
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	if err := cli.ApplyClientHooks(c); err != nil {
		if session != nil {
			session.ZeroCredentials()
		}
		return nil, nil, fmt.Errorf("initializing MCP client: %w", err)
	}
	return c, session, nil
}

func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}
func registeredCommandMirrorCapabilities(s *server.MCPServer, capabilities []map[string]string) []map[string]string {
	registered := make([]map[string]string, 0, len(capabilities))
	root := cli.RootCmd()
	for _, capability := range capabilities {
		toolName := cobratree.ToolNameForCommand(s, root, capability["cli_command"])
		if toolName == "" {
			continue
		}
		entry := s.GetTool(toolName)
		if entry == nil || entry.Tool.Meta == nil || entry.Tool.Meta.AdditionalFields["pp:tenant-gate"] != "child-cli" {
			continue
		}
		capability["mcp_tool"] = toolName
		registered = append(registered, capability)
	}
	return registered
}

func handleContext(s *server.MCPServer) func(context.Context, mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		return handleContextResult(s, ctx, req)
	}
}

func handleContextResult(s *server.MCPServer, _ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "tickertape",
		"description": "Live, provenance-aware Tickertape research without stale local market data",
		"archetype":   "crm",
		"tool_count":  len(s.ListTools()),
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion tickertape-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name":        "company",
				"description": "Indian company identity, fundamentals, reports, scorecards, and public signals.",
				"endpoints":   []string{"aggregated_deals", "ai_summary", "chart_inter", "chart_intra", "checklist", "financials", "forecast", "info", "news", "ratings", "ratios", "scorecard", "smallcases", "summary"},
				"searchable":  true,
			},
			{
				"name":        "deals",
				"description": "Public market-mover and deal-idea surfaces.",
				"endpoints":   []string{"ideas", "insight"},
				"searchable":  true,
			},
			{
				"name":        "homepage",
				"description": "Public event and publication stream.",
				"endpoints":   []string{"events"},
				"searchable":  true,
			},
			{
				"name":        "market",
				"description": "Live market-wide status, mood, and quote surfaces.",
				"endpoints":   []string{"mood", "quotes", "status", "us_latest_quotes"},
				"searchable":  true,
			},
			{
				"name":        "mutualfund",
				"description": "Mutual-fund discovery, summary, holdings, charts, managers, and checklists.",
				"endpoints":   []string{"chart_inter", "chart_sip", "checklist", "holdings", "info", "list", "managers", "summary", "widget"},
				"searchable":  true,
			},
			{
				"name":        "screener",
				"description": "Equity and mutual-fund filter catalogs, prebuilt screens, universes, and optional queries.",
				"endpoints":   []string{"equity_filters", "equity_prebuilt", "equity_query", "equity_universes", "mf_filters", "mf_prebuilt", "mf_query", "mf_universes"},
				"read_only":   true,
			},
			{
				"name":        "search_resource",
				"description": "Search and symbol discovery.",
				"endpoints":   []string{"suggest"},
				"searchable":  true,
			},
			{
				"name":        "us",
				"description": "US security and ETF research through Tickertape's global market service.",
				"endpoints":   []string{"chart", "etf_info", "etf_overview", "filters", "financials", "security_info", "security_overview"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass offset parameter for subsequent pages.",
			"Control page size with the count parameter (default 100).",
			"All domain reads are fetched live; no local snapshot or response cache is used.",
			"Use search-resource suggest or the live search command for symbol discovery.",
			"Premium and entitlement errors remain explicit in endpoint response metadata.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": registeredCommandMirrorCapabilities(s, []map[string]string{
			{"name": "Entitlement-aware scorecards", "command": "company scorecard", "cli_command": "company scorecard", "description": "Show Tickertape score dimensions, locked fields, entry-point signals", "rationale": "The scorecard envelope carries source-specific lock and element metadata that generic quote clients discard.", "via": "mcp-command-mirror"},
			{"name": "Company publication timeline", "command": "company timeline", "cli_command": "company timeline", "description": "Combine live company events, news, results, and investor-presentation metadata into a dated source-labelled stream.", "rationale": "The CLI can compose several Tickertape summary arrays into one agent-sized view without inventing cross-source", "via": "mcp-command-mirror"},
			{"name": "Live multi-asset lookup", "command": "lookup", "cli_command": "lookup", "description": "Triages Indian stocks, mutual funds, ETFs, indices", "rationale": "Tickertape exposes an unusually broad cross-asset research graph", "via": "mcp-command-mirror"},
			{"name": "Access and provenance envelope", "command": "inspect access", "cli_command": "inspect access", "description": "Explain source host, route, observation time, entity identity, lock state, and entitlement errors for any live result.", "rationale": "Undocumented web-app routes and premium fields make silent omission dangerous", "via": "mcp-command-mirror"},
			{"name": "MMI component brief", "command": "market brief", "cli_command": "market brief", "description": "Turn the live Market Mood Index payload into a concise timestamped brief of fear/greed, FII, momentum, volatility", "rationale": "The MMI endpoint returns heterogeneous indicators that benefit from a stable agent-facing presentation without", "via": "mcp-command-mirror"},
			{"name": "Source-specific company research brief", "command": "company brief", "cli_command": "company brief", "description": "Compose live company identity, summary, scorecard, reports, and access state into one bounded triage response.", "rationale": "The CLI can join related Tickertape routes for one request without storing domain history or flattening source-specific", "via": "mcp-command-mirror"},
			{"name": "Live screener catalog navigator", "command": "screen catalog", "cli_command": "screen catalog", "description": "Organize equity and mutual-fund filters, categories, universes, and prebuilt screens while preserving premium markers.", "rationale": "The catalog is public metadata", "via": "mcp-command-mirror"},
		}),
		"playbook": []map[string]string{
			{"topic": "Entitlement-aware scorecards", "insight": "The scorecard envelope carries source-specific lock and element metadata that generic quote clients discard."},
			{"topic": "Company publication timeline", "insight": "The CLI can compose several Tickertape summary arrays into one agent-sized view without inventing cross-source equivalence."},
			{"topic": "Live multi-asset lookup", "insight": "Tickertape exposes an unusually broad cross-asset research graph, and the CLI can route it without creating a local mirror."},
			{"topic": "Access and provenance envelope", "insight": "Undocumented web-app routes and premium fields make silent omission dangerous; the CLI can preserve the evidence envelope on every call."},
			{"topic": "MMI component brief", "insight": "The MMI endpoint returns heterogeneous indicators that benefit from a stable agent-facing presentation without persisting a snapshot."},
			{"topic": "Source-specific company research brief", "insight": "The CLI can join related Tickertape routes for one request without storing domain history or flattening source-specific opinions."},
			{"topic": "Live screener catalog navigator", "insight": "The catalog is public metadata, while saved screens and query execution are separate sensitive or contract-uncertain workflows."},
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "Tickertape research commands fetch current public routes and preserve source and observation metadata."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
