// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Auction struct {
	AuctionNumber string  `json:"auction_number"`
	Exchange      string  `json:"exchange"`
	Tradingsymbol string  `json:"tradingsymbol"`
	Quantity      int     `json:"quantity"`
	Price         float64 `json:"price"`
}

type GTTTrigger struct {
	Id        string          `json:"id"`
	Status    string          `json:"status"`
	Type      string          `json:"type"`
	Condition json.RawMessage `json:"condition"`
	Orders    json.RawMessage `json:"orders"`
	ExpiresAt string          `json:"expires_at"`
}

type Holding struct {
	Tradingsymbol       string  `json:"tradingsymbol"`
	Exchange            string  `json:"exchange"`
	Isin                string  `json:"isin"`
	Product             string  `json:"product"`
	Quantity            int     `json:"quantity"`
	T1Quantity          int     `json:"t1_quantity"`
	AveragePrice        float64 `json:"average_price"`
	LastPrice           float64 `json:"last_price"`
	ClosePrice          float64 `json:"close_price"`
	Pnl                 float64 `json:"pnl"`
	DayChange           float64 `json:"day_change"`
	DayChangePercentage float64 `json:"day_change_percentage"`
}

type MarginSegment struct {
	Enabled   bool            `json:"enabled"`
	Net       float64         `json:"net"`
	Available json.RawMessage `json:"available"`
	Utilised  json.RawMessage `json:"utilised"`
}

type Margins struct {
	Equity    json.RawMessage `json:"equity"`
	Commodity json.RawMessage `json:"commodity"`
}

type Order struct {
	OrderId                 string  `json:"order_id"`
	ExchangeOrderId         string  `json:"exchange_order_id"`
	ParentOrderId           string  `json:"parent_order_id"`
	Status                  string  `json:"status"`
	StatusMessage           string  `json:"status_message"`
	OrderTimestamp          string  `json:"order_timestamp"`
	ExchangeUpdateTimestamp string  `json:"exchange_update_timestamp"`
	ExchangeTimestamp       string  `json:"exchange_timestamp"`
	Variety                 string  `json:"variety"`
	Modified                bool    `json:"modified"`
	Exchange                string  `json:"exchange"`
	Tradingsymbol           string  `json:"tradingsymbol"`
	OrderType               string  `json:"order_type"`
	TransactionType         string  `json:"transaction_type"`
	Validity                string  `json:"validity"`
	Product                 string  `json:"product"`
	Quantity                int     `json:"quantity"`
	Price                   float64 `json:"price"`
	TriggerPrice            float64 `json:"trigger_price"`
	AveragePrice            float64 `json:"average_price"`
	FilledQuantity          int     `json:"filled_quantity"`
	PendingQuantity         int     `json:"pending_quantity"`
	CancelledQuantity       int     `json:"cancelled_quantity"`
	Tag                     string  `json:"tag"`
}

type PositionBook struct {
	Net json.RawMessage `json:"net"`
	Day json.RawMessage `json:"day"`
}

type Profile struct {
	UserId        string `json:"user_id"`
	UserName      string `json:"user_name"`
	Email         string `json:"email"`
	UserShortname string `json:"user_shortname"`
	Broker        string `json:"broker"`
	Products      string `json:"products"`
	Exchanges     string `json:"exchanges"`
	OrderTypes    string `json:"order_types"`
}

type Trade struct {
	TradeId           string  `json:"trade_id"`
	OrderId           string  `json:"order_id"`
	Exchange          string  `json:"exchange"`
	Tradingsymbol     string  `json:"tradingsymbol"`
	InstrumentToken   string  `json:"instrument_token"`
	Product           string  `json:"product"`
	AveragePrice      float64 `json:"average_price"`
	Quantity          int     `json:"quantity"`
	ExchangeOrderId   string  `json:"exchange_order_id"`
	TransactionType   string  `json:"transaction_type"`
	FillTimestamp     string  `json:"fill_timestamp"`
	ExchangeTimestamp string  `json:"exchange_timestamp"`
}
