// Copyright 2026 abhirup and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Account struct {
	AccountId           string          `json:"accountId"`
	AccountName         string          `json:"accountName"`
	CurrentAccountValue float64         `json:"currentAccountValue"`
	Permissions         json.RawMessage `json:"permissions"`
}

type AiEngineConfig struct {
	InferenceOptions  json.RawMessage `json:"inferenceOptions"`
	Inputs            []Input         `json:"inputs"`
	Outcomes          []Outcome       `json:"outcomes"`
	PredictEngineType string          `json:"predictEngineType"`
}

type Analytic struct {
	AccountValue     float64          `json:"accountValue"`
	CurrentMonthData CurrentMonthData `json:"currentMonthData"`
	MonthlyData      MonthlyData      `json:"monthlyData"`
}

type BatchConfig struct {
	BatchMode    string `json:"batchMode"`
	MaxBatchSize int    `json:"maxBatchSize"`
}

type Buildlog struct {
	PublicLogsUrl string `json:"publicLogsUrl"`
}

type Console struct {
	Auth0ClientId   string `json:"auth0ClientId"`
	Auth0DomainName string `json:"auth0DomainName"`
	ClientType      string `json:"clientType"`
	FastAPIBaseUrl  string `json:"fastAPIBaseUrl"`
	PayPalClientId  string `json:"payPalClientId"`
}

type CurrentMonthData struct {
	MoneyEarned        MoneyEarned       `json:"moneyEarned"`
	MoneyEarnedByModel json.RawMessage   `json:"moneyEarnedByModel"`
	MoneySpent         MoneySpent        `json:"moneySpent"`
	MoneySpentByModel  MoneySpentByModel `json:"moneySpentByModel"`
	UsageEarned        UsageEarned       `json:"usageEarned"`
	UsageEarnedByModel json.RawMessage   `json:"usageEarnedByModel"`
	UsageSpent         UsageSpent        `json:"usageSpent"`
	UsageSpentByModel  UsageSpentByModel `json:"usageSpentByModel"`
}

type DevAbhirupdas8C0AF724114435 struct {
	AboutMe              string          `json:"aboutMe"`
	DisplayName          string          `json:"displayName"`
	FirstName            string          `json:"firstName"`
	LastName             string          `json:"lastName"`
	NumberOfPublicModels int             `json:"numberOfPublicModels"`
	PublicName           string          `json:"publicName"`
	SocialInfo           json.RawMessage `json:"socialInfo"`
	TotalNumberOfModels  int             `json:"totalNumberOfModels"`
}

type EngineFile struct {
	FileName string `json:"fileName"`
	FileType string `json:"fileType"`
}

type File struct {
	FileName string `json:"fileName"`
	FileType string `json:"fileType"`
}

type FilePaths struct {
	MODELDESCRIPTION string `json:"MODELDESCRIPTION"`
}

type InferenceTimeStats struct {
	Count    int    `json:"count"`
	Max      string `json:"max"`
	Mean     string `json:"mean"`
	Min      string `json:"min"`
	Sum      int    `json:"sum"`
	SumSq    int    `json:"sumSq"`
	Variance string `json:"variance"`
}

type Input struct {
	DefaultValue     string          `json:"defaultValue"`
	InputDescription string          `json:"inputDescription"`
	InputType        string          `json:"inputType"`
	Name             string          `json:"name"`
	Options          json.RawMessage `json:"options"`
}

type InputmessageInputcon struct {
	EnableMultiLineText bool `json:"enableMultiLineText"`
	EnablePictureViewer bool `json:"enablePictureViewer"`
	EnableValidation    bool `json:"enableValidation"`
	HiddenVariable      bool `json:"hiddenVariable"`
	UseChatbotInterface bool `json:"useChatbotInterface"`
}

type InterfaceDisplayOptions struct {
	ChatbotCustomCSS    string `json:"chatbotCustomCSS"`
	ChatbotStartMessage string `json:"chatbotStartMessage"`
}

type LastBuildResults struct {
	Status string `json:"status"`
}

type MODELDESCRIPTION struct {
	DestinationPath  string `json:"destinationPath"`
	FileKey          string `json:"fileKey"`
	FileName         string `json:"fileName"`
	PublicUploadLink string `json:"publicUploadLink"`
}

type Model struct {
	Active                     bool                    `json:"active"`
	AiEngineConfig             AiEngineConfig          `json:"aiEngineConfig"`
	AllowPublicComponentAccess bool                    `json:"allowPublicComponentAccess"`
	AppEngineId                string                  `json:"appEngineId"`
	Author                     string                  `json:"author"`
	ComputeType                string                  `json:"computeType"`
	EngineCostPerSecond        int                     `json:"engineCostPerSecond"`
	EngineStatus               string                  `json:"engineStatus"`
	EntityType                 string                  `json:"entityType"`
	Id                         string                  `json:"id"`
	InterfaceDisplayOptions    InterfaceDisplayOptions `json:"interfaceDisplayOptions"`
	InterfaceType              string                  `json:"interfaceType"`
	IsPublic                   bool                    `json:"isPublic"`
	LongRunningInference       bool                    `json:"longRunningInference"`
	ModelAlias                 string                  `json:"modelAlias"`
	ModelData                  ModelData               `json:"modelData"`
	ModelDescription           string                  `json:"modelDescription"`
	ModelId                    string                  `json:"modelId"`
	ModelLongDescription       string                  `json:"modelLongDescription"`
	ModelName                  string                  `json:"modelName"`
	ModelType                  string                  `json:"modelType"`
	NeedsContext               bool                    `json:"needsContext"`
	OwnerSubscriptionType      string                  `json:"ownerSubscriptionType,omitempty"`
	ParentRepositoryId         string                  `json:"parentRepositoryId"`
	PerformanceScore           int                     `json:"performanceScore"`
	PerformanceStats           PerformanceStats        `json:"performanceStats"`
	Permissions                json.RawMessage         `json:"permissions"`
	PricingInfo                PricingInfo             `json:"pricingInfo"`
	SocialStatus               SocialStatus2           `json:"socialStatus,omitempty"`
	SupportedInterfaces        json.RawMessage         `json:"supportedInterfaces"`
	SupportingLinks            json.RawMessage         `json:"supportingLinks"`
	Tags                       json.RawMessage         `json:"tags"`
	TotalCost                  int                     `json:"totalCost"`
	TotalInferences            int                     `json:"totalInferences"`
	TotalViews                 int                     `json:"totalViews"`
	VariableDisplayOptions     VariableDisplayOptions  `json:"variableDisplayOptions"`
	Visibility                 string                  `json:"visibility"`
}

type ModelData struct {
	FilePaths FilePaths `json:"filePaths"`
}

type MoneyEarned struct {
	V01092026 int `json:"01/09/2026"`
	V02092026 int `json:"02/09/2026"`
	V03092026 int `json:"03/09/2026"`
	V04092026 int `json:"04/09/2026"`
	V05092026 int `json:"05/09/2026"`
	V06092026 int `json:"06/09/2026"`
	V07092026 int `json:"07/09/2026"`
	V08092026 int `json:"08/09/2026"`
	V09092026 int `json:"09/09/2026"`
	V10092026 int `json:"10/09/2026"`
	V11092026 int `json:"11/09/2026"`
	V12092026 int `json:"12/09/2026"`
	V13092026 int `json:"13/09/2026"`
	V14092026 int `json:"14/09/2026"`
	V15092026 int `json:"15/09/2026"`
	V16092026 int `json:"16/09/2026"`
	V17092026 int `json:"17/09/2026"`
	V18092026 int `json:"18/09/2026"`
	V19092026 int `json:"19/09/2026"`
}

type MoneyEarned2 struct {
	V012026 int `json:"01/2026"`
	V022026 int `json:"02/2026"`
	V032026 int `json:"03/2026"`
	V042026 int `json:"04/2026"`
	V052026 int `json:"05/2026"`
	V062026 int `json:"06/2026"`
	V072026 int `json:"07/2026"`
	V082026 int `json:"08/2026"`
	V092026 int `json:"09/2026"`
	V102025 int `json:"10/2025"`
	V112025 int `json:"11/2025"`
	V122025 int `json:"12/2025"`
}

type MoneySpent struct {
	V01092026 int     `json:"01/09/2026"`
	V02092026 int     `json:"02/09/2026"`
	V03092026 int     `json:"03/09/2026"`
	V04092026 int     `json:"04/09/2026"`
	V05092026 float64 `json:"05/09/2026"`
	V06092026 int     `json:"06/09/2026"`
	V07092026 int     `json:"07/09/2026"`
	V08092026 int     `json:"08/09/2026"`
	V09092026 int     `json:"09/09/2026"`
	V10092026 int     `json:"10/09/2026"`
	V11092026 int     `json:"11/09/2026"`
	V12092026 int     `json:"12/09/2026"`
	V13092026 int     `json:"13/09/2026"`
	V14092026 int     `json:"14/09/2026"`
	V15092026 int     `json:"15/09/2026"`
	V16092026 int     `json:"16/09/2026"`
	V17092026 int     `json:"17/09/2026"`
	V18092026 int     `json:"18/09/2026"`
	V19092026 int     `json:"19/09/2026"`
}

type MoneySpent2 struct {
	V012026 int     `json:"01/2026"`
	V022026 int     `json:"02/2026"`
	V032026 int     `json:"03/2026"`
	V042026 int     `json:"04/2026"`
	V052026 int     `json:"05/2026"`
	V062026 int     `json:"06/2026"`
	V072026 int     `json:"07/2026"`
	V082026 int     `json:"08/2026"`
	V092026 float64 `json:"09/2026"`
	V102025 int     `json:"10/2025"`
	V112025 int     `json:"11/2025"`
	V122025 int     `json:"12/2025"`
}

type MoneySpentByModel struct {
	CoinGradingVLLMOpenGVLabInternVL38B int     `json:"CoinGrading - VLLM - OpenGVLab_InternVL3-8B"`
	LlamaCppTest                        int     `json:"LlamaCppTest"`
	QwenOmniCoin                        int     `json:"Qwen Omni Coin"`
	WANT2V                              int     `json:"WAN-T2V"`
	WhisperXSpeakerDiarization          float64 `json:"WhisperX - Speaker Diarization"`
}

type MoneySpentByModel2 struct {
	CoinGradingVLLMOpenGVLabInternVL314B float64 `json:"CoinGrading - VLLM - OpenGVLab_InternVL3-14B"`
	CoinGradingVLLMQwen25VLInstruct7B    float64 `json:"CoinGrading - VLLM - Qwen2.5-VL-Instruct-7B"`
	MistralVLLMOfficial                  float64 `json:"Mistral VLLM Official"`
	MistralVLLMSelfHost                  float64 `json:"Mistral VLLM SelfHost"`
	Other                                float64 `json:"Other"`
	WANT2V                               float64 `json:"WAN-T2V"`
}

type MonthlyData struct {
	MoneyEarned        MoneyEarned2       `json:"moneyEarned"`
	MoneyEarnedByModel json.RawMessage    `json:"moneyEarnedByModel"`
	MoneySpent         MoneySpent2        `json:"moneySpent"`
	MoneySpentByModel  MoneySpentByModel2 `json:"moneySpentByModel"`
	UsageEarned        UsageEarned2       `json:"usageEarned"`
	UsageEarnedByModel json.RawMessage    `json:"usageEarnedByModel"`
	UsageSpent         UsageSpent2        `json:"usageSpent"`
	UsageSpentByModel  UsageSpentByModel2 `json:"usageSpentByModel"`
}

type NewInputInputcon struct {
	EnableMultiLineText bool `json:"enableMultiLineText"`
	EnablePictureViewer bool `json:"enablePictureViewer"`
	EnableValidation    bool `json:"enableValidation"`
	HiddenVariable      bool `json:"hiddenVariable"`
	UseChatbotInterface bool `json:"useChatbotInterface"`
}

type Outcome struct {
	DefaultValue       string          `json:"defaultValue"`
	Name               string          `json:"name"`
	Options            json.RawMessage `json:"options"`
	OutcomeDescription string          `json:"outcomeDescription"`
	OutcomeType        string          `json:"outcomeType"`
}

type OutputmessageOutputcon struct {
	EnableMultiLineText bool `json:"enableMultiLineText"`
	EnablePictureViewer bool `json:"enablePictureViewer"`
	EnableValidation    bool `json:"enableValidation"`
	HiddenVariable      bool `json:"hiddenVariable"`
	UseChatbotInterface bool `json:"useChatbotInterface"`
}

type PerformanceStats struct {
	Accuracy  int             `json:"accuracy"`
	Auc       int             `json:"auc"`
	BleuScore int             `json:"bleuScore"`
	DunnIndex int             `json:"dunnIndex"`
	F1Score   int             `json:"f1Score"`
	Metrics   json.RawMessage `json:"metrics"`
	Precision int             `json:"precision"`
	R2        int             `json:"r2"`
	Recall    int             `json:"recall"`
}

type PlatformInfo struct {
	AllowAdditionalDockerCommands bool            `json:"allowAdditionalDockerCommands"`
	ComputeCostPerSecond          float64         `json:"computeCostPerSecond"`
	ContainerBasedPlatform        bool            `json:"containerBasedPlatform"`
	Description                   string          `json:"description"`
	FriendlyName                  string          `json:"friendlyName"`
	MaxAllowedGPUMemory           int             `json:"maxAllowedGPUMemory"`
	MaxAllowedMemory              int             `json:"maxAllowedMemory"`
	MaxAllowedStorage             int             `json:"maxAllowedStorage"`
	MinAllowedGPUMemory           int             `json:"minAllowedGPUMemory"`
	MinAllowedMemory              int             `json:"minAllowedMemory"`
	MinAllowedStorage             int             `json:"minAllowedStorage"`
	PerGBGPUMemoryPricing         string          `json:"perGBGPUMemoryPricing"`
	PerGBMemoryPricing            float64         `json:"perGBMemoryPricing"`
	PerGBStoragePricing           float64         `json:"perGBStoragePricing"`
	PlatformKey                   string          `json:"platformKey"`
	RecommendedBaseImages         json.RawMessage `json:"recommendedBaseImages"`
}

type PricingInfo struct {
	EnableMonetization           bool   `json:"enableMonetization"`
	ModelOwnerPaysComputeCost    bool   `json:"modelOwnerPaysComputeCost"`
	NoChargeOnInferenceWithError bool   `json:"noChargeOnInferenceWithError"`
	ServicePricingInfo           string `json:"servicePricingInfo"`
	SkipUsageChargeInSameCtx     bool   `json:"skipUsageChargeInSameCtx"`
}

type ReconresultOutputcon struct {
	EnableMultiLineText bool `json:"enableMultiLineText"`
	EnablePictureViewer bool `json:"enablePictureViewer"`
	EnableValidation    bool `json:"enableValidation"`
	HiddenVariable      bool `json:"hiddenVariable"`
	UseChatbotInterface bool `json:"useChatbotInterface"`
}

type Router struct {
	ClientType     string `json:"clientType"`
	FastAPIBaseUrl string `json:"fastAPIBaseUrl"`
	PayPalClientId string `json:"payPalClientId"`
}

type Search struct {
	EntityType             string          `json:"entityType"`
	Id                     string          `json:"id"`
	OwnerId                string          `json:"ownerId"`
	Permissions            json.RawMessage `json:"permissions"`
	RepositoryAccessRights json.RawMessage `json:"repositoryAccessRights"`
	RepositoryDescription  string          `json:"repositoryDescription"`
	RepositoryId           string          `json:"repositoryId"`
	RepositoryName         string          `json:"repositoryName"`
}

type SearchResult struct {
	EntityType       string       `json:"entityType"`
	FavIconUrl       string       `json:"favIconUrl"`
	IsPublic         bool         `json:"isPublic"`
	ModelAlias       string       `json:"modelAlias"`
	ModelCategory    string       `json:"modelCategory"`
	ModelDescription string       `json:"modelDescription"`
	ModelId          string       `json:"modelId"`
	ModelName        string       `json:"modelName"`
	ModelTitle       string       `json:"modelTitle"`
	ModelType        string       `json:"modelType"`
	PerformanceScore int          `json:"performanceScore"`
	SocialStatus     SocialStatus `json:"socialStatus"`
	ThumbnailUrl     string       `json:"thumbnailUrl"`
	Visibility       string       `json:"visibility"`
}

type SocialStatus struct {
	AverageStarRating int `json:"averageStarRating"`
	InferenceCount    int `json:"inferenceCount"`
	RatingCount       int `json:"ratingCount"`
	ViewCount         int `json:"viewCount"`
}

type SocialStatus2 struct {
	AverageStarRating int `json:"averageStarRating"`
	InferenceCount    int `json:"inferenceCount"`
	RatingCount       int `json:"ratingCount"`
	ViewCount         int `json:"viewCount"`
}

type SourceFile struct {
	PublicDownloadLink string `json:"publicDownloadLink"`
}

type StateInfo struct {
	HistoricalNodeCountStats json.RawMessage `json:"historicalNodeCountStats"`
	NumRunningInstances      int             `json:"numRunningInstances"`
	RunningNodes             json.RawMessage `json:"runningNodes"`
}

type Supportedengine struct {
	AllowAdditionalDockerCommands bool            `json:"allowAdditionalDockerCommands"`
	ComputeCostPerSecond          float64         `json:"computeCostPerSecond"`
	ContainerBasedPlatform        bool            `json:"containerBasedPlatform"`
	Description                   string          `json:"description"`
	EntryPointTemplateUrl         string          `json:"entryPointTemplateUrl"`
	FriendlyName                  string          `json:"friendlyName"`
	MaxAllowedGPUMemory           int             `json:"maxAllowedGPUMemory"`
	MaxAllowedMemory              int             `json:"maxAllowedMemory"`
	MaxAllowedStorage             int             `json:"maxAllowedStorage"`
	MinAllowedGPUMemory           int             `json:"minAllowedGPUMemory"`
	MinAllowedMemory              int             `json:"minAllowedMemory"`
	MinAllowedStorage             int             `json:"minAllowedStorage"`
	PerGBGPUMemoryPricing         string          `json:"perGBGPUMemoryPricing"`
	PerGBMemoryPricing            float64         `json:"perGBMemoryPricing"`
	PerGBStoragePricing           float64         `json:"perGBStoragePricing"`
	PlatformKey                   string          `json:"platformKey"`
	PlatformTemplateUrl           string          `json:"platformTemplateUrl"`
	RecommendedBaseImages         json.RawMessage `json:"recommendedBaseImages"`
}

type UsageEarned struct {
	V01092026 int `json:"01/09/2026"`
	V02092026 int `json:"02/09/2026"`
	V03092026 int `json:"03/09/2026"`
	V04092026 int `json:"04/09/2026"`
	V05092026 int `json:"05/09/2026"`
	V06092026 int `json:"06/09/2026"`
	V07092026 int `json:"07/09/2026"`
	V08092026 int `json:"08/09/2026"`
	V09092026 int `json:"09/09/2026"`
	V10092026 int `json:"10/09/2026"`
	V11092026 int `json:"11/09/2026"`
	V12092026 int `json:"12/09/2026"`
	V13092026 int `json:"13/09/2026"`
	V14092026 int `json:"14/09/2026"`
	V15092026 int `json:"15/09/2026"`
	V16092026 int `json:"16/09/2026"`
	V17092026 int `json:"17/09/2026"`
	V18092026 int `json:"18/09/2026"`
	V19092026 int `json:"19/09/2026"`
}

type UsageEarned2 struct {
	V012026 int `json:"01/2026"`
	V022026 int `json:"02/2026"`
	V032026 int `json:"03/2026"`
	V042026 int `json:"04/2026"`
	V052026 int `json:"05/2026"`
	V062026 int `json:"06/2026"`
	V072026 int `json:"07/2026"`
	V082026 int `json:"08/2026"`
	V092026 int `json:"09/2026"`
	V102025 int `json:"10/2025"`
	V112025 int `json:"11/2025"`
	V122025 int `json:"12/2025"`
}

type UsageSpent struct {
	V01092026 int `json:"01/09/2026"`
	V02092026 int `json:"02/09/2026"`
	V03092026 int `json:"03/09/2026"`
	V04092026 int `json:"04/09/2026"`
	V05092026 int `json:"05/09/2026"`
	V06092026 int `json:"06/09/2026"`
	V07092026 int `json:"07/09/2026"`
	V08092026 int `json:"08/09/2026"`
	V09092026 int `json:"09/09/2026"`
	V10092026 int `json:"10/09/2026"`
	V11092026 int `json:"11/09/2026"`
	V12092026 int `json:"12/09/2026"`
	V13092026 int `json:"13/09/2026"`
	V14092026 int `json:"14/09/2026"`
	V15092026 int `json:"15/09/2026"`
	V16092026 int `json:"16/09/2026"`
	V17092026 int `json:"17/09/2026"`
	V18092026 int `json:"18/09/2026"`
	V19092026 int `json:"19/09/2026"`
}

type UsageSpent2 struct {
	V012026 int `json:"01/2026"`
	V022026 int `json:"02/2026"`
	V032026 int `json:"03/2026"`
	V042026 int `json:"04/2026"`
	V052026 int `json:"05/2026"`
	V062026 int `json:"06/2026"`
	V072026 int `json:"07/2026"`
	V082026 int `json:"08/2026"`
	V092026 int `json:"09/2026"`
	V102025 int `json:"10/2025"`
	V112025 int `json:"11/2025"`
	V122025 int `json:"12/2025"`
}

type UsageSpentByModel struct {
	LlamaCppTest               int `json:"LlamaCppTest"`
	PPReconScratch             int `json:"PP Recon Scratch"`
	QwenOmniCoin               int `json:"Qwen Omni Coin"`
	WANT2V                     int `json:"WAN-T2V"`
	WhisperXSpeakerDiarization int `json:"WhisperX - Speaker Diarization"`
}

type UsageSpentByModel2 struct {
	CoinGradingVLLMQwen25VLInstruct7B int `json:"CoinGrading - VLLM - Qwen2.5-VL-Instruct-7B"`
	MistralVLLMSelfHost               int `json:"Mistral VLLM SelfHost"`
	Other                             int `json:"Other"`
	SubtitleTranslationLLM            int `json:"Subtitle Translation LLM"`
	WANT2V                            int `json:"WAN-T2V"`
	VllmTest                          int `json:"vllm-test"`
}

type UserengineResult struct {
	AllowInterruptableInference bool               `json:"allowInterruptableInference"`
	BatchConfig                 BatchConfig        `json:"batchConfig"`
	BuildNumber                 int                `json:"buildNumber"`
	CreatedDate                 string             `json:"createdDate"`
	DeployedBuildNumber         int                `json:"deployedBuildNumber"`
	EnableChainedModels         bool               `json:"enableChainedModels"`
	EngineDescription           string             `json:"engineDescription"`
	EngineId                    string             `json:"engineId"`
	EngineName                  string             `json:"engineName"`
	EnginePlatformKey           string             `json:"enginePlatformKey"`
	EnginePlatformName          string             `json:"enginePlatformName"`
	EntityType                  string             `json:"entityType"`
	Files                       []File             `json:"files"`
	GpuMemoryRequirement        int                `json:"gpuMemoryRequirement"`
	Id                          string             `json:"id"`
	InferenceTimeStats          InferenceTimeStats `json:"inferenceTimeStats"`
	LastBuildResults            LastBuildResults   `json:"lastBuildResults"`
	MaximumRunTime              string             `json:"maximumRunTime"`
	MemoryRequirement           int                `json:"memoryRequirement"`
	ModifiedDate                string             `json:"modifiedDate"`
	PackageDefinitionFileName   string             `json:"packageDefinitionFileName"`
	ParentRepositoryId          string             `json:"parentRepositoryId"`
	ParentRepositoryName        string             `json:"parentRepositoryName"`
	Permissions                 json.RawMessage    `json:"permissions"`
	PlatformInfo                PlatformInfo       `json:"platformInfo"`
	RunOnDedicatedInstance      bool               `json:"runOnDedicatedInstance"`
	SelectedBaseImage           string             `json:"selectedBaseImage"`
	StateInfo                   StateInfo          `json:"stateInfo"`
	Status                      string             `json:"status"`
	StorageRequirement          int                `json:"storageRequirement"`
}

type UsermodelResult struct {
	EntityType           string `json:"entityType"`
	IsPublic             bool   `json:"isPublic"`
	ModelAlias           string `json:"modelAlias"`
	ModelId              string `json:"modelId"`
	ModelName            string `json:"modelName"`
	ModelType            string `json:"modelType"`
	ParentRepositoryName string `json:"parentRepositoryName"`
	PerformanceScore     int    `json:"performanceScore"`
	Visibility           string `json:"visibility"`
}

type VariableDisplayOptions struct {
	InputmessageInputcon   InputmessageInputcon   `json:"inputmessage_inputcon"`
	NewInputInputcon       NewInputInputcon       `json:"new_input_inputcon"`
	OutputmessageOutputcon OutputmessageOutputcon `json:"outputmessage_outputcon"`
	ReconresultOutputcon   ReconresultOutputcon   `json:"reconresult_outputcon"`
}
