// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"tickertape-pp-cli/internal/auth"
	"tickertape-pp-cli/internal/cliutil"
)

type Config struct {
	BaseURL       string            `json:"base_url"`
	AuthHeaderVal string            `json:"auth_header"`
	Headers       map[string]string `json:"headers,omitempty"`
	AuthSource    string            `json:"-"`
	Path          string            `json:"-"`
	envOverrides  map[string]bool   `json:"-"`
	fileConfig    *Config           `json:"-"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://api.tickertape.in",
	}

	// Resolve config path
	path, explicitConfigFile, err := resolveConfigPath(configPath)
	if err != nil {
		return nil, err
	}
	cfg.Path = path

	if explicitConfigFile {
		if err := readConfigFile(path, cfg, "config-kind path"); err != nil && !os.IsNotExist(err) {
			return nil, err
		}
	} else {
		legacyPath, err := LegacyConfigPath()
		if err != nil {
			return nil, err
		}
		data, sourcePath, err := cliutil.ReadFileWithLegacyFallback(path, legacyPath)
		if err != nil {
			if !os.IsNotExist(err) {
				return nil, err
			}
		} else {
			owner := "config-kind path"
			if sourcePath == legacyPath {
				owner = "legacy config path"
			}
			parsed := *cfg
			if err := parseConfigData(data, &parsed, sourcePath, owner); err != nil {
				if sourcePath == legacyPath {
					fmt.Fprintf(os.Stderr, "warning: legacy config parse skipped for %s: %v\n", sourcePath, err)
				} else {
					return nil, err
				}
			} else {
				*cfg = parsed
			}
		}
	}
	cfg.Path = path

	cfg.snapshotFileConfig()

	// Credentials are resolved without ever writing domain data. Explicit
	// environment credentials take precedence for CI; otherwise use the
	// macOS Keychain entry created by `auth import --stdin`; finally retain
	// the legacy config-file credential for compatibility.
	if envCreds, source, envErr := auth.EnvironmentCredentials(); envErr == nil {
		cfg.applyCredentials(envCreds, source)
	} else if !errors.Is(envErr, auth.ErrNotFound) {
		return nil, envErr
	} else if keychainCreds, keychainErr := auth.ReadKeychain(context.Background()); keychainErr == nil {
		cfg.applyCredentials(keychainCreds, "keychain")
	} else if !errors.Is(keychainErr, auth.ErrNotFound) {
		return nil, keychainErr
	} else if cfg.CredentialConfigured() {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := cliutil.EnvOverride("TICKERTAPE_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	return cfg, nil
}

func resolveConfigPath(configPath string) (string, bool, error) {
	if strings.TrimSpace(configPath) != "" {
		return configPath, true, nil
	}
	if path := os.Getenv("TICKERTAPE_CONFIG"); path != "" {
		return path, true, nil
	}
	dir, err := cliutil.ConfigDir()
	if err != nil {
		return "", false, err
	}
	return filepath.Join(dir, "config.json"), false, nil
}

func LegacyConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve legacy config path: %w", err)
	}
	return filepath.Join(home, ".config", "tickertape-pp-cli", "config.json"), nil
}

func readConfigFile(path string, cfg *Config, owner string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return parseConfigData(data, cfg, path, owner)
}

func parseConfigData(data []byte, cfg *Config, path string, owner string) error {
	if err := json.Unmarshal(data, cfg); err != nil {
		return fmt.Errorf("parsing %s %s: %w", owner, path, err)
	}
	return nil
}

func (c *Config) applyCredentials(creds auth.Credentials, source string) {
	if creds.AuthHeader != "" {
		c.AuthHeaderVal = creds.AuthHeader
	}
	if len(creds.Headers) > 0 {
		if c.Headers == nil {
			c.Headers = map[string]string{}
		}
		for key, value := range creds.Headers {
			c.Headers[key] = value
		}
	}
	c.AuthSource = source
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	return ""
}

func (c *Config) StoreScopeCredential() string {
	if c == nil {
		return ""
	}
	if header := c.AuthHeader(); header != "" {
		return header
	}

	var parts []string
	if c.AuthHeaderVal != "" {
		parts = append(parts, "auth_header="+c.AuthHeaderVal)
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, "\n")
}

// Raw browser-session values count as credentials even when no header
// representation exists; hand-coded flows may also preserve a working header.
func (c *Config) CredentialConfigured() bool {
	if c == nil {
		return false
	}
	if c.AuthHeader() != "" {
		return true
	}
	for key, value := range c.Headers {
		if strings.EqualFold(key, "Cookie") && strings.TrimSpace(value) != "" {
			return true
		}
	}
	return false
}

func (c *Config) markEnvOverride(field string) {
	if c.envOverrides == nil {
		c.envOverrides = map[string]bool{}
	}
	c.envOverrides[field] = true
}

// cloneStringMap returns an independent copy of m (nil stays nil). The fileConfig
// snapshot must not share reference-type map fields (such as Headers) with the
// live config, or a later mutation to one would silently track in the other.
func cloneStringMap(m map[string]string) map[string]string {
	if m == nil {
		return nil
	}
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

func (c *Config) snapshotFileConfig() {
	snapshot := *c
	snapshot.envOverrides = nil
	snapshot.fileConfig = nil
	// *c is a shallow copy: map fields are reference types, so the snapshot would
	// share them with c and silently track later mutations, defeating the
	// isolation this snapshot exists to provide. Clone them.
	snapshot.Headers = cloneStringMap(c.Headers)
	c.fileConfig = &snapshot
}

func (c *Config) configForSave() Config {
	out := *c
	if c.fileConfig != nil {
	}
	out.envOverrides = nil
	out.fileConfig = nil
	return out
}

func (c *Config) updateFileConfigField(field string) {
	if c.fileConfig == nil || c.envOverrides[field] {
		return
	}
	switch field {
	case "AuthHeaderVal":
		c.fileConfig.AuthHeaderVal = c.AuthHeaderVal
	}
}

func (c *Config) save() error {
	persisted := c.configForSave()
	var persist any = persisted
	data, err := json.MarshalIndent(persist, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	if err := cliutil.AtomicWritePrivateFile(c.Path, data, 0o600, 0o700); err != nil {
		return err
	}
	c.fileConfig = &persisted
	c.fileConfig.envOverrides = nil
	c.fileConfig.fileConfig = nil
	// persisted shares its map fields with c (configForSave shallow-copies *c),
	// so isolate the stored fileConfig the same way snapshotFileConfig does;
	// otherwise later mutations to c's maps leak into the on-disk snapshot.
	c.fileConfig.Headers = cloneStringMap(c.fileConfig.Headers)
	return nil
}

// Ensure strings import is used
var _ = strings.ReplaceAll
