// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCompanyCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "company",
		Short:       "Company research and fundamentals",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCompanyFinancialsCmd(flags))
	cmd.AddCommand(newCompanyFundFlowCmd(flags))
	cmd.AddCommand(newCompanyKnowledgeBaseCmd(flags))
	cmd.AddCommand(newCompanyMarketShareCmd(flags))
	cmd.AddCommand(newCompanyOperationalMetricsCmd(flags))
	cmd.AddCommand(newCompanyOverviewCmd(flags))
	cmd.AddCommand(newCompanyRevenueMixCmd(flags))
	cmd.AddCommand(newCompanySearchCmd(flags))
	cmd.AddCommand(newCompanyShareholdingCmd(flags))
	return cmd
}
