// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPortfolioCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "portfolio",
		Short:       "Authenticated read-only portfolio views",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPortfolioCompanySummaryCmd(flags))
	cmd.AddCommand(newPortfolioFamilyCompanySummaryCmd(flags))
	cmd.AddCommand(newPortfolioFamilyGainersLosersCmd(flags))
	cmd.AddCommand(newPortfolioFamilySummaryCmd(flags))
	cmd.AddCommand(newPortfolioGainersLosersCmd(flags))
	cmd.AddCommand(newPortfolioSummaryCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelPortfolioQualityCmd(flags))
	return cmd
}
