// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"tijori-finance-pp-cli/internal/client"
	"tijori-finance-pp-cli/internal/cliutil"
	"tijori-finance-pp-cli/internal/config"
	"tijori-finance-pp-cli/internal/platform"
)

type rootFlags struct {
	asJSON                  bool
	compact                 bool
	csv                     bool
	plain                   bool
	quiet                   bool
	dryRun                  bool
	noInput                 bool
	yes                     bool
	agent                   bool
	selectFields            string
	configPath              string
	homePath                string
	runProfileName          string
	clientProfileName       string
	platformSession         *platform.Session
	platformResolver        platform.CredentialResolver
	platformResolverReady   bool
	platformAnalytics       *platform.AnalyticsDeclaration
	platformGateError       error
	platformMetadataWriter  io.Writer
	receiptEnabled          bool
	receiptFile             string
	auditDir                string
	receiptWriter           *platform.ReceiptWriter
	platformMetadataEmitted bool
	deliverSpec             string
	timeout                 time.Duration
	timeoutExplicit         bool
	rateLimit               float64
	dataSource              string
	agentSource             string
	freshnessMeta           any

	// deliverBuf captures command output when --deliver is set to a
	// non-stdout sink. Flushed to the sink after Execute returns.
	deliverBuf  *bytes.Buffer
	deliverSink DeliverSink
}

// novelCommandHooks are optional hooks for hand-authored command extensions.
// A markerless file in package cli may register one from init without editing
// this generated root, so force regeneration preserves both the source and
// wiring. Hooks run after generated novel parent groups are attached so a
// hook can Find a novel parent and add children. Registration is additive:
// independent extensions never replace one another, except that a real
// command replaces a TODO scaffold with the same name.
var novelCommandHooks []func(root *cobra.Command, flags *rootFlags)

func registerNovelCommand(hook func(root *cobra.Command, flags *rootFlags)) {
	novelCommandHooks = append(novelCommandHooks, hook)
}

const novelScaffoldAnnotation = "pp:novel-scaffold"

func isNovelScaffoldCommand(cmd *cobra.Command) bool {
	return cmd != nil && cmd.Annotations[novelScaffoldAnnotation] == "true"
}

func addNovelCommandIfAbsent(parent *cobra.Command, candidate *cobra.Command) {
	if parent == nil || candidate == nil {
		return
	}
	for _, existing := range parent.Commands() {
		if existing.Name() != candidate.Name() {
			continue
		}
		if isNovelScaffoldCommand(existing) && !isNovelScaffoldCommand(candidate) {
			parent.RemoveCommand(existing)
			parent.AddCommand(candidate)
		}
		return
	}
	parent.AddCommand(candidate)
}

func preferImplementedNovelCommands(cmd *cobra.Command) {
	if cmd == nil {
		return
	}
	byName := map[string][]*cobra.Command{}
	for _, child := range cmd.Commands() {
		byName[child.Name()] = append(byName[child.Name()], child)
	}
	for _, group := range byName {
		var keep *cobra.Command
		for _, child := range group {
			if !isNovelScaffoldCommand(child) {
				keep = child
				break
			}
		}
		if keep == nil {
			continue
		}
		for _, child := range group {
			if child != keep && isNovelScaffoldCommand(child) {
				cmd.RemoveCommand(child)
			}
		}
	}
	for _, child := range cmd.Commands() {
		preferImplementedNovelCommands(child)
	}
}

// clientHooks let preserved package-local extensions configure a newly-created
// client without editing generated code. Hooks are additive and run once per
// client construction; they must not perform provider-specific behavior here.
var clientHooks []func(*client.Client) error

func registerClientHook(hook func(*client.Client) error) {
	clientHooks = append(clientHooks, hook)
}

// Keeps preserved post-construction setup consistent across interactive CLI
// and MCP clients.
func ApplyClientHooks(c *client.Client) error {
	for _, hook := range clientHooks {
		if err := hook(c); err != nil {
			return err
		}
	}
	return nil
}

// RootCmd returns the Cobra command tree without executing it. The MCP server
// uses this to mirror every user-facing command as an agent tool.
func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
// The named return feeds the deferred journal write: one site after
// ExecuteC returns covers every outcome, including RunE errors (a
// Cobra PostRun hook would be skipped on RunE error, so none is used).
func Execute() (retErr error) {
	var flags rootFlags
	rootCmd := newRootCmd(&flags)
	defer finalizePlatformInvocation(&flags, &retErr)

	err := rootCmd.Execute()
	if errors.Is(err, pflag.ErrHelp) {
		return nil
	}
	if err != nil && strings.Contains(err.Error(), "unknown flag") {
		msg := err.Error()
		// Extract the flag name from the error message (e.g., "unknown flag: --foob")
		if idx := strings.Index(msg, "unknown flag: "); idx >= 0 {
			flagStr := strings.TrimSpace(msg[idx+len("unknown flag: "):])
			if suggestion := suggestFlag(flagStr, rootCmd); suggestion != "" {
				// Cobra already printed `Error: unknown flag: --foob` before
				// returning; the wrap below attaches the hint to err.Error()
				// for downstream consumers and exit-code classification, but
				// would never reach stderr now that main.go no longer prints
				// err. Emit the hint explicitly so the suggestion still
				// shows up under Cobra's error line.
				fmt.Fprintf(os.Stderr, "hint: did you mean --%s?\n", suggestion)
				err = fmt.Errorf("%w\nhint: did you mean --%s?", err, suggestion)
			}
		}
	}
	if err == nil && flags.deliverBuf != nil {
		if derr := Deliver(flags.deliverSink, flags.deliverBuf.Bytes(), flags.compact); derr != nil {
			fmt.Fprintf(os.Stderr, "warning: deliver to %s:%s failed: %v\n", flags.deliverSink.Scheme, flags.deliverSink.Target, derr)
			return derr
		}
	}
	if err != nil && isCobraUsageError(err) {
		// Cobra/pflag pre-RunE errors (unknown flag, unknown command,
		// missing required, etc.) never flow through usageErr() because
		// they originate inside rootCmd.Execute() before any user RunE
		// runs. Without this wrap, ExitCode() falls through to the
		// default and emits 1 — clobbering the conventional code-2 for
		// usage errors that the helpers.go contract already promises.
		return usageErr(err)
	}
	return err
}

// isCobraUsageError reports whether err matches one of Cobra/pflag's
// pre-RunE usage-error shapes. Detection is by message prefix to match
// the same approach the unknown-flag hint path uses above; neither
// Cobra nor pflag exports typed sentinels for these.
//
// Patterns are anchored to the literal punctuation Cobra and pflag
// emit so an application's own RunE error that happens to contain the
// substring "required flag" or "invalid argument" doesn't get
// misclassified as a usage error.
//
// Patterns covered (Cobra v1.x + pflag v1.x as of 2026-05):
//   - "unknown flag: --foo"                            (pflag)
//   - "unknown shorthand flag: 'x' in -x"              (pflag)
//   - "unknown command \"foo\" for ..."                (Cobra)
//   - "required flag \"foo\" not set"                  (Cobra, single missing)
//   - "required flag(s) \"foo\" not set"               (Cobra, multiple missing)
//   - "flag needs an argument: --foo"                  (pflag, missing value)
//   - "invalid argument \"x\" for \"--y\" flag: ..."   (pflag, parse failure)
//
// Cobra emits the singular form ("required flag") when exactly one
// MarkFlagRequired flag is missing, and the plural form ("required
// flag(s)") only when multiple are missing on the same command. Both
// shapes must be anchored to avoid matching app-level errors that
// happen to mention "required flag" as prose; the trailing space + quote
// (`required flag "`) is the literal punctuation cobra emits.
//
// Returns false for nil err.
func isCobraUsageError(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	return strings.HasPrefix(msg, "unknown flag") ||
		strings.HasPrefix(msg, "unknown shorthand flag") ||
		strings.HasPrefix(msg, "unknown command") ||
		strings.HasPrefix(msg, `required flag "`) ||
		strings.HasPrefix(msg, `required flag(s) "`) ||
		strings.HasPrefix(msg, "flag needs an argument:") ||
		strings.HasPrefix(msg, `invalid argument "`)
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "tijori-finance-pp-cli",
		Short: `Tijori Finance CLI — A source-linked terminal research notebook for Indian equities.`,
		Long: `Tijori Finance CLI — A source-linked terminal research notebook for Indian equities.

Highlights (not in the official API docs):
  • research peers   Compare live peer financial, ownership, and operating evidence in one unit-aware matrix.
  • research review-queue   Join current holdings or watchlist names with upcoming results, events, reports, and alerts.
  • research changes   Emit deterministic row-level changes between two server-returned financial periods.
  • research ownership-check   Align same-period ownership movements with financial and cash-flow changes.
  • research result-pack   Connect a result or event to report, concall, and validated source-document metadata.
  • screener run   Return the exact native query, matched fields, result page, and request provenance (use --explain).
  • research context   Bundle dated company, sector, macro, and raw-material observations without a synthetic verdict.
  • portfolio quality   Join live portfolio weights with public company quality evidence and explicit unavailable states.
  • feed inspect   Resolve timeline items to normalized event, report, and document metadata while preserving cursors.
  • auth capabilities   Report public, authenticated, empty, blocked, expired, or changed-shape status per safe GET endpoint.
  • research input-context   Place current raw-material observations beside live operational and revenue-mix data.

Agent mode: add --agent to any command for JSON output + non-interactive mode.
Health check: run 'tijori-finance-pp-cli doctor' to verify connectivity.
See README.md or the bundled SKILL.md for recipes.`,
		SilenceUsage: true,
		Version:      version,
	}
	rootCmd.SetVersionTemplate("tijori-finance-pp-cli {{ .Version }}\n")

	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.compact, "compact", false, "Return only key fields (id, name, status, timestamps) for minimal token usage")
	rootCmd.PersistentFlags().BoolVar(&flags.csv, "csv", false, "Output as CSV (table and array responses)")
	rootCmd.PersistentFlags().BoolVar(&flags.plain, "plain", false, "Output as plain tab-separated text")
	rootCmd.PersistentFlags().BoolVar(&flags.quiet, "quiet", false, "Bare output, one value per line")
	rootCmd.PersistentFlags().StringVar(&flags.configPath, "config", "", "Config file path")
	rootCmd.PersistentFlags().StringVar(&flags.homePath, "home", "", "Root directory for config, data, state, and cache files")
	rootCmd.PersistentFlags().DurationVar(&flags.timeout, "timeout", 60*time.Second, "Request timeout")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Show request without sending")
	rootCmd.PersistentFlags().BoolVar(&flags.receiptEnabled, "receipt", false, "Write an atomic private run receipt")
	rootCmd.PersistentFlags().StringVar(&flags.receiptFile, "receipt-file", "", "Override the run receipt destination")
	rootCmd.PersistentFlags().StringVar(&flags.auditDir, "audit-dir", "", "Aggregate the receipt and index under this audit directory")
	rootCmd.PersistentFlags().BoolVar(&flags.noInput, "no-input", false, "Disable all interactive prompts (for CI/agents)")
	rootCmd.PersistentFlags().StringVar(&flags.selectFields, "select", "", "Comma-separated fields to include in output")
	rootCmd.PersistentFlags().BoolVar(&flags.yes, "yes", false, "Skip confirmation prompts (explicit confirmation for scripts)")
	rootCmd.PersistentFlags().BoolVar(&noColor, "no-color", false, "Disable colored output")
	rootCmd.PersistentFlags().BoolVar(&humanFriendly, "human-friendly", false, "Enable colored output and rich formatting")
	rootCmd.PersistentFlags().BoolVar(&flags.agent, "agent", false, "Set agent-friendly output defaults (--json --compact --no-input --no-color)")
	rootCmd.PersistentFlags().StringVar(&flags.dataSource, "data-source", "live", "Data source for read commands (live API only; local persistence is disabled)")
	rootCmd.PersistentFlags().StringVar(&flags.runProfileName, "profile", "", "Apply values from a saved run profile; this does not select a client (see 'tijori-finance-pp-cli profile list')")
	rootCmd.PersistentFlags().StringVar(&flags.clientProfileName, "client-profile", "", "Select the tenant-gated client profile (env: PRINTING_PRESS_CLIENT_PROFILE)")
	if strings.TrimSpace(os.Getenv(mcpBoundProfileEnv)) != "" {
		if flag := rootCmd.PersistentFlags().Lookup("client-profile"); flag != nil {
			flag.Hidden = true
		}
	}
	rootCmd.PersistentFlags().StringVar(&flags.deliverSpec, "deliver", "", "Route output to a sink: stdout (default), file:<path>, webhook:<url>")
	rootCmd.PersistentFlags().Float64Var(&flags.rateLimit, "rate-limit", client.RateLimitAuto, "Max requests per second (0 to disable; default auto — pace to server rate-limit headers)")
	if f := rootCmd.PersistentFlags().Lookup("rate-limit"); f != nil {
		f.DefValue = "auto"
	}

	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		var appliedProfile *Profile
		if err := enforceMCPBoundProfile(cmd, flags); err != nil {
			return err
		}
		if _, err := cliutil.SetHomeOverride(flags.homePath); err != nil {
			return err
		}
		if flags.deliverSpec != "" {
			sink, err := ParseDeliverSink(flags.deliverSpec)
			if err != nil {
				return err
			}
			if sink.Scheme != "stdout" && sink.Scheme != "" {
				return fmt.Errorf("--deliver %q is disabled: this CLI does not persist domain data or POST results", sink.Scheme)
			}
			flags.deliverSink = sink
			if sink.Scheme != "stdout" && sink.Scheme != "" {
				flags.deliverBuf = &bytes.Buffer{}
				cmd.SetOut(io.MultiWriter(os.Stdout, flags.deliverBuf))
			}
		}
		if flags.runProfileName != "" {
			profile, err := GetProfile(flags.runProfileName)
			if err != nil {
				return err
			}
			if profile == nil {
				available := ListProfileNames()
				if len(available) == 0 {
					return fmt.Errorf("run profile %q not found (no profiles saved yet; run '%s profile save <name> --<flag> <value>')", flags.runProfileName, cmd.Root().Name())
				}
				return fmt.Errorf("run profile %q not found; available: %s", flags.runProfileName, strings.Join(available, ", "))
			}
			if err := ApplyProfileToFlags(cmd, profile); err != nil {
				return err
			}
			appliedProfile = profile
		}
		if platformCommandNeedsGate(cmd) {
			if err := preparePlatformSession(flags); err != nil {
				return err
			}
			cmd.SetContext(platform.ContextWithSession(cmd.Context(), flags.platformSession))
			if err := validatePlatformLegacyInputs(cmd, flags); err != nil {
				return err
			}
			if err := initializePlatformReceipt(cmd, flags); err != nil {
				return err
			}
			if err := adoptPlatformCommandWindow(cmd, flags); err != nil {
				return err
			}
			flags.platformMetadataWriter = cmd.ErrOrStderr()
			if err := verifyPlatformSession(cmd.Context(), flags); err != nil {
				if platformCommandIsDoctor(cmd) {
					flags.platformGateError = err
				} else {
					return err
				}
			}
		}
		if flags.agent {
			if !cmd.Flags().Changed("json") {
				flags.asJSON = true
			}
			if !cmd.Flags().Changed("compact") {
				flags.compact = true
			}
			if !cmd.Flags().Changed("no-input") {
				flags.noInput = true
			}
			if !cmd.Flags().Changed("no-color") {
				noColor = true
			}
		}
		switch flags.dataSource {
		case "live":
			// live-only by contract; no domain-data persistence or local fallback
		case "auto", "local":
			return fmt.Errorf("--data-source %q is disabled: this CLI fetches domain data live and never uses a local store", flags.dataSource)
		default:
			return fmt.Errorf("invalid --data-source value %q: must be live", flags.dataSource)
		}
		flags.timeoutExplicit = timeoutExplicitFrom(cmd, appliedProfile)
		flags.agentSource = declaredAgentSource(cmd, flags)
		return nil
	}
	rootCmd.AddCommand(newCompanyCmd(flags))
	rootCmd.AddCommand(newFeedCmd(flags))
	rootCmd.AddCommand(newMarketCmd(flags))
	rootCmd.AddCommand(newPortfolioCmd(flags))
	rootCmd.AddCommand(newReportsCmd(flags))
	rootCmd.AddCommand(newScreenerCmd(flags))
	rootCmd.AddCommand(newDoctorCmd(flags))
	if registeredPlatformSource != nil {
		attachPlatformClientCommands(rootCmd, flags)
	}
	// The CLI is intentionally read-only and live-only. Do not attach the
	// generated local state, sync, search, tail, analytics, export, feedback,
	// or archive/workflow commands.
	rootCmd.AddCommand(newProfileCmd(flags))
	rootCmd.AddCommand(newWhichCmd(flags))
	rootCmd.AddCommand(newAPICmd(flags))
	rootCmd.AddCommand(newAlertsPromotedCmd(flags))
	rootCmd.AddCommand(newIdeasPromotedCmd(flags))
	rootCmd.AddCommand(newMacroPromotedCmd(flags))
	rootCmd.AddCommand(newRawMaterialsPromotedCmd(flags))
	rootCmd.AddCommand(newWatchlistPromotedCmd(flags))
	rootCmd.AddCommand(newVersionCmd())
	rootCmd.AddCommand(newAgentContextCmd(rootCmd))
	addNovelCommandIfAbsent(rootCmd, newNovelAuthCmd(flags))
	addNovelCommandIfAbsent(rootCmd, newNovelResearchCmd(flags))
	for _, hook := range novelCommandHooks {
		hook(rootCmd, flags)
	}
	preferImplementedNovelCommands(rootCmd)
	// Attach the conditional platform identity command last so ordinary,
	// promoted, and novel API-owned `whoami` commands all win the name.
	if registeredPlatformSource != nil {
		attachPlatformWhoamiCommand(rootCmd, flags)
	}

	return rootCmd
}

// ApplyProfileToFlags overlays values without setting Flag.Changed, so a
// profile-supplied timeout must count here or binary transfers would drop
// the whole-call bound.
func timeoutExplicitFrom(cmd *cobra.Command, profile *Profile) bool {
	if cmd != nil && cmd.Flags().Changed("timeout") {
		return true
	}
	if profile != nil {
		if _, ok := profile.Values["timeout"]; ok {
			return true
		}
	}
	return false
}

func ExitCode(err error) int {
	var codeErr *cliError
	if As(err, &codeErr) {
		return codeErr.code
	}
	return 1
}

func (f *rootFlags) newClient() (*client.Client, error) {
	cfg, err := config.Load(f.configPath)
	if err != nil {
		return nil, configErr(err)
	}
	return f.newClientFromConfig(cfg)
}

// newClients resolves configuration and secure-store material once, then
// constructs independent clients. This avoids concurrent or repeated macOS
// Keychain reads in compound commands while keeping per-client HTTP state
// isolated for safe parallel requests.
func (f *rootFlags) newClients(count int) ([]*client.Client, error) {
	if count < 1 {
		return nil, nil
	}
	cfg, err := config.Load(f.configPath)
	if err != nil {
		return nil, configErr(err)
	}
	clients := make([]*client.Client, count)
	for i := range clients {
		clients[i], err = f.newClientFromConfig(cfg)
		if err != nil {
			return nil, err
		}
	}
	return clients, nil
}

func (f *rootFlags) newClientFromConfig(cfg *config.Config) (*client.Client, error) {
	c := client.New(cfg, f.timeout, f.rateLimit)
	if f.timeoutExplicit {
		c.SetTimeoutExplicit(true)
	}
	c.DryRun = f.dryRun
	// Domain responses are intentionally live-only. Keep the legacy flag for
	// compatibility, but never enable the generated response cache.
	c.NoCache = true
	if err := bindPlatformClient(c, f); err != nil {
		return nil, err
	}
	if err := ApplyClientHooks(c); err != nil {
		return nil, err
	}
	return c, nil
}

func (f *rootFlags) printJSON(w *cobra.Command, v any) error {
	return printJSONFiltered(w.OutOrStdout(), v, f)
}

func (f *rootFlags) printTable(w *cobra.Command, headers []string, rows [][]string) error {
	if f.asJSON {
		return fmt.Errorf("use printJSON for JSON output")
	}
	tw := tabwriter.NewWriter(w.OutOrStdout(), 2, 4, 2, ' ', 0)
	header := ""
	for i, h := range headers {
		if i > 0 {
			header += "\t"
		}
		header += h
	}
	fmt.Fprintln(tw, header)
	for _, row := range rows {
		line := ""
		for i, cell := range row {
			if i > 0 {
				line += "\t"
			}
			line += cell
		}
		fmt.Fprintln(tw, line)
	}
	return tw.Flush()
}
