// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newScreenerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "screener",
		Short:       "Native Tijori screener DSL and field catalog",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newScreenerAdvancedSearchCmd(flags))
	cmd.AddCommand(newScreenerFieldsCmd(flags))
	cmd.AddCommand(newScreenerPopularCmd(flags))
	cmd.AddCommand(newScreenerPopularResultsCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelScreenerRunCmd(flags))
	return cmd
}
