// Copyright 2026 abhirup and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newEnginesCreateEnginesCmd(flags *rootFlags) *cobra.Command {
	var bodyAdditionalDockerCommands string
	var bodyAdditionalDockerCommandsFlag string
	var bodyAllowInterruptableInference string
	var bodyBatchConfigBatchMode string
	var bodyBatchConfigMaxBatchSize int
	var bodyBuildNumber int
	var bodyCreatedDate string
	var bodyDeployedBuildNumber int
	var bodyEnableChainedModels string
	var bodyEngineId string
	var bodyEngineName string
	var bodyEnginePlatformKey string
	var bodyEnginePlatformName string
	var bodyEntityType string
	var bodyFiles string
	var bodyGpuMemoryRequirement int
	var bodyId string
	var bodyInferenceTimeStatsCount int
	var bodyInferenceTimeStatsMax string
	var bodyInferenceTimeStatsMean string
	var bodyInferenceTimeStatsMin string
	var bodyInferenceTimeStatsSum int
	var bodyInferenceTimeStatsSumSq int
	var bodyInferenceTimeStatsVariance string
	var bodyLastBuildResultsStatus string
	var bodyMaximumRunTime string
	var bodyMemoryRequirement int
	var bodyModifiedDate string
	var bodyOwnerSubscriptionType string
	var bodyPackageDefinitionFileName string
	var bodyParentRepositoryId string
	var bodyPermissions string
	var bodyPlatformInfoAllowAdditionalDockerCommands string
	var bodyPlatformInfoClusterId string
	var bodyPlatformInfoComputeCostPerSecond float64
	var bodyPlatformInfoContainerBasedPlatform string
	var bodyPlatformInfoDescription string
	var bodyPlatformInfoFriendlyName string
	var bodyPlatformInfoMaxAllowedGPUMemory int
	var bodyPlatformInfoMaxAllowedMemory int
	var bodyPlatformInfoMaxAllowedStorage int
	var bodyPlatformInfoMinAllowedGPUMemory int
	var bodyPlatformInfoMinAllowedMemory int
	var bodyPlatformInfoMinAllowedStorage int
	var bodyPlatformInfoPerGBGPUMemoryPricing float64
	var bodyPlatformInfoPerGBMemoryPricing int
	var bodyPlatformInfoPerGBStoragePricing float64
	var bodyPlatformInfoPlatformKey string
	var bodyPlatformInfoRecommendedBaseImages string
	var bodyRunOnDedicatedInstance string
	var bodySelectedBaseImage string
	var bodyStateInfoHistoricalNodeCountStatsV2118092026 string
	var bodyStateInfoNumRunningInstances int
	var bodyStateInfoRunningNodes string
	var bodyStatus string
	var bodyStorageRequirement int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-engines",
		Short:       "POST /api/engines",
		Annotations: map[string]string{"pp:endpoint": "engines.create_engines", "pp:method": "POST", "pp:path": "/api/engines", "pp:requires-input": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("additional-docker-commands") && bodyAdditionalDockerCommands == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "additional-docker-commands")
				}
				if !cmd.Flags().Changed("additional-docker-commands-flag") && bodyAdditionalDockerCommandsFlag == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "additional-docker-commands-flag")
				}
				if !cmd.Flags().Changed("allow-interruptable-inference") && bodyAllowInterruptableInference == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "allow-interruptable-inference")
				}
				if !cmd.Flags().Changed("batch-config-batch-mode") && bodyBatchConfigBatchMode == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "batch-config-batch-mode")
				}
				if !cmd.Flags().Changed("batch-config-max-batch-size") && bodyBatchConfigMaxBatchSize == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "batch-config-max-batch-size")
				}
				if !cmd.Flags().Changed("build-number") && bodyBuildNumber == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "build-number")
				}
				if !cmd.Flags().Changed("created-date") && bodyCreatedDate == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-date")
				}
				if !cmd.Flags().Changed("deployed-build-number") && bodyDeployedBuildNumber == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "deployed-build-number")
				}
				if !cmd.Flags().Changed("enable-chained-models") && bodyEnableChainedModels == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "enable-chained-models")
				}
				if !cmd.Flags().Changed("engine-id") && bodyEngineId == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "engine-id")
				}
				if !cmd.Flags().Changed("engine-name") && bodyEngineName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "engine-name")
				}
				if !cmd.Flags().Changed("engine-platform-key") && bodyEnginePlatformKey == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "engine-platform-key")
				}
				if !cmd.Flags().Changed("engine-platform-name") && bodyEnginePlatformName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "engine-platform-name")
				}
				if !cmd.Flags().Changed("entity-type") && bodyEntityType == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "entity-type")
				}
				if !cmd.Flags().Changed("files") && bodyFiles == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "files")
				}
				if !cmd.Flags().Changed("gpu-memory-requirement") && bodyGpuMemoryRequirement == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "gpu-memory-requirement")
				}
				if !cmd.Flags().Changed("id") && bodyId == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "id")
				}
				if !cmd.Flags().Changed("inference-time-stats-count") && bodyInferenceTimeStatsCount == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "inference-time-stats-count")
				}
				if !cmd.Flags().Changed("inference-time-stats-max") && bodyInferenceTimeStatsMax == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "inference-time-stats-max")
				}
				if !cmd.Flags().Changed("inference-time-stats-mean") && bodyInferenceTimeStatsMean == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "inference-time-stats-mean")
				}
				if !cmd.Flags().Changed("inference-time-stats-min") && bodyInferenceTimeStatsMin == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "inference-time-stats-min")
				}
				if !cmd.Flags().Changed("inference-time-stats-sum") && bodyInferenceTimeStatsSum == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "inference-time-stats-sum")
				}
				if !cmd.Flags().Changed("inference-time-stats-sum-sq") && bodyInferenceTimeStatsSumSq == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "inference-time-stats-sum-sq")
				}
				if !cmd.Flags().Changed("inference-time-stats-variance") && bodyInferenceTimeStatsVariance == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "inference-time-stats-variance")
				}
				if !cmd.Flags().Changed("last-build-results-status") && bodyLastBuildResultsStatus == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "last-build-results-status")
				}
				if !cmd.Flags().Changed("maximum-run-time") && bodyMaximumRunTime == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "maximum-run-time")
				}
				if !cmd.Flags().Changed("memory-requirement") && bodyMemoryRequirement == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "memory-requirement")
				}
				if !cmd.Flags().Changed("modified-date") && bodyModifiedDate == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "modified-date")
				}
				if !cmd.Flags().Changed("owner-subscription-type") && bodyOwnerSubscriptionType == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "owner-subscription-type")
				}
				if !cmd.Flags().Changed("package-definition-file-name") && bodyPackageDefinitionFileName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "package-definition-file-name")
				}
				if !cmd.Flags().Changed("parent-repository-id") && bodyParentRepositoryId == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "parent-repository-id")
				}
				if !cmd.Flags().Changed("permissions") && bodyPermissions == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "permissions")
				}
				if !cmd.Flags().Changed("platform-info-allow-additional-docker-commands") && bodyPlatformInfoAllowAdditionalDockerCommands == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-allow-additional-docker-commands")
				}
				if !cmd.Flags().Changed("platform-info-cluster-id") && bodyPlatformInfoClusterId == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-cluster-id")
				}
				if !cmd.Flags().Changed("platform-info-compute-cost-per-second") && bodyPlatformInfoComputeCostPerSecond == 0.0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-compute-cost-per-second")
				}
				if !cmd.Flags().Changed("platform-info-container-based-platform") && bodyPlatformInfoContainerBasedPlatform == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-container-based-platform")
				}
				if !cmd.Flags().Changed("platform-info-description") && bodyPlatformInfoDescription == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-description")
				}
				if !cmd.Flags().Changed("platform-info-friendly-name") && bodyPlatformInfoFriendlyName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-friendly-name")
				}
				if !cmd.Flags().Changed("platform-info-max-allowed-gpu-memory") && bodyPlatformInfoMaxAllowedGPUMemory == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-max-allowed-gpu-memory")
				}
				if !cmd.Flags().Changed("platform-info-max-allowed-memory") && bodyPlatformInfoMaxAllowedMemory == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-max-allowed-memory")
				}
				if !cmd.Flags().Changed("platform-info-max-allowed-storage") && bodyPlatformInfoMaxAllowedStorage == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-max-allowed-storage")
				}
				if !cmd.Flags().Changed("platform-info-min-allowed-gpu-memory") && bodyPlatformInfoMinAllowedGPUMemory == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-min-allowed-gpu-memory")
				}
				if !cmd.Flags().Changed("platform-info-min-allowed-memory") && bodyPlatformInfoMinAllowedMemory == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-min-allowed-memory")
				}
				if !cmd.Flags().Changed("platform-info-min-allowed-storage") && bodyPlatformInfoMinAllowedStorage == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-min-allowed-storage")
				}
				if !cmd.Flags().Changed("platform-info-per-gbgpu-memory-pricing") && bodyPlatformInfoPerGBGPUMemoryPricing == 0.0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-per-gbgpu-memory-pricing")
				}
				if !cmd.Flags().Changed("platform-info-per-gb-memory-pricing") && bodyPlatformInfoPerGBMemoryPricing == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-per-gb-memory-pricing")
				}
				if !cmd.Flags().Changed("platform-info-per-gb-storage-pricing") && bodyPlatformInfoPerGBStoragePricing == 0.0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-per-gb-storage-pricing")
				}
				if !cmd.Flags().Changed("platform-info-platform-key") && bodyPlatformInfoPlatformKey == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-platform-key")
				}
				if !cmd.Flags().Changed("platform-info-recommended-base-images") && bodyPlatformInfoRecommendedBaseImages == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "platform-info-recommended-base-images")
				}
				if !cmd.Flags().Changed("run-on-dedicated-instance") && bodyRunOnDedicatedInstance == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "run-on-dedicated-instance")
				}
				if !cmd.Flags().Changed("selected-base-image") && bodySelectedBaseImage == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "selected-base-image")
				}
				if !cmd.Flags().Changed("state-info-historical-node-count-stats-2118092026") && bodyStateInfoHistoricalNodeCountStatsV2118092026 == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "state-info-historical-node-count-stats-2118092026")
				}
				if !cmd.Flags().Changed("state-info-num-running-instances") && bodyStateInfoNumRunningInstances == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "state-info-num-running-instances")
				}
				if !cmd.Flags().Changed("state-info-running-nodes") && bodyStateInfoRunningNodes == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "state-info-running-nodes")
				}
				if !cmd.Flags().Changed("status") && bodyStatus == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status")
				}
				if !cmd.Flags().Changed("storage-requirement") && bodyStorageRequirement == 0 && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "storage-requirement")
				}
			}
			path := "/api/engines"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("additional-docker-commands") || bodyAdditionalDockerCommands != "" {
					bodyMap["additionalDockerCommands"] = bodyAdditionalDockerCommands
				}
				if cmd.Flags().Changed("additional-docker-commands-flag") || bodyAdditionalDockerCommandsFlag != "" {
					parsedAdditionalDockerCommandsFlag, err := strconv.ParseBool(bodyAdditionalDockerCommandsFlag)
					if err != nil {
						return fmt.Errorf("parsing --additional-docker-commands-flag as bool: %w", err)
					}
					bodyMap["additionalDockerCommandsFlag"] = parsedAdditionalDockerCommandsFlag
				}
				if cmd.Flags().Changed("allow-interruptable-inference") || bodyAllowInterruptableInference != "" {
					parsedAllowInterruptableInference, err := strconv.ParseBool(bodyAllowInterruptableInference)
					if err != nil {
						return fmt.Errorf("parsing --allow-interruptable-inference as bool: %w", err)
					}
					bodyMap["allowInterruptableInference"] = parsedAllowInterruptableInference
				}
				{
					nestedBatchConfig := map[string]any{}
					if cmd.Flags().Changed("batch-config-batch-mode") || bodyBatchConfigBatchMode != "" {
						nestedBatchConfig["batchMode"] = bodyBatchConfigBatchMode
					}
					if cmd.Flags().Changed("batch-config-max-batch-size") || bodyBatchConfigMaxBatchSize != 0 {
						nestedBatchConfig["maxBatchSize"] = bodyBatchConfigMaxBatchSize
					}
					if len(nestedBatchConfig) > 0 {
						bodyMap["batchConfig"] = nestedBatchConfig
					}
				}
				if cmd.Flags().Changed("build-number") || bodyBuildNumber != 0 {
					bodyMap["buildNumber"] = bodyBuildNumber
				}
				if cmd.Flags().Changed("created-date") || bodyCreatedDate != "" {
					bodyMap["createdDate"] = bodyCreatedDate
				}
				if cmd.Flags().Changed("deployed-build-number") || bodyDeployedBuildNumber != 0 {
					bodyMap["deployedBuildNumber"] = bodyDeployedBuildNumber
				}
				if cmd.Flags().Changed("enable-chained-models") || bodyEnableChainedModels != "" {
					parsedEnableChainedModels, err := strconv.ParseBool(bodyEnableChainedModels)
					if err != nil {
						return fmt.Errorf("parsing --enable-chained-models as bool: %w", err)
					}
					bodyMap["enableChainedModels"] = parsedEnableChainedModels
				}
				if cmd.Flags().Changed("engine-id") || bodyEngineId != "" {
					bodyMap["engineId"] = bodyEngineId
				}
				if cmd.Flags().Changed("engine-name") || bodyEngineName != "" {
					bodyMap["engineName"] = bodyEngineName
				}
				if cmd.Flags().Changed("engine-platform-key") || bodyEnginePlatformKey != "" {
					bodyMap["enginePlatformKey"] = bodyEnginePlatformKey
				}
				if cmd.Flags().Changed("engine-platform-name") || bodyEnginePlatformName != "" {
					bodyMap["enginePlatformName"] = bodyEnginePlatformName
				}
				if cmd.Flags().Changed("entity-type") || bodyEntityType != "" {
					bodyMap["entityType"] = bodyEntityType
				}
				if cmd.Flags().Changed("files") || bodyFiles != "" {
					var parsedFiles any
					if err := json.Unmarshal([]byte(bodyFiles), &parsedFiles); err != nil {
						return fmt.Errorf("parsing --files JSON: %w", err)
					}
					asArray, ok := parsedFiles.([]any)
					if !ok {
						return fmt.Errorf("--files must be a JSON array, got JSON %T", parsedFiles)
					}
					bodyMap["files"] = asArray
				}
				if cmd.Flags().Changed("gpu-memory-requirement") || bodyGpuMemoryRequirement != 0 {
					bodyMap["gpuMemoryRequirement"] = bodyGpuMemoryRequirement
				}
				if cmd.Flags().Changed("id") || bodyId != "" {
					bodyMap["id"] = bodyId
				}
				{
					nestedInferenceTimeStats := map[string]any{}
					if cmd.Flags().Changed("inference-time-stats-count") || bodyInferenceTimeStatsCount != 0 {
						nestedInferenceTimeStats["count"] = bodyInferenceTimeStatsCount
					}
					if cmd.Flags().Changed("inference-time-stats-max") || bodyInferenceTimeStatsMax != "" {
						nestedInferenceTimeStats["max"] = bodyInferenceTimeStatsMax
					}
					if cmd.Flags().Changed("inference-time-stats-mean") || bodyInferenceTimeStatsMean != "" {
						nestedInferenceTimeStats["mean"] = bodyInferenceTimeStatsMean
					}
					if cmd.Flags().Changed("inference-time-stats-min") || bodyInferenceTimeStatsMin != "" {
						nestedInferenceTimeStats["min"] = bodyInferenceTimeStatsMin
					}
					if cmd.Flags().Changed("inference-time-stats-sum") || bodyInferenceTimeStatsSum != 0 {
						nestedInferenceTimeStats["sum"] = bodyInferenceTimeStatsSum
					}
					if cmd.Flags().Changed("inference-time-stats-sum-sq") || bodyInferenceTimeStatsSumSq != 0 {
						nestedInferenceTimeStats["sumSq"] = bodyInferenceTimeStatsSumSq
					}
					if cmd.Flags().Changed("inference-time-stats-variance") || bodyInferenceTimeStatsVariance != "" {
						nestedInferenceTimeStats["variance"] = bodyInferenceTimeStatsVariance
					}
					if len(nestedInferenceTimeStats) > 0 {
						bodyMap["inferenceTimeStats"] = nestedInferenceTimeStats
					}
				}
				{
					nestedLastBuildResults := map[string]any{}
					if cmd.Flags().Changed("last-build-results-status") || bodyLastBuildResultsStatus != "" {
						nestedLastBuildResults["status"] = bodyLastBuildResultsStatus
					}
					if len(nestedLastBuildResults) > 0 {
						bodyMap["lastBuildResults"] = nestedLastBuildResults
					}
				}
				if cmd.Flags().Changed("maximum-run-time") || bodyMaximumRunTime != "" {
					bodyMap["maximumRunTime"] = bodyMaximumRunTime
				}
				if cmd.Flags().Changed("memory-requirement") || bodyMemoryRequirement != 0 {
					bodyMap["memoryRequirement"] = bodyMemoryRequirement
				}
				if cmd.Flags().Changed("modified-date") || bodyModifiedDate != "" {
					bodyMap["modifiedDate"] = bodyModifiedDate
				}
				if cmd.Flags().Changed("owner-subscription-type") || bodyOwnerSubscriptionType != "" {
					bodyMap["ownerSubscriptionType"] = bodyOwnerSubscriptionType
				}
				if cmd.Flags().Changed("package-definition-file-name") || bodyPackageDefinitionFileName != "" {
					bodyMap["packageDefinitionFileName"] = bodyPackageDefinitionFileName
				}
				if cmd.Flags().Changed("parent-repository-id") || bodyParentRepositoryId != "" {
					bodyMap["parentRepositoryId"] = bodyParentRepositoryId
				}
				if cmd.Flags().Changed("permissions") || bodyPermissions != "" {
					var parsedPermissions any
					if err := json.Unmarshal([]byte(bodyPermissions), &parsedPermissions); err != nil {
						return fmt.Errorf("parsing --permissions JSON: %w", err)
					}
					asArray, ok := parsedPermissions.([]any)
					if !ok {
						return fmt.Errorf("--permissions must be a JSON array, got JSON %T", parsedPermissions)
					}
					bodyMap["permissions"] = asArray
				}
				{
					nestedPlatformInfo := map[string]any{}
					if cmd.Flags().Changed("platform-info-allow-additional-docker-commands") || bodyPlatformInfoAllowAdditionalDockerCommands != "" {
						parsedPlatformInfoAllowAdditionalDockerCommands, err := strconv.ParseBool(bodyPlatformInfoAllowAdditionalDockerCommands)
						if err != nil {
							return fmt.Errorf("parsing --platform-info-allow-additional-docker-commands as bool: %w", err)
						}
						nestedPlatformInfo["allowAdditionalDockerCommands"] = parsedPlatformInfoAllowAdditionalDockerCommands
					}
					if cmd.Flags().Changed("platform-info-cluster-id") || bodyPlatformInfoClusterId != "" {
						nestedPlatformInfo["clusterId"] = bodyPlatformInfoClusterId
					}
					if cmd.Flags().Changed("platform-info-compute-cost-per-second") || bodyPlatformInfoComputeCostPerSecond != 0.0 {
						nestedPlatformInfo["computeCostPerSecond"] = bodyPlatformInfoComputeCostPerSecond
					}
					if cmd.Flags().Changed("platform-info-container-based-platform") || bodyPlatformInfoContainerBasedPlatform != "" {
						parsedPlatformInfoContainerBasedPlatform, err := strconv.ParseBool(bodyPlatformInfoContainerBasedPlatform)
						if err != nil {
							return fmt.Errorf("parsing --platform-info-container-based-platform as bool: %w", err)
						}
						nestedPlatformInfo["containerBasedPlatform"] = parsedPlatformInfoContainerBasedPlatform
					}
					if cmd.Flags().Changed("platform-info-description") || bodyPlatformInfoDescription != "" {
						nestedPlatformInfo["description"] = bodyPlatformInfoDescription
					}
					if cmd.Flags().Changed("platform-info-friendly-name") || bodyPlatformInfoFriendlyName != "" {
						nestedPlatformInfo["friendlyName"] = bodyPlatformInfoFriendlyName
					}
					if cmd.Flags().Changed("platform-info-max-allowed-gpu-memory") || bodyPlatformInfoMaxAllowedGPUMemory != 0 {
						nestedPlatformInfo["maxAllowedGPUMemory"] = bodyPlatformInfoMaxAllowedGPUMemory
					}
					if cmd.Flags().Changed("platform-info-max-allowed-memory") || bodyPlatformInfoMaxAllowedMemory != 0 {
						nestedPlatformInfo["maxAllowedMemory"] = bodyPlatformInfoMaxAllowedMemory
					}
					if cmd.Flags().Changed("platform-info-max-allowed-storage") || bodyPlatformInfoMaxAllowedStorage != 0 {
						nestedPlatformInfo["maxAllowedStorage"] = bodyPlatformInfoMaxAllowedStorage
					}
					if cmd.Flags().Changed("platform-info-min-allowed-gpu-memory") || bodyPlatformInfoMinAllowedGPUMemory != 0 {
						nestedPlatformInfo["minAllowedGPUMemory"] = bodyPlatformInfoMinAllowedGPUMemory
					}
					if cmd.Flags().Changed("platform-info-min-allowed-memory") || bodyPlatformInfoMinAllowedMemory != 0 {
						nestedPlatformInfo["minAllowedMemory"] = bodyPlatformInfoMinAllowedMemory
					}
					if cmd.Flags().Changed("platform-info-min-allowed-storage") || bodyPlatformInfoMinAllowedStorage != 0 {
						nestedPlatformInfo["minAllowedStorage"] = bodyPlatformInfoMinAllowedStorage
					}
					if cmd.Flags().Changed("platform-info-per-gbgpu-memory-pricing") || bodyPlatformInfoPerGBGPUMemoryPricing != 0.0 {
						nestedPlatformInfo["perGBGPUMemoryPricing"] = bodyPlatformInfoPerGBGPUMemoryPricing
					}
					if cmd.Flags().Changed("platform-info-per-gb-memory-pricing") || bodyPlatformInfoPerGBMemoryPricing != 0 {
						nestedPlatformInfo["perGBMemoryPricing"] = bodyPlatformInfoPerGBMemoryPricing
					}
					if cmd.Flags().Changed("platform-info-per-gb-storage-pricing") || bodyPlatformInfoPerGBStoragePricing != 0.0 {
						nestedPlatformInfo["perGBStoragePricing"] = bodyPlatformInfoPerGBStoragePricing
					}
					if cmd.Flags().Changed("platform-info-platform-key") || bodyPlatformInfoPlatformKey != "" {
						nestedPlatformInfo["platformKey"] = bodyPlatformInfoPlatformKey
					}
					if cmd.Flags().Changed("platform-info-recommended-base-images") || bodyPlatformInfoRecommendedBaseImages != "" {
						var parsedPlatformInfoRecommendedBaseImages any
						if err := json.Unmarshal([]byte(bodyPlatformInfoRecommendedBaseImages), &parsedPlatformInfoRecommendedBaseImages); err != nil {
							return fmt.Errorf("parsing --platform-info-recommended-base-images JSON: %w", err)
						}
						asArray, ok := parsedPlatformInfoRecommendedBaseImages.([]any)
						if !ok {
							return fmt.Errorf("--platform-info-recommended-base-images must be a JSON array, got JSON %T", parsedPlatformInfoRecommendedBaseImages)
						}
						nestedPlatformInfo["recommendedBaseImages"] = asArray
					}
					if len(nestedPlatformInfo) > 0 {
						bodyMap["platformInfo"] = nestedPlatformInfo
					}
				}
				if cmd.Flags().Changed("run-on-dedicated-instance") || bodyRunOnDedicatedInstance != "" {
					parsedRunOnDedicatedInstance, err := strconv.ParseBool(bodyRunOnDedicatedInstance)
					if err != nil {
						return fmt.Errorf("parsing --run-on-dedicated-instance as bool: %w", err)
					}
					bodyMap["runOnDedicatedInstance"] = parsedRunOnDedicatedInstance
				}
				if cmd.Flags().Changed("selected-base-image") || bodySelectedBaseImage != "" {
					bodyMap["selectedBaseImage"] = bodySelectedBaseImage
				}
				{
					nestedStateInfo := map[string]any{}
					{
						nestedStateInfoHistoricalNodeCountStats := map[string]any{}
						if cmd.Flags().Changed("state-info-historical-node-count-stats-2118092026") || bodyStateInfoHistoricalNodeCountStatsV2118092026 != "" {
							var parsedStateInfoHistoricalNodeCountStatsV2118092026 any
							if err := json.Unmarshal([]byte(bodyStateInfoHistoricalNodeCountStatsV2118092026), &parsedStateInfoHistoricalNodeCountStatsV2118092026); err != nil {
								return fmt.Errorf("parsing --state-info-historical-node-count-stats-2118092026 JSON: %w", err)
							}
							asMap, ok := parsedStateInfoHistoricalNodeCountStatsV2118092026.(map[string]any)
							if !ok {
								return fmt.Errorf("--state-info-historical-node-count-stats-2118092026 must be a JSON object, got JSON %T", parsedStateInfoHistoricalNodeCountStatsV2118092026)
							}
							nestedStateInfoHistoricalNodeCountStats["2118092026"] = asMap
						}
						if len(nestedStateInfoHistoricalNodeCountStats) > 0 {
							nestedStateInfo["historicalNodeCountStats"] = nestedStateInfoHistoricalNodeCountStats
						}
					}
					if cmd.Flags().Changed("state-info-num-running-instances") || bodyStateInfoNumRunningInstances != 0 {
						nestedStateInfo["numRunningInstances"] = bodyStateInfoNumRunningInstances
					}
					if cmd.Flags().Changed("state-info-running-nodes") || bodyStateInfoRunningNodes != "" {
						var parsedStateInfoRunningNodes any
						if err := json.Unmarshal([]byte(bodyStateInfoRunningNodes), &parsedStateInfoRunningNodes); err != nil {
							return fmt.Errorf("parsing --state-info-running-nodes JSON: %w", err)
						}
						asArray, ok := parsedStateInfoRunningNodes.([]any)
						if !ok {
							return fmt.Errorf("--state-info-running-nodes must be a JSON array, got JSON %T", parsedStateInfoRunningNodes)
						}
						nestedStateInfo["runningNodes"] = asArray
					}
					if len(nestedStateInfo) > 0 {
						bodyMap["stateInfo"] = nestedStateInfo
					}
				}
				if cmd.Flags().Changed("status") || bodyStatus != "" {
					bodyMap["status"] = bodyStatus
				}
				if cmd.Flags().Changed("storage-requirement") || bodyStorageRequirement != 0 {
					bodyMap["storageRequirement"] = bodyStorageRequirement
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "engines", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "engines", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "engines", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "engines", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "engines", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "engines",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Mutation-riding reads (POST search, RPC-over-POST lists) return
				// the same single-key collection envelopes as GET reads. Unwrap
				// before filtering so rows nest once under the result key and
				// --select filters rows, not envelope keys; plain created-object
				// responses pass through unwrapSingleKeyArray untouched.
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				var selectErr error
				filtered := unwrapSingleKeyArray(data)
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "engines", partialFailure.Message))
				}
				return selectErr
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlagsMeta renders the body with live
			// provenance, then the typed partial-failure exit fires unless
			// --allow-partial-failure downgrades it. Without this guard a
			// partial failure would exit 0 for these output modes — the exact
			// silent-swallow regression the surrounding patch is preventing
			// for asJSON / piped output.
			printErr := printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"}, nil)
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "engines", partialFailure.Message))
			}
			return printErr
		},
	}
	cmd.Flags().StringVar(&bodyAdditionalDockerCommands, "additional-docker-commands", "", "")
	cmd.Flags().StringVar(&bodyAdditionalDockerCommandsFlag, "additional-docker-commands-flag", "", "")
	cmd.Flags().StringVar(&bodyAllowInterruptableInference, "allow-interruptable-inference", "", "")
	cmd.Flags().StringVar(&bodyBatchConfigBatchMode, "batch-config-batch-mode", "", "")
	cmd.Flags().IntVar(&bodyBatchConfigMaxBatchSize, "batch-config-max-batch-size", 0, "")
	cmd.Flags().IntVar(&bodyBuildNumber, "build-number", 0, "")
	cmd.Flags().StringVar(&bodyCreatedDate, "created-date", "", "")
	cmd.Flags().IntVar(&bodyDeployedBuildNumber, "deployed-build-number", 0, "")
	cmd.Flags().StringVar(&bodyEnableChainedModels, "enable-chained-models", "", "")
	cmd.Flags().StringVar(&bodyEngineId, "engine-id", "", "")
	cmd.Flags().StringVar(&bodyEngineName, "engine-name", "", "")
	cmd.Flags().StringVar(&bodyEnginePlatformKey, "engine-platform-key", "", "")
	cmd.Flags().StringVar(&bodyEnginePlatformName, "engine-platform-name", "", "")
	cmd.Flags().StringVar(&bodyEntityType, "entity-type", "", "")
	cmd.Flags().StringVar(&bodyFiles, "files", "", "")
	cmd.Flags().IntVar(&bodyGpuMemoryRequirement, "gpu-memory-requirement", 0, "")
	cmd.Flags().StringVar(&bodyId, "id", "", "")
	cmd.Flags().IntVar(&bodyInferenceTimeStatsCount, "inference-time-stats-count", 0, "")
	cmd.Flags().StringVar(&bodyInferenceTimeStatsMax, "inference-time-stats-max", "", "")
	cmd.Flags().StringVar(&bodyInferenceTimeStatsMean, "inference-time-stats-mean", "", "")
	cmd.Flags().StringVar(&bodyInferenceTimeStatsMin, "inference-time-stats-min", "", "")
	cmd.Flags().IntVar(&bodyInferenceTimeStatsSum, "inference-time-stats-sum", 0, "")
	cmd.Flags().IntVar(&bodyInferenceTimeStatsSumSq, "inference-time-stats-sum-sq", 0, "")
	cmd.Flags().StringVar(&bodyInferenceTimeStatsVariance, "inference-time-stats-variance", "", "")
	cmd.Flags().StringVar(&bodyLastBuildResultsStatus, "last-build-results-status", "", "")
	cmd.Flags().StringVar(&bodyMaximumRunTime, "maximum-run-time", "", "")
	cmd.Flags().IntVar(&bodyMemoryRequirement, "memory-requirement", 0, "")
	cmd.Flags().StringVar(&bodyModifiedDate, "modified-date", "", "")
	cmd.Flags().StringVar(&bodyOwnerSubscriptionType, "owner-subscription-type", "", "")
	cmd.Flags().StringVar(&bodyPackageDefinitionFileName, "package-definition-file-name", "", "")
	cmd.Flags().StringVar(&bodyParentRepositoryId, "parent-repository-id", "", "")
	cmd.Flags().StringVar(&bodyPermissions, "permissions", "", "")
	cmd.Flags().StringVar(&bodyPlatformInfoAllowAdditionalDockerCommands, "platform-info-allow-additional-docker-commands", "", "")
	cmd.Flags().StringVar(&bodyPlatformInfoClusterId, "platform-info-cluster-id", "", "")
	cmd.Flags().Float64Var(&bodyPlatformInfoComputeCostPerSecond, "platform-info-compute-cost-per-second", 0.0, "")
	cmd.Flags().StringVar(&bodyPlatformInfoContainerBasedPlatform, "platform-info-container-based-platform", "", "")
	cmd.Flags().StringVar(&bodyPlatformInfoDescription, "platform-info-description", "", "")
	cmd.Flags().StringVar(&bodyPlatformInfoFriendlyName, "platform-info-friendly-name", "", "")
	cmd.Flags().IntVar(&bodyPlatformInfoMaxAllowedGPUMemory, "platform-info-max-allowed-gpu-memory", 0, "")
	cmd.Flags().IntVar(&bodyPlatformInfoMaxAllowedMemory, "platform-info-max-allowed-memory", 0, "")
	cmd.Flags().IntVar(&bodyPlatformInfoMaxAllowedStorage, "platform-info-max-allowed-storage", 0, "")
	cmd.Flags().IntVar(&bodyPlatformInfoMinAllowedGPUMemory, "platform-info-min-allowed-gpu-memory", 0, "")
	cmd.Flags().IntVar(&bodyPlatformInfoMinAllowedMemory, "platform-info-min-allowed-memory", 0, "")
	cmd.Flags().IntVar(&bodyPlatformInfoMinAllowedStorage, "platform-info-min-allowed-storage", 0, "")
	cmd.Flags().Float64Var(&bodyPlatformInfoPerGBGPUMemoryPricing, "platform-info-per-gbgpu-memory-pricing", 0.0, "")
	cmd.Flags().IntVar(&bodyPlatformInfoPerGBMemoryPricing, "platform-info-per-gb-memory-pricing", 0, "")
	cmd.Flags().Float64Var(&bodyPlatformInfoPerGBStoragePricing, "platform-info-per-gb-storage-pricing", 0.0, "")
	cmd.Flags().StringVar(&bodyPlatformInfoPlatformKey, "platform-info-platform-key", "", "")
	cmd.Flags().StringVar(&bodyPlatformInfoRecommendedBaseImages, "platform-info-recommended-base-images", "", "")
	cmd.Flags().StringVar(&bodyRunOnDedicatedInstance, "run-on-dedicated-instance", "", "")
	cmd.Flags().StringVar(&bodySelectedBaseImage, "selected-base-image", "", "")
	cmd.Flags().StringVar(&bodyStateInfoHistoricalNodeCountStatsV2118092026, "state-info-historical-node-count-stats-2118092026", "", "")
	cmd.Flags().IntVar(&bodyStateInfoNumRunningInstances, "state-info-num-running-instances", 0, "")
	cmd.Flags().StringVar(&bodyStateInfoRunningNodes, "state-info-running-nodes", "", "")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "")
	cmd.Flags().IntVar(&bodyStorageRequirement, "storage-requirement", 0, "")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
