// Copyright 2026 abhirup and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newModelsCreateModelsCmd(flags *rootFlags) *cobra.Command {
	var bodyActive bool
	var bodyAiEngineConfigInferenceOptions string
	var bodyAiEngineConfigInputs string
	var bodyAiEngineConfigOutcomes string
	var bodyAiEngineConfigPredictEngineType string
	var bodyAllowPublicComponentAccess bool
	var bodyAppEngineId string
	var bodyAuthor string
	var bodyComputeType string
	var bodyEngineCostPerSecond int
	var bodyEngineStatus string
	var bodyEntityType string
	var bodyId string
	var bodyInterfaceDisplayOptions string
	var bodyInterfaceType string
	var bodyIsPublic bool
	var bodyLongRunningInference bool
	var bodyModelAlias string
	var bodyModelDataFilePathsMODELDESCRIPTION string
	var bodyModelDescription string
	var bodyModelId string
	var bodyModelLongDescription string
	var bodyModelName string
	var bodyModelType string
	var bodyNeedsContext bool
	var bodyOwnerSubscriptionType string
	var bodyParentRepositoryId string
	var bodyPerformanceScore int
	var bodyPerformanceStatsAccuracy int
	var bodyPerformanceStatsAuc int
	var bodyPerformanceStatsBleuScore int
	var bodyPerformanceStatsDunnIndex int
	var bodyPerformanceStatsF1Score int
	var bodyPerformanceStatsMetrics string
	var bodyPerformanceStatsPrecision int
	var bodyPerformanceStatsR2 int
	var bodyPerformanceStatsRecall int
	var bodyPermissions string
	var bodyPricingInfoEnableMonetization string
	var bodyPricingInfoModelOwnerPaysComputeCost string
	var bodyPricingInfoNoChargeOnInferenceWithError string
	var bodyPricingInfoServicePricingInfo string
	var bodyPricingInfoSkipUsageChargeInSameCtx string
	var bodySupportedInterfaces string
	var bodySupportingLinks string
	var bodyTags string
	var bodyTotalCost int
	var bodyTotalInferences int
	var bodyTotalViews int
	var bodyVariableDisplayOptions string
	var bodyVisibility string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-models",
		Short:       "POST /api/models",
		Annotations: map[string]string{"pp:endpoint": "models.create_models", "pp:method": "POST", "pp:path": "/api/models", "pp:requires-input": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("ai-engine-config-inference-options") && bodyAiEngineConfigInferenceOptions == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "ai-engine-config-inference-options")
				}
				if !cmd.Flags().Changed("ai-engine-config-inputs") && bodyAiEngineConfigInputs == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "ai-engine-config-inputs")
				}
				if !cmd.Flags().Changed("ai-engine-config-outcomes") && bodyAiEngineConfigOutcomes == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "ai-engine-config-outcomes")
				}
				if !cmd.Flags().Changed("ai-engine-config-predict-engine-type") && bodyAiEngineConfigPredictEngineType == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "ai-engine-config-predict-engine-type")
				}
				if !cmd.Flags().Changed("app-engine-id") && bodyAppEngineId == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "app-engine-id")
				}
				if cmd.Flags().Changed("model-data-file-paths-modeldescription") || bodyModelDataFilePathsMODELDESCRIPTION != "" {
					if !cmd.Flags().Changed("model-data-file-paths-modeldescription") && bodyModelDataFilePathsMODELDESCRIPTION == "" && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "model-data-file-paths-modeldescription")
					}
				}
				if !cmd.Flags().Changed("model-name") && bodyModelName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "model-name")
				}
				if !cmd.Flags().Changed("parent-repository-id") && bodyParentRepositoryId == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "parent-repository-id")
				}
				if (cmd.Flags().Changed("performance-stats-accuracy") || bodyPerformanceStatsAccuracy != 0) || (cmd.Flags().Changed("performance-stats-auc") || bodyPerformanceStatsAuc != 0) || (cmd.Flags().Changed("performance-stats-bleu-score") || bodyPerformanceStatsBleuScore != 0) || (cmd.Flags().Changed("performance-stats-dunn-index") || bodyPerformanceStatsDunnIndex != 0) || (cmd.Flags().Changed("performance-stats-f1-score") || bodyPerformanceStatsF1Score != 0) || (cmd.Flags().Changed("performance-stats-metrics") || bodyPerformanceStatsMetrics != "") || (cmd.Flags().Changed("performance-stats-precision") || bodyPerformanceStatsPrecision != 0) || (cmd.Flags().Changed("performance-stats-r2") || bodyPerformanceStatsR2 != 0) || (cmd.Flags().Changed("performance-stats-recall") || bodyPerformanceStatsRecall != 0) {
					if !cmd.Flags().Changed("performance-stats-accuracy") && bodyPerformanceStatsAccuracy == 0 && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-accuracy")
					}
					if !cmd.Flags().Changed("performance-stats-auc") && bodyPerformanceStatsAuc == 0 && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-auc")
					}
					if !cmd.Flags().Changed("performance-stats-bleu-score") && bodyPerformanceStatsBleuScore == 0 && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-bleu-score")
					}
					if !cmd.Flags().Changed("performance-stats-dunn-index") && bodyPerformanceStatsDunnIndex == 0 && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-dunn-index")
					}
					if !cmd.Flags().Changed("performance-stats-f1-score") && bodyPerformanceStatsF1Score == 0 && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-f1-score")
					}
					if !cmd.Flags().Changed("performance-stats-metrics") && bodyPerformanceStatsMetrics == "" && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-metrics")
					}
					if !cmd.Flags().Changed("performance-stats-precision") && bodyPerformanceStatsPrecision == 0 && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-precision")
					}
					if !cmd.Flags().Changed("performance-stats-r2") && bodyPerformanceStatsR2 == 0 && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-r2")
					}
					if !cmd.Flags().Changed("performance-stats-recall") && bodyPerformanceStatsRecall == 0 && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "performance-stats-recall")
					}
				}
				if !cmd.Flags().Changed("pricing-info-enable-monetization") && bodyPricingInfoEnableMonetization == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "pricing-info-enable-monetization")
				}
				if !cmd.Flags().Changed("pricing-info-model-owner-pays-compute-cost") && bodyPricingInfoModelOwnerPaysComputeCost == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "pricing-info-model-owner-pays-compute-cost")
				}
				if !cmd.Flags().Changed("pricing-info-no-charge-on-inference-with-error") && bodyPricingInfoNoChargeOnInferenceWithError == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "pricing-info-no-charge-on-inference-with-error")
				}
				if !cmd.Flags().Changed("pricing-info-service-pricing-info") && bodyPricingInfoServicePricingInfo == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "pricing-info-service-pricing-info")
				}
				if !cmd.Flags().Changed("pricing-info-skip-usage-charge-in-same-ctx") && bodyPricingInfoSkipUsageChargeInSameCtx == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "pricing-info-skip-usage-charge-in-same-ctx")
				}
				if !cmd.Flags().Changed("supported-interfaces") && bodySupportedInterfaces == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "supported-interfaces")
				}
			}
			path := "/api/models"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("active") {
					bodyMap["active"] = bodyActive
				}
				{
					nestedAiEngineConfig := map[string]any{}
					if cmd.Flags().Changed("ai-engine-config-inference-options") || bodyAiEngineConfigInferenceOptions != "" {
						var parsedAiEngineConfigInferenceOptions any
						if err := json.Unmarshal([]byte(bodyAiEngineConfigInferenceOptions), &parsedAiEngineConfigInferenceOptions); err != nil {
							return fmt.Errorf("parsing --ai-engine-config-inference-options JSON: %w", err)
						}
						asMap, ok := parsedAiEngineConfigInferenceOptions.(map[string]any)
						if !ok {
							return fmt.Errorf("--ai-engine-config-inference-options must be a JSON object, got JSON %T", parsedAiEngineConfigInferenceOptions)
						}
						nestedAiEngineConfig["inferenceOptions"] = asMap
					}
					if cmd.Flags().Changed("ai-engine-config-inputs") || bodyAiEngineConfigInputs != "" {
						var parsedAiEngineConfigInputs any
						if err := json.Unmarshal([]byte(bodyAiEngineConfigInputs), &parsedAiEngineConfigInputs); err != nil {
							return fmt.Errorf("parsing --ai-engine-config-inputs JSON: %w", err)
						}
						asArray, ok := parsedAiEngineConfigInputs.([]any)
						if !ok {
							return fmt.Errorf("--ai-engine-config-inputs must be a JSON array, got JSON %T", parsedAiEngineConfigInputs)
						}
						nestedAiEngineConfig["inputs"] = asArray
					}
					if cmd.Flags().Changed("ai-engine-config-outcomes") || bodyAiEngineConfigOutcomes != "" {
						var parsedAiEngineConfigOutcomes any
						if err := json.Unmarshal([]byte(bodyAiEngineConfigOutcomes), &parsedAiEngineConfigOutcomes); err != nil {
							return fmt.Errorf("parsing --ai-engine-config-outcomes JSON: %w", err)
						}
						asArray, ok := parsedAiEngineConfigOutcomes.([]any)
						if !ok {
							return fmt.Errorf("--ai-engine-config-outcomes must be a JSON array, got JSON %T", parsedAiEngineConfigOutcomes)
						}
						nestedAiEngineConfig["outcomes"] = asArray
					}
					if cmd.Flags().Changed("ai-engine-config-predict-engine-type") || bodyAiEngineConfigPredictEngineType != "" {
						nestedAiEngineConfig["predictEngineType"] = bodyAiEngineConfigPredictEngineType
					}
					if len(nestedAiEngineConfig) > 0 {
						bodyMap["aiEngineConfig"] = nestedAiEngineConfig
					}
				}
				if cmd.Flags().Changed("allow-public-component-access") {
					bodyMap["allowPublicComponentAccess"] = bodyAllowPublicComponentAccess
				}
				if cmd.Flags().Changed("app-engine-id") || bodyAppEngineId != "" {
					bodyMap["appEngineId"] = bodyAppEngineId
				}
				if cmd.Flags().Changed("author") || bodyAuthor != "" {
					bodyMap["author"] = bodyAuthor
				}
				if cmd.Flags().Changed("compute-type") || bodyComputeType != "" {
					bodyMap["computeType"] = bodyComputeType
				}
				if cmd.Flags().Changed("engine-cost-per-second") || bodyEngineCostPerSecond != 0 {
					bodyMap["engineCostPerSecond"] = bodyEngineCostPerSecond
				}
				if cmd.Flags().Changed("engine-status") || bodyEngineStatus != "" {
					bodyMap["engineStatus"] = bodyEngineStatus
				}
				if cmd.Flags().Changed("entity-type") || bodyEntityType != "" {
					bodyMap["entityType"] = bodyEntityType
				}
				if cmd.Flags().Changed("id") || bodyId != "" {
					bodyMap["id"] = bodyId
				}
				if cmd.Flags().Changed("interface-display-options") || bodyInterfaceDisplayOptions != "" {
					var parsedInterfaceDisplayOptions any
					if err := json.Unmarshal([]byte(bodyInterfaceDisplayOptions), &parsedInterfaceDisplayOptions); err != nil {
						return fmt.Errorf("parsing --interface-display-options JSON: %w", err)
					}
					asMap, ok := parsedInterfaceDisplayOptions.(map[string]any)
					if !ok {
						return fmt.Errorf("--interface-display-options must be a JSON object, got JSON %T", parsedInterfaceDisplayOptions)
					}
					bodyMap["interfaceDisplayOptions"] = asMap
				}
				if cmd.Flags().Changed("interface-type") || bodyInterfaceType != "" {
					bodyMap["interfaceType"] = bodyInterfaceType
				}
				if cmd.Flags().Changed("is-public") {
					bodyMap["isPublic"] = bodyIsPublic
				}
				if cmd.Flags().Changed("long-running-inference") {
					bodyMap["longRunningInference"] = bodyLongRunningInference
				}
				if cmd.Flags().Changed("model-alias") || bodyModelAlias != "" {
					bodyMap["modelAlias"] = bodyModelAlias
				}
				{
					nestedModelData := map[string]any{}
					{
						nestedModelDataFilePaths := map[string]any{}
						if cmd.Flags().Changed("model-data-file-paths-modeldescription") || bodyModelDataFilePathsMODELDESCRIPTION != "" {
							nestedModelDataFilePaths["MODELDESCRIPTION"] = bodyModelDataFilePathsMODELDESCRIPTION
						}
						if len(nestedModelDataFilePaths) > 0 {
							nestedModelData["filePaths"] = nestedModelDataFilePaths
						}
					}
					if len(nestedModelData) > 0 {
						bodyMap["modelData"] = nestedModelData
					}
				}
				if cmd.Flags().Changed("model-description") || bodyModelDescription != "" {
					bodyMap["modelDescription"] = bodyModelDescription
				}
				if cmd.Flags().Changed("model-id") || bodyModelId != "" {
					bodyMap["modelId"] = bodyModelId
				}
				if cmd.Flags().Changed("model-long-description") || bodyModelLongDescription != "" {
					bodyMap["modelLongDescription"] = bodyModelLongDescription
				}
				if cmd.Flags().Changed("model-name") || bodyModelName != "" {
					bodyMap["modelName"] = bodyModelName
				}
				if cmd.Flags().Changed("model-type") || bodyModelType != "" {
					bodyMap["modelType"] = bodyModelType
				}
				if cmd.Flags().Changed("needs-context") {
					bodyMap["needsContext"] = bodyNeedsContext
				}
				if cmd.Flags().Changed("owner-subscription-type") || bodyOwnerSubscriptionType != "" {
					bodyMap["ownerSubscriptionType"] = bodyOwnerSubscriptionType
				}
				if cmd.Flags().Changed("parent-repository-id") || bodyParentRepositoryId != "" {
					bodyMap["parentRepositoryId"] = bodyParentRepositoryId
				}
				if cmd.Flags().Changed("performance-score") || bodyPerformanceScore != 0 {
					bodyMap["performanceScore"] = bodyPerformanceScore
				}
				{
					nestedPerformanceStats := map[string]any{}
					if cmd.Flags().Changed("performance-stats-accuracy") || bodyPerformanceStatsAccuracy != 0 {
						nestedPerformanceStats["accuracy"] = bodyPerformanceStatsAccuracy
					}
					if cmd.Flags().Changed("performance-stats-auc") || bodyPerformanceStatsAuc != 0 {
						nestedPerformanceStats["auc"] = bodyPerformanceStatsAuc
					}
					if cmd.Flags().Changed("performance-stats-bleu-score") || bodyPerformanceStatsBleuScore != 0 {
						nestedPerformanceStats["bleuScore"] = bodyPerformanceStatsBleuScore
					}
					if cmd.Flags().Changed("performance-stats-dunn-index") || bodyPerformanceStatsDunnIndex != 0 {
						nestedPerformanceStats["dunnIndex"] = bodyPerformanceStatsDunnIndex
					}
					if cmd.Flags().Changed("performance-stats-f1-score") || bodyPerformanceStatsF1Score != 0 {
						nestedPerformanceStats["f1Score"] = bodyPerformanceStatsF1Score
					}
					if cmd.Flags().Changed("performance-stats-metrics") || bodyPerformanceStatsMetrics != "" {
						var parsedPerformanceStatsMetrics any
						if err := json.Unmarshal([]byte(bodyPerformanceStatsMetrics), &parsedPerformanceStatsMetrics); err != nil {
							return fmt.Errorf("parsing --performance-stats-metrics JSON: %w", err)
						}
						asMap, ok := parsedPerformanceStatsMetrics.(map[string]any)
						if !ok {
							return fmt.Errorf("--performance-stats-metrics must be a JSON object, got JSON %T", parsedPerformanceStatsMetrics)
						}
						nestedPerformanceStats["metrics"] = asMap
					}
					if cmd.Flags().Changed("performance-stats-precision") || bodyPerformanceStatsPrecision != 0 {
						nestedPerformanceStats["precision"] = bodyPerformanceStatsPrecision
					}
					if cmd.Flags().Changed("performance-stats-r2") || bodyPerformanceStatsR2 != 0 {
						nestedPerformanceStats["r2"] = bodyPerformanceStatsR2
					}
					if cmd.Flags().Changed("performance-stats-recall") || bodyPerformanceStatsRecall != 0 {
						nestedPerformanceStats["recall"] = bodyPerformanceStatsRecall
					}
					if len(nestedPerformanceStats) > 0 {
						bodyMap["performanceStats"] = nestedPerformanceStats
					}
				}
				if cmd.Flags().Changed("permissions") || bodyPermissions != "" {
					var parsedPermissions any
					if err := json.Unmarshal([]byte(bodyPermissions), &parsedPermissions); err != nil {
						return fmt.Errorf("parsing --permissions JSON: %w", err)
					}
					asArray, ok := parsedPermissions.([]any)
					if !ok {
						return fmt.Errorf("--permissions must be a JSON array, got JSON %T", parsedPermissions)
					}
					bodyMap["permissions"] = asArray
				}
				{
					nestedPricingInfo := map[string]any{}
					if cmd.Flags().Changed("pricing-info-enable-monetization") || bodyPricingInfoEnableMonetization != "" {
						parsedPricingInfoEnableMonetization, err := strconv.ParseBool(bodyPricingInfoEnableMonetization)
						if err != nil {
							return fmt.Errorf("parsing --pricing-info-enable-monetization as bool: %w", err)
						}
						nestedPricingInfo["enableMonetization"] = parsedPricingInfoEnableMonetization
					}
					if cmd.Flags().Changed("pricing-info-model-owner-pays-compute-cost") || bodyPricingInfoModelOwnerPaysComputeCost != "" {
						parsedPricingInfoModelOwnerPaysComputeCost, err := strconv.ParseBool(bodyPricingInfoModelOwnerPaysComputeCost)
						if err != nil {
							return fmt.Errorf("parsing --pricing-info-model-owner-pays-compute-cost as bool: %w", err)
						}
						nestedPricingInfo["modelOwnerPaysComputeCost"] = parsedPricingInfoModelOwnerPaysComputeCost
					}
					if cmd.Flags().Changed("pricing-info-no-charge-on-inference-with-error") || bodyPricingInfoNoChargeOnInferenceWithError != "" {
						parsedPricingInfoNoChargeOnInferenceWithError, err := strconv.ParseBool(bodyPricingInfoNoChargeOnInferenceWithError)
						if err != nil {
							return fmt.Errorf("parsing --pricing-info-no-charge-on-inference-with-error as bool: %w", err)
						}
						nestedPricingInfo["noChargeOnInferenceWithError"] = parsedPricingInfoNoChargeOnInferenceWithError
					}
					if cmd.Flags().Changed("pricing-info-service-pricing-info") || bodyPricingInfoServicePricingInfo != "" {
						nestedPricingInfo["servicePricingInfo"] = bodyPricingInfoServicePricingInfo
					}
					if cmd.Flags().Changed("pricing-info-skip-usage-charge-in-same-ctx") || bodyPricingInfoSkipUsageChargeInSameCtx != "" {
						parsedPricingInfoSkipUsageChargeInSameCtx, err := strconv.ParseBool(bodyPricingInfoSkipUsageChargeInSameCtx)
						if err != nil {
							return fmt.Errorf("parsing --pricing-info-skip-usage-charge-in-same-ctx as bool: %w", err)
						}
						nestedPricingInfo["skipUsageChargeInSameCtx"] = parsedPricingInfoSkipUsageChargeInSameCtx
					}
					if len(nestedPricingInfo) > 0 {
						bodyMap["pricingInfo"] = nestedPricingInfo
					}
				}
				if cmd.Flags().Changed("supported-interfaces") || bodySupportedInterfaces != "" {
					var parsedSupportedInterfaces any
					if err := json.Unmarshal([]byte(bodySupportedInterfaces), &parsedSupportedInterfaces); err != nil {
						return fmt.Errorf("parsing --supported-interfaces JSON: %w", err)
					}
					asArray, ok := parsedSupportedInterfaces.([]any)
					if !ok {
						return fmt.Errorf("--supported-interfaces must be a JSON array, got JSON %T", parsedSupportedInterfaces)
					}
					bodyMap["supportedInterfaces"] = asArray
				}
				if cmd.Flags().Changed("supporting-links") || bodySupportingLinks != "" {
					var parsedSupportingLinks any
					if err := json.Unmarshal([]byte(bodySupportingLinks), &parsedSupportingLinks); err != nil {
						return fmt.Errorf("parsing --supporting-links JSON: %w", err)
					}
					asArray, ok := parsedSupportingLinks.([]any)
					if !ok {
						return fmt.Errorf("--supporting-links must be a JSON array, got JSON %T", parsedSupportingLinks)
					}
					bodyMap["supportingLinks"] = asArray
				}
				if cmd.Flags().Changed("tags") || bodyTags != "" {
					var parsedTags any
					if err := json.Unmarshal([]byte(bodyTags), &parsedTags); err != nil {
						return fmt.Errorf("parsing --tags JSON: %w", err)
					}
					asArray, ok := parsedTags.([]any)
					if !ok {
						return fmt.Errorf("--tags must be a JSON array, got JSON %T", parsedTags)
					}
					bodyMap["tags"] = asArray
				}
				if cmd.Flags().Changed("total-cost") || bodyTotalCost != 0 {
					bodyMap["totalCost"] = bodyTotalCost
				}
				if cmd.Flags().Changed("total-inferences") || bodyTotalInferences != 0 {
					bodyMap["totalInferences"] = bodyTotalInferences
				}
				if cmd.Flags().Changed("total-views") || bodyTotalViews != 0 {
					bodyMap["totalViews"] = bodyTotalViews
				}
				if cmd.Flags().Changed("variable-display-options") || bodyVariableDisplayOptions != "" {
					var parsedVariableDisplayOptions any
					if err := json.Unmarshal([]byte(bodyVariableDisplayOptions), &parsedVariableDisplayOptions); err != nil {
						return fmt.Errorf("parsing --variable-display-options JSON: %w", err)
					}
					asMap, ok := parsedVariableDisplayOptions.(map[string]any)
					if !ok {
						return fmt.Errorf("--variable-display-options must be a JSON object, got JSON %T", parsedVariableDisplayOptions)
					}
					bodyMap["variableDisplayOptions"] = asMap
				}
				if cmd.Flags().Changed("visibility") || bodyVisibility != "" {
					bodyMap["visibility"] = bodyVisibility
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "models", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "models", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "models", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "models", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "models", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "models",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Mutation-riding reads (POST search, RPC-over-POST lists) return
				// the same single-key collection envelopes as GET reads. Unwrap
				// before filtering so rows nest once under the result key and
				// --select filters rows, not envelope keys; plain created-object
				// responses pass through unwrapSingleKeyArray untouched.
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				var selectErr error
				filtered := unwrapSingleKeyArray(data)
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "models", partialFailure.Message))
				}
				return selectErr
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlagsMeta renders the body with live
			// provenance, then the typed partial-failure exit fires unless
			// --allow-partial-failure downgrades it. Without this guard a
			// partial failure would exit 0 for these output modes — the exact
			// silent-swallow regression the surrounding patch is preventing
			// for asJSON / piped output.
			printErr := printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"}, nil)
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "models", partialFailure.Message))
			}
			return printErr
		},
	}
	cmd.Flags().BoolVar(&bodyActive, "active", false, "")
	cmd.Flags().StringVar(&bodyAiEngineConfigInferenceOptions, "ai-engine-config-inference-options", "", "")
	cmd.Flags().StringVar(&bodyAiEngineConfigInputs, "ai-engine-config-inputs", "", "")
	cmd.Flags().StringVar(&bodyAiEngineConfigOutcomes, "ai-engine-config-outcomes", "", "")
	cmd.Flags().StringVar(&bodyAiEngineConfigPredictEngineType, "ai-engine-config-predict-engine-type", "", "")
	cmd.Flags().BoolVar(&bodyAllowPublicComponentAccess, "allow-public-component-access", false, "")
	cmd.Flags().StringVar(&bodyAppEngineId, "app-engine-id", "", "")
	cmd.Flags().StringVar(&bodyAuthor, "author", "", "")
	cmd.Flags().StringVar(&bodyComputeType, "compute-type", "", "")
	cmd.Flags().IntVar(&bodyEngineCostPerSecond, "engine-cost-per-second", 0, "")
	cmd.Flags().StringVar(&bodyEngineStatus, "engine-status", "", "")
	cmd.Flags().StringVar(&bodyEntityType, "entity-type", "", "")
	cmd.Flags().StringVar(&bodyId, "id", "", "")
	cmd.Flags().StringVar(&bodyInterfaceDisplayOptions, "interface-display-options", "", "Free-form map keyed by variable name. Pass as JSON.")
	cmd.Flags().StringVar(&bodyInterfaceType, "interface-type", "", "")
	cmd.Flags().BoolVar(&bodyIsPublic, "is-public", false, "")
	cmd.Flags().BoolVar(&bodyLongRunningInference, "long-running-inference", false, "")
	cmd.Flags().StringVar(&bodyModelAlias, "model-alias", "", "")
	cmd.Flags().StringVar(&bodyModelDataFilePathsMODELDESCRIPTION, "model-data-file-paths-modeldescription", "", "")
	cmd.Flags().StringVar(&bodyModelDescription, "model-description", "", "")
	cmd.Flags().StringVar(&bodyModelId, "model-id", "", "")
	cmd.Flags().StringVar(&bodyModelLongDescription, "model-long-description", "", "")
	cmd.Flags().StringVar(&bodyModelName, "model-name", "", "")
	cmd.Flags().StringVar(&bodyModelType, "model-type", "", "")
	cmd.Flags().BoolVar(&bodyNeedsContext, "needs-context", false, "")
	cmd.Flags().StringVar(&bodyOwnerSubscriptionType, "owner-subscription-type", "", "")
	cmd.Flags().StringVar(&bodyParentRepositoryId, "parent-repository-id", "", "")
	cmd.Flags().IntVar(&bodyPerformanceScore, "performance-score", 0, "")
	cmd.Flags().IntVar(&bodyPerformanceStatsAccuracy, "performance-stats-accuracy", 0, "")
	cmd.Flags().IntVar(&bodyPerformanceStatsAuc, "performance-stats-auc", 0, "")
	cmd.Flags().IntVar(&bodyPerformanceStatsBleuScore, "performance-stats-bleu-score", 0, "")
	cmd.Flags().IntVar(&bodyPerformanceStatsDunnIndex, "performance-stats-dunn-index", 0, "")
	cmd.Flags().IntVar(&bodyPerformanceStatsF1Score, "performance-stats-f1-score", 0, "")
	cmd.Flags().StringVar(&bodyPerformanceStatsMetrics, "performance-stats-metrics", "", "")
	cmd.Flags().IntVar(&bodyPerformanceStatsPrecision, "performance-stats-precision", 0, "")
	cmd.Flags().IntVar(&bodyPerformanceStatsR2, "performance-stats-r2", 0, "")
	cmd.Flags().IntVar(&bodyPerformanceStatsRecall, "performance-stats-recall", 0, "")
	cmd.Flags().StringVar(&bodyPermissions, "permissions", "", "")
	cmd.Flags().StringVar(&bodyPricingInfoEnableMonetization, "pricing-info-enable-monetization", "", "")
	cmd.Flags().StringVar(&bodyPricingInfoModelOwnerPaysComputeCost, "pricing-info-model-owner-pays-compute-cost", "", "")
	cmd.Flags().StringVar(&bodyPricingInfoNoChargeOnInferenceWithError, "pricing-info-no-charge-on-inference-with-error", "", "")
	cmd.Flags().StringVar(&bodyPricingInfoServicePricingInfo, "pricing-info-service-pricing-info", "", "")
	cmd.Flags().StringVar(&bodyPricingInfoSkipUsageChargeInSameCtx, "pricing-info-skip-usage-charge-in-same-ctx", "", "")
	cmd.Flags().StringVar(&bodySupportedInterfaces, "supported-interfaces", "", "")
	cmd.Flags().StringVar(&bodySupportingLinks, "supporting-links", "", "")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "")
	cmd.Flags().IntVar(&bodyTotalCost, "total-cost", 0, "")
	cmd.Flags().IntVar(&bodyTotalInferences, "total-inferences", 0, "")
	cmd.Flags().IntVar(&bodyTotalViews, "total-views", 0, "")
	cmd.Flags().StringVar(&bodyVariableDisplayOptions, "variable-display-options", "", "Free-form map keyed by variable name. Pass as JSON.")
	cmd.Flags().StringVar(&bodyVisibility, "visibility", "", "")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
