// Copyright 2026 abhirup and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newModelsListSearchCmd(flags *rootFlags) *cobra.Command {
	var flagAisearch bool
	var flagModelType string
	var flagPage string
	var flagPageCount int
	var flagSort string

	cmd := &cobra.Command{
		Use:         "list-search",
		Short:       "Browse the model catalogue (GET /api/models/search)",
		Long: "Browse/rank the catalogue. Measured server behavior: text queries (searchBy,\n" +
			"searchterm) are silently ignored on this route in both ranking modes — no text\n" +
			"filter exists for the public catalogue. --aisearch only switches ranking mode.\n" +
			"To search models by name, use `models list-usermodels --searchterm`.",
		Example:     "  unitypredict-pp-cli models list-search",
		Annotations: map[string]string{"pp:endpoint": "models.list_search", "pp:method": "GET", "pp:path": "/api/models/search", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/api/models/search"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			// Measured 2026-09-19: this route silently ignores text queries
			// (searchBy/searchterm) in both keyword and AI mode — totalCount and
			// ordering are identical with a nonsense term. aisearch only switches
			// the ranking mode. Text filtering lives on list-usermodels --searchterm.
			if flagAisearch != false {
				params["aisearch"] = formatCLIParamValue(flagAisearch)
			}
			if flagModelType != "" {
				params["modelType"] = formatCLIParamValue(flagModelType)
			}
			if flagPage != "" {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagPageCount != 0 {
				params["pageCount"] = formatCLIParamValue(flagPageCount)
			}
			if flagSort != "" {
				params["sort"] = formatCLIParamValue(flagSort)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "models", true, path, params, nil, "results", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"favIconUrl": true, "modelId": true, "modelName": true, "modelTitle": true, "socialStatus": true, "thumbnailUrl": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"favIconUrl": true, "modelId": true, "modelName": true, "modelTitle": true, "socialStatus": true, "thumbnailUrl": true})
		},
	}
	cmd.Flags().BoolVar(&flagAisearch, "aisearch", false, "Switch to AI relevance ranking (does not filter by text)")
	cmd.Flags().StringVar(&flagModelType, "model-type", "", "Model type filter (e.g. HostedModel)")
	cmd.Flags().StringVar(&flagPage, "page", "", "Page number (1-based)")
	cmd.Flags().IntVar(&flagPageCount, "page-count", 0, "Results per page")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort order (e.g. Relevance)")

	return cmd
}
