// Copyright 2026 abhirup and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newModelsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "models",
		Short:       "List, get, and create models",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newModelsCreateModelsCmd(flags))
	cmd.AddCommand(newModelsGetMODELDESCRIPTIONCmd(flags))
	cmd.AddCommand(newModelsGetMODELDESCRIPTION2Cmd(flags))
	cmd.AddCommand(newModelsGetTHUMBNAILCmd(flags))
	cmd.AddCommand(newModelsGetModelsCmd(flags))
	cmd.AddCommand(newModelsListSearchCmd(flags))
	cmd.AddCommand(newModelsListUsermodelsCmd(flags))
	return cmd
}
