// Copyright 2026 abhirup and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newToolsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "tools",
		Short:       "Manage tools command groups",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newToolsListAnalyticsCmd(flags))
	cmd.AddCommand(newToolsListDevAbhirupdas8C0AF724114435Cmd(flags))
	return cmd
}
