// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package platform

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
)

const ProfileSchemaVersion = 1

var profileNamePattern = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,62}$`)

// Profile is the cross-source, non-secret client configuration shared by
// participating printed CLIs.
type Profile struct {
	SchemaVersion int                      `toml:"schema_version" json:"schema_version"`
	Name          string                   `toml:"name" json:"name"`
	Sources       map[string]SourceProfile `toml:"sources" json:"sources"`
}

// SourceProfile contains references and public identity assertions only.
// Resolved credential bytes never enter this structure.
type SourceProfile struct {
	CredentialRef            string            `toml:"credential_ref,omitempty" json:"credential_ref,omitempty"`
	UsernameRef              string            `toml:"username_ref,omitempty" json:"username_ref,omitempty"`
	AdditionalCredentialRefs map[string]string `toml:"additional_credential_refs,omitempty" json:"additional_credential_refs,omitempty"`
	ExpectedAccountID        string            `toml:"expected_account_id,omitempty" json:"expected_account_id,omitempty"`
	ExpectedOrgName          string            `toml:"expected_org_name,omitempty" json:"expected_org_name,omitempty"`
	ExpectedStoreID          string            `toml:"expected_store_id,omitempty" json:"expected_store_id,omitempty"`
	ExpectedStoreDomain      string            `toml:"expected_store_domain,omitempty" json:"expected_store_domain,omitempty"`
	ExpectedPropertyID       string            `toml:"expected_property_id,omitempty" json:"expected_property_id,omitempty"`
	ExpectedBaseURL          string            `toml:"expected_base_url,omitempty" json:"expected_base_url,omitempty"`
}

// Paths are the profile/source-isolated filesystem locations for one CLI.
type Paths struct {
	ProfileFile string `json:"profile_file"`
	ConfigFile  string `json:"config_file"`
	ReceiptsDir string `json:"receipts_dir"`
}

// CredentialResolver resolves one exact external reference into memory.
type CredentialResolver interface {
	Resolve(context.Context, string) ([]byte, error)
}

// ResolvedCredentials holds credential bytes only for the current process.
type ResolvedCredentials map[string][]byte

// Zero overwrites all retained credential buffers.
func (r ResolvedCredentials) Zero() {
	for key, value := range r {
		for i := range value {
			value[i] = 0
		}
		delete(r, key)
	}
}

func ValidateProfileName(name string) error {
	if !profileNamePattern.MatchString(name) || strings.Contains(name, "..") {
		return fmt.Errorf("invalid client profile name %q", name)
	}
	return nil
}

func normalizeSourceSlug(source string) string {
	source = strings.ToLower(strings.TrimSpace(source))
	source = strings.ReplaceAll(source, "_", "-")
	return source
}

func (p *Profile) Validate() error {
	if p.SchemaVersion != ProfileSchemaVersion {
		return fmt.Errorf("unsupported client profile schema_version %d", p.SchemaVersion)
	}
	if err := ValidateProfileName(p.Name); err != nil {
		return err
	}
	if len(p.Sources) == 0 {
		return errors.New("client profile must contain at least one source")
	}
	seen := map[string]string{}
	for raw, source := range p.Sources {
		normalized := normalizeSourceSlug(raw)
		if err := ValidateProfileName(normalized); err != nil {
			return fmt.Errorf("invalid source %q: %w", raw, err)
		}
		if prior, ok := seen[normalized]; ok {
			return fmt.Errorf("duplicate source entries %q and %q after normalization", prior, raw)
		}
		seen[normalized] = raw
		if err := source.Validate(); err != nil {
			return fmt.Errorf("source %q: %w", raw, err)
		}
	}
	return nil
}

func (s SourceProfile) Validate() error {
	for name, ref := range s.AdditionalCredentialRefs {
		if strings.TrimSpace(name) == "" {
			return errors.New("additional credential reference name may not be empty")
		}
		if ref == "" {
			return fmt.Errorf("additional credential reference %q may not be empty", name)
		}
	}
	if len(s.ExpectedIdentity()) == 0 {
		return errors.New("at least one expected identity assertion is required")
	}
	return nil
}

func (s SourceProfile) References() map[string]string {
	refs := make(map[string]string, len(s.AdditionalCredentialRefs)+2)
	if s.CredentialRef != "" {
		refs["credential"] = s.CredentialRef
	}
	if s.UsernameRef != "" {
		refs["username"] = s.UsernameRef
	}
	for name, ref := range s.AdditionalCredentialRefs {
		refs[name] = ref
	}
	return refs
}

func (s SourceProfile) ExpectedIdentity() map[string]string {
	values := map[string]string{
		"account_id":   s.ExpectedAccountID,
		"org_name":     s.ExpectedOrgName,
		"store_id":     s.ExpectedStoreID,
		"store_domain": s.ExpectedStoreDomain,
		"property_id":  s.ExpectedPropertyID,
		"base_url":     s.ExpectedBaseURL,
	}
	for key, value := range values {
		if strings.TrimSpace(value) == "" {
			delete(values, key)
		}
	}
	return values
}

func ProfilePath(name string) (string, error) {
	_ = name
	return "", errors.New("client profile persistence is disabled; use secure auth configuration")
}

func LoadProfile(name string) (*Profile, error) {
	_ = name
	return nil, errors.New("client profile persistence is disabled; use secure auth configuration")
}

func SaveProfile(_ *Profile) error {
	return errors.New("client profile persistence is disabled; use secure auth configuration")
}

func ListProfiles() ([]string, error) { return []string{}, nil }

func SetDefaultProfile(name string) error {
	_ = name
	return errors.New("client profile persistence is disabled; use secure auth configuration")
}

func DeleteProfile(name string) error {
	_ = name
	return errors.New("client profile persistence is disabled; use secure auth configuration")
}

// SelectProfile never reads a local profile registry. Explicit profiles are
// rejected because the live-only CLI authenticates through config.Load.
func SelectProfile(explicit string) (string, error) {
	if strings.TrimSpace(explicit) != "" || strings.TrimSpace(os.Getenv("PRINTING_PRESS_CLIENT_PROFILE")) != "" {
		return "", errors.New("client profiles are disabled; configure authentication through the secure auth config")
	}
	return "", errors.New("client profiles are disabled")
}

func PathsFor(profileName, cliName, source string) (Paths, error) {
	if err := ValidateProfileName(profileName); err != nil {
		return Paths{}, err
	}
	if err := ValidateProfileName(normalizeSourceSlug(strings.TrimSuffix(cliName, "-pp-cli"))); err != nil {
		return Paths{}, err
	}
	if err := ValidateProfileName(normalizeSourceSlug(source)); err != nil {
		return Paths{}, err
	}
	return Paths{}, nil
}

func resolveCredentials(ctx context.Context, resolver CredentialResolver, source SourceProfile) (ResolvedCredentials, error) {
	refs := source.References()
	resolved := make(ResolvedCredentials, len(refs))
	if len(refs) == 0 {
		return resolved, nil
	}
	if resolver == nil {
		return nil, errors.New("credential resolver is required for credential references")
	}
	keys := make([]string, 0, len(refs))
	for key := range refs {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		value, err := resolver.Resolve(ctx, refs[key])
		if err != nil {
			resolved.Zero()
			return nil, fmt.Errorf("resolve %s reference: %w", key, err)
		}
		resolved[key] = value
	}
	return resolved, nil
}

func credentialFingerprint(credentials ResolvedCredentials) (string, error) {
	// Fingerprints are process-local derivations. They are never written to a
	// state directory or used as a persistent cache key.
	hash := sha256.New()
	keys := make([]string, 0, len(credentials))
	for name := range credentials {
		keys = append(keys, name)
	}
	sort.Strings(keys)
	for _, name := range keys {
		_, _ = io.WriteString(hash, fmt.Sprintf("%d:%s:%d:", len(name), name, len(credentials[name])))
		_, _ = hash.Write(credentials[name])
	}
	return hex.EncodeToString(hash.Sum(nil)), nil
}
