// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"chatgpt-pp-cli/internal/cli"
	"chatgpt-pp-cli/internal/client"
	"chatgpt-pp-cli/internal/cliutil"
	"chatgpt-pp-cli/internal/config"
	"chatgpt-pp-cli/internal/learn"
	"chatgpt-pp-cli/internal/mcp/bound"
	"chatgpt-pp-cli/internal/mcp/cobratree"
	"chatgpt-pp-cli/internal/platform"
	"chatgpt-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	s.AddTool(
		mcplib.NewTool("chat_prepare",
			mcplib.WithDescription("Conduit prepare — mints the short-lived (60s) conduit token required by the send call. Returns the new ConduitPrepare."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/backend-api/f/conversation/prepare", false, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("chat_requirements",
			mcplib.WithDescription("Sentinel gate — returns requirements token, PoW seed/difficulty, turnstile requirement (token values are credential material). Optional: proof."),
			mcplib.WithString("proof", mcplib.Description("Base64 fingerprint/proof payload (empty for the first mint)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/backend-api/sentinel/chat-requirements", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "proof", WireName: "p", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("chat_send",
			mcplib.WithDescription("Send a message — SSE response with typed events; message_stream_complete is the semantic terminal; resume_conversation_token enables reconnection. EXPERIMENTAL: turnstile-gated; fails clearly without legitimately issued authorization. Required: action, messages, parent_message_id, model. Optional: conversation_id, timezone_offset_min, thinking_effort."),
			mcplib.WithString("action", mcplib.Required(), mcplib.Description("Always 'next'")),
			mcplib.WithArray("messages", mcplib.Required(), mcplib.Description("Message array (id + author role user + content object with content_type text and parts list)")),
			mcplib.WithString("conversation_id", mcplib.Description("Conversation UUID — omit to start a new chat")),
			mcplib.WithString("parent_message_id", mcplib.Required(), mcplib.Description("Parent node — current_node for a follow-up")),
			mcplib.WithString("model", mcplib.Required(), mcplib.Description("Model slug (see models list)")),
			mcplib.WithNumber("timezone_offset_min", mcplib.Description("Timezone offset in minutes")),
			mcplib.WithString("thinking_effort", mcplib.Description("Thinking effort (low|standard|high)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/backend-api/f/conversation", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "action", WireName: "action", Location: "body"}, {PublicName: "messages", WireName: "messages", Location: "body"}, {PublicName: "conversation_id", WireName: "conversation_id", Location: "body"}, {PublicName: "parent_message_id", WireName: "parent_message_id", Location: "body"}, {PublicName: "model", WireName: "model", Location: "body"}, {PublicName: "timezone_offset_min", WireName: "timezone_offset_min", Location: "body"}, {PublicName: "thinking_effort", WireName: "thinking_effort", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("conversations_get",
			mcplib.WithDescription("Full conversation as the webapp consumes it — messages array plus Relay page_info; has_next_page can be false on truncated windows, verify against current_node. Required: conversation_id. Optional: num_turns, include_has_versions. Returns the Conversation."),
			mcplib.WithString("conversation_id", mcplib.Required(), mcplib.Description("Conversation UUID")),
			mcplib.WithNumber("num_turns", mcplib.Description("Turn-window limit (response may still claim has_next_page=false)")),
			mcplib.WithBoolean("include_has_versions", mcplib.Description("Include version flags")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/backend-api/conversations/{conversation_id}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "conversation_id", WireName: "conversation_id", Location: "path"}, {PublicName: "num_turns", WireName: "num_turns", Location: "query"}, {PublicName: "include_has_versions", WireName: "include_has_versions", Location: "query"}}, []string{"conversation_id"}),
	)
	s.AddTool(
		mcplib.NewTool("conversations_get_tree",
			mcplib.WithDescription("Legacy compat read — singular endpoint returns the parent/children mapping tree (visible roles only; no hidden system/thoughts nodes). Required: conversation_id."),
			mcplib.WithString("conversation_id", mcplib.Required(), mcplib.Description("Conversation UUID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/backend-api/conversation/{conversation_id}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "conversation_id", WireName: "conversation_id", Location: "path"}}, []string{"conversation_id"}),
	)
	s.AddTool(
		mcplib.NewTool("conversations_list",
			mcplib.WithDescription("Chronological conversation list — offset/limit pagination; total is a min(realTotal, offset+limit+1) hint, walk pages until a short page. Optional: offset (default: 0), limit (default: 28), order (default: updated) (plus 2 more). Returns the ConversationList."),
			mcplib.WithNumber("offset", mcplib.Description("Pagination offset")),
			mcplib.WithNumber("limit", mcplib.Description("Page size (max 100; 999 rejected as 422)")),
			mcplib.WithString("order", mcplib.Description("Sort key (updated accepted; created returns 500 — sort client-side)")),
			mcplib.WithBoolean("is_archived", mcplib.Description("Filter archived conversations")),
			mcplib.WithBoolean("is_starred", mcplib.Description("Filter starred conversations")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/backend-api/conversations", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "offset", WireName: "offset", Location: "query", Default: "0"}, {PublicName: "limit", WireName: "limit", Location: "query", Default: "28"}, {PublicName: "order", WireName: "order", Location: "query", Default: "updated"}, {PublicName: "is_archived", WireName: "is_archived", Location: "query"}, {PublicName: "is_starred", WireName: "is_starred", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("conversations_list_messages",
			mcplib.WithDescription("Message window with forward cursor — after=<message_id> returns everything after that id (cursor/limit/end_cursor params are ignored here). Required: conversation_id. Optional: after."),
			mcplib.WithString("conversation_id", mcplib.Required(), mcplib.Description("Conversation UUID")),
			mcplib.WithString("after", mcplib.Description("Return messages after this message id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/backend-api/conversations/{conversation_id}/messages", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "conversation_id", WireName: "conversation_id", Location: "path"}, {PublicName: "after", WireName: "after", Location: "query"}}, []string{"conversation_id"}),
	)
	s.AddTool(
		mcplib.NewTool("conversations_search",
			mcplib.WithDescription("Legacy search — query param is literally 'query' (not q); returns message-level hits with snippets. Required: query. Optional: offset, limit."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search text")),
			mcplib.WithNumber("offset", mcplib.Description("Result offset")),
			mcplib.WithNumber("limit", mcplib.Description("Result limit")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/backend-api/conversations/search", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "query", WireName: "query", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}}, []string{"query"}),
	)
	s.AddTool(
		mcplib.NewTool("conversations_stream_status",
			mcplib.WithDescription("Streaming state for an active send (404 when idle) — used by status/wait. Required: conversation_id. Returns the StreamStatus."),
			mcplib.WithString("conversation_id", mcplib.Required(), mcplib.Description("Conversation UUID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/backend-api/conversations/{conversation_id}/stream_status", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "conversation_id", WireName: "conversation_id", Location: "path"}}, []string{"conversation_id"}),
	)
	s.AddTool(
		mcplib.NewTool("global_search_global",
			mcplib.WithDescription("Federated message-content search across conversations and projects — strict body schema (extra fields 422); cursor pagination. Required: query. Optional: limit, cursor. Returns the new GlobalSearchResults."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search text")),
			mcplib.WithNumber("limit", mcplib.Description("Page size")),
			mcplib.WithString("cursor", mcplib.Description("Opaque cursor from the previous response")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/backend-api/global/search", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "limit", WireName: "limit", Location: "body"}, {PublicName: "cursor", WireName: "cursor", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("models_list",
			mcplib.WithDescription("Model picker inventory — slugs, reasoning types, thinking efforts, default badge. Optional: history_view_enabled. Returns the ModelsResponse."),
			mcplib.WithBoolean("history_view_enabled", mcplib.Description("Include history-view models")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/backend-api/models", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "history_view_enabled", WireName: "history_view_enabled", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("session_get",
			mcplib.WithDescription("Current session, account, and freshly minted access token (values are credential material — never logged). Returns the Session."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/auth/session", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='chat'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext(s),
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
	Default    string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcpToolError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set it with: echo \"$TOKEN\" | chatgpt-pp-cli auth set-token or export CHATGPT_TOKEN=\"your-token-here\"" +
					"\n      See API docs: https://chatgpt.com" +
					"\n      Run 'chatgpt-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: echo \"$TOKEN\" | chatgpt-pp-cli auth set-token or export CHATGPT_TOKEN=\"your-token-here\"" +
					"\n      See API docs: https://chatgpt.com" +
					"\n      Run 'chatgpt-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Set it with: echo \"$TOKEN\" | chatgpt-pp-cli auth set-token or export CHATGPT_TOKEN=\"your-token-here\"" +
					"\n      See API docs: https://chatgpt.com" +
					"\n      Run 'chatgpt-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	return newMCPClientFromConfig(ctx, cfg)
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(ctx context.Context, cfg *config.Config) (*client.Client, *platform.Session, error) {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	if err := cli.ApplyClientHooks(c); err != nil {
		if session != nil {
			session.ZeroCredentials()
		}
		return nil, nil, fmt.Errorf("initializing MCP client: %w", err)
	}
	return c, session, nil
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

type mcpStoreStatusKind string

const (
	mcpStoreStatusEmpty   mcpStoreStatusKind = "empty"
	mcpStoreStatusPartial mcpStoreStatusKind = "partial"
	mcpStoreStatusReady   mcpStoreStatusKind = "ready"
)

func openMCPReadOnlyStore(path string) (*store.Store, *mcplib.CallToolResult) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, mcplib.NewToolResultError(mcpMissingStoreMessage(path))
		}
		return nil, mcplib.NewToolResultError(fmt.Sprintf("checking local data store %s: %v", path, err))
	}
	db, err := store.OpenReadOnly(path)
	if err != nil {
		return nil, mcplib.NewToolResultError(fmt.Sprintf("opening local data store %s: %v. Run chatgpt-pp-cli sync --resources conversations,models to refresh the store, or use live endpoint MCP tools for unsynced data.", path, err))
	}
	return db, nil
}

func mcpMissingStoreMessage(path string) string {
	return fmt.Sprintf("No local data store found at %s. Run chatgpt-pp-cli sync --resources conversations,models before using MCP search/sql, or use live endpoint MCP tools for unsynced data.", path)
}

func mcpStoreStatus(db *store.Store) (mcpStoreStatusKind, error) {
	status, err := db.Status()
	if err != nil {
		return "", err
	}
	var checkpoints, completed int
	err = db.DB().QueryRow(`SELECT COUNT(*), COALESCE(SUM(CASE WHEN last_attempt_complete = 1 THEN 1 ELSE 0 END), 0) FROM sync_state`).Scan(&checkpoints, &completed)
	if err != nil && strings.Contains(strings.ToLower(err.Error()), "no such column: last_attempt_complete") {
		// Read-only stores have not run the conservative completion migration.
		// Legacy timestamps were also written by partial walks, so prove nothing.
		err = db.DB().QueryRow(`SELECT COUNT(*), 0 FROM sync_state`).Scan(&checkpoints, &completed)
	}
	if err != nil {
		msg := strings.ToLower(err.Error())
		if strings.Contains(msg, "no such table") || strings.Contains(msg, "no such column") {
			if len(status) > 0 {
				return mcpStoreStatusReady, nil
			}
			return mcpStoreStatusEmpty, nil
		}
		return "", err
	}
	if checkpoints > 0 {
		if completed == checkpoints {
			return mcpStoreStatusReady, nil
		}
		return mcpStoreStatusPartial, nil
	}
	if len(status) > 0 {
		return mcpStoreStatusReady, nil
	}
	return mcpStoreStatusEmpty, nil
}

func mcpEmptyStoreNextStep() string {
	return "Run chatgpt-pp-cli sync --resources conversations,models to populate the local SQLite store before using MCP search/sql."
}

func mcpPartialStoreNextStep() string {
	return "The latest sync attempt is incomplete. Resume or rerun chatgpt-pp-cli sync --resources conversations,models before treating local search/sql results as a complete snapshot."
}

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSearchEnvelope(results, storeStatus))
}

func mcpSearchEnvelope(results []json.RawMessage, storeStatus mcpStoreStatusKind) map[string]any {
	if results == nil {
		results = []json.RawMessage{}
	}
	out := map[string]any{
		"count":        len(results),
		"results":      results,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if storeStatus == mcpStoreStatusPartial {
		out["warning"] = "Local data may be incomplete because the latest sync attempt did not finish."
		out["next_step"] = mcpPartialStoreNextStep()
	} else if len(results) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "No local search matches. Try a broader query, a lower-specificity FTS expression, or sync again if data may be stale."
		}
	}
	return out
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	queryCtx, cancel := bound.WithSQLQueryDeadline(ctx)
	defer cancel()

	rows, err := db.DB().QueryContext(queryCtx, query)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	scan := bound.NewSQLScanState(cols)
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		if !scan.Add(row) {
			break
		}
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSQLEnvelope(scan.Rows, cols, storeStatus, scan.Truncated))
}

func mcpSQLEnvelope(rows []map[string]any, columns []string, storeStatus mcpStoreStatusKind, truncated bool) map[string]any {
	if rows == nil {
		rows = []map[string]any{}
	}
	out := map[string]any{
		"count":        len(rows),
		"columns":      columns,
		"rows":         rows,
		"store_status": storeStatus,
		"resumable":    false,
		"truncated":    truncated,
	}
	if truncated {
		out["returned_count"] = len(rows)
		out["max_bytes"] = bound.MaxBytes
		out["note"] = bound.SQLResultBoundNote
	}
	if storeStatus == mcpStoreStatusPartial {
		out["warning"] = "Local data may be incomplete because the latest sync attempt did not finish."
		out["next_step"] = mcpPartialStoreNextStep()
	} else if len(rows) == 0 && !truncated {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "The read-only SQL query returned no rows. Check resource_type filters, json_extract paths, or run chatgpt-pp-cli sync --resources conversations,models again if data may be stale."
		}
	}
	return out
}

func mcpSQLQueryError(queryCtx context.Context, err error) string {
	if queryCtx.Err() != nil {
		return fmt.Sprintf("query cancelled: %v. MCP SQL queries are bounded to %s; narrow the query with WHERE, GROUP BY, or an aggregate.", err, bound.SQLQueryTimeout)
	}
	msg := err.Error()
	if strings.Contains(strings.ToLower(msg), "no such table") {
		return fmt.Sprintf("query failed: %v. Synced records live in resources(resource_type, id, data), not one SQL table per resource. Filter by resource_type, for example resource_type='chat', and read JSON fields with json_extract(data,'$.field').", err)
	}
	return fmt.Sprintf("query failed: %v", err)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}
func registeredCommandMirrorCapabilities(s *server.MCPServer, capabilities []map[string]string) []map[string]string {
	registered := make([]map[string]string, 0, len(capabilities))
	root := cli.RootCmd()
	for _, capability := range capabilities {
		toolName := cobratree.ToolNameForCommand(s, root, capability["cli_command"])
		if toolName == "" {
			continue
		}
		entry := s.GetTool(toolName)
		if entry == nil || entry.Tool.Meta == nil || entry.Tool.Meta.AdditionalFields["pp:tenant-gate"] != "child-cli" {
			continue
		}
		capability["mcp_tool"] = toolName
		registered = append(registered, capability)
	}
	return registered
}

func handleContext(s *server.MCPServer) func(context.Context, mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		return handleContextResult(s, ctx, req)
	}
}

func handleContextResult(s *server.MCPServer, _ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "chatgpt",
		"description": "Your ChatGPT history as a queryable local archive — verified-complete extraction, outlines, and search no other tool has.",
		"archetype":   "communication",
		"tool_count":  len(s.ListTools()),
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion chatgpt-pp-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "CHATGPT_TOKEN",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"docs_url": "https://chatgpt.com",
		},
		"resources": []map[string]any{
			{
				"name":        "chat",
				"description": "Experimental send surface — browser-gated, no Turnstile solver",
				"endpoints":   []string{"prepare", "requirements", "send"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "conversations",
				"description": "Conversation inventory and full extraction",
				"endpoints":   []string{"get", "get_tree", "list", "list_messages", "search", "stream_status"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "global_search",
				"description": "Global search (the Ctrl+K surface)",
				"endpoints":   []string{"global"},
				"searchable":  true,
			},
			{
				"name":        "models",
				"description": "Available ChatGPT models",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
			{
				"name":        "session",
				"description": "Authenticated session state — the bearer mint source",
				"endpoints":   []string{"get"},
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": registeredCommandMirrorCapabilities(s, []map[string]string{
			{"name": "Hydrated chronological inventory", "command": "list --hydrate", "cli_command": "list --hydrate", "description": "See every chat in chronological order with turn counts, time span, and freshness — not just titles.", "rationale": "The list API returns no counts (verified empirically)", "via": "mcp-command-mirror"},
			{"name": "Verified-complete extraction", "command": "transcript --verify", "cli_command": "transcript --verify", "description": "Extract an entire conversation with a completeness proof against the live tree state.", "rationale": "The detail API's has_next_page can report false on truncated windows (empirical)", "via": "mcp-command-mirror"},
			{"name": "Long-thread outline", "command": "outline", "cli_command": "outline", "description": "Map a long thread into titled sections at each of your prompts, with timestamps and anchors.", "rationale": "ChatGPT's own table of contents derives purely from user messages (verified via React inspection)", "via": "mcp-command-mirror"},
			{"name": "Section-sliced extraction", "command": "transcript --section", "cli_command": "transcript --section", "description": "Extract just part of a long conversation by section number or message anchors.", "rationale": "Outline anchors index into the message array, so slicing is a local range computation no API provides.", "via": "mcp-command-mirror"},
			{"name": "Dual-mode search", "command": "search", "cli_command": "search", "description": "Search message content server-side by default, or offline over your synced archive.", "rationale": "The Ctrl+K global search endpoint returns federated message-level hits", "via": "mcp-command-mirror"},
		}),
		"playbook": []map[string]string{
			{"topic": "Hydrated chronological inventory", "insight": "The list API returns no counts (verified empirically); a local SQLite hydration cache computes them incrementally by update watermark."},
			{"topic": "Verified-complete extraction", "insight": "The detail API's has_next_page can report false on truncated windows (empirical); cursor-walking to current_node with verification is the only safe extraction."},
			{"topic": "Long-thread outline", "insight": "ChatGPT's own table of contents derives purely from user messages (verified via React inspection); the same derivation over the API needs no extra endpoint."},
			{"topic": "Section-sliced extraction", "insight": "Outline anchors index into the message array, so slicing is a local range computation no API provides."},
			{"topic": "Dual-mode search", "insight": "The Ctrl+K global search endpoint returns federated message-level hits; the synced SQLite store mirrors it for offline work."},
			{"topic": "Message search", "insight": "Use the search tool on synced data rather than paginating through message history. Message APIs often have aggressive rate limits."},
			{"topic": "Channel health", "insight": "When analyzing channel activity, use sql aggregation on synced messages. Don't iterate individual messages via API."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
