// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCompanyCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "company",
		Short:       "Indian company identity, fundamentals, reports, scorecards, and public signals.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCompanyAggregatedDealsCmd(flags))
	cmd.AddCommand(newCompanyAiSummaryCmd(flags))
	cmd.AddCommand(newCompanyChartInterCmd(flags))
	cmd.AddCommand(newCompanyChartIntraCmd(flags))
	cmd.AddCommand(newCompanyChecklistCmd(flags))
	cmd.AddCommand(newCompanyFinancialsCmd(flags))
	cmd.AddCommand(newCompanyForecastCmd(flags))
	cmd.AddCommand(newCompanyInfoCmd(flags))
	cmd.AddCommand(newCompanyNewsCmd(flags))
	cmd.AddCommand(newCompanyRatingsCmd(flags))
	cmd.AddCommand(newCompanyRatiosCmd(flags))
	cmd.AddCommand(newCompanyScorecardCmd(flags))
	cmd.AddCommand(newCompanySmallcasesCmd(flags))
	cmd.AddCommand(newCompanySummaryCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelCompanyBriefCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelCompanyTimelineCmd(flags))
	return cmd
}
