// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMutualfundCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "mutualfund",
		Short:       "Mutual-fund discovery, summary, holdings, charts, managers, and checklists.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMutualfundChartInterCmd(flags))
	cmd.AddCommand(newMutualfundChartSipCmd(flags))
	cmd.AddCommand(newMutualfundChecklistCmd(flags))
	cmd.AddCommand(newMutualfundHoldingsCmd(flags))
	cmd.AddCommand(newMutualfundInfoCmd(flags))
	cmd.AddCommand(newMutualfundListCmd(flags))
	cmd.AddCommand(newMutualfundManagersCmd(flags))
	cmd.AddCommand(newMutualfundSummaryCmd(flags))
	cmd.AddCommand(newMutualfundWidgetCmd(flags))
	return cmd
}
