// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"tickertape-pp-cli/internal/client"
	"tickertape-pp-cli/internal/config"
	"tickertape-pp-cli/internal/platform"
)

type rootFlags struct {
	asJSON     bool
	compact    bool
	csv        bool
	plain      bool
	quiet      bool
	dryRun     bool
	noInput    bool
	idempotent bool
	yes        bool
	agent      bool
	// allowPartialFailure downgrades a detected response-body partial-failure
	// (e.g. Google Ads `partialFailureError`) from a non-zero exit to a
	// stderr warning. Default false so silent partial successes surface as
	// failures by default.
	allowPartialFailure     bool
	selectFields            string
	configPath              string
	homePath                string
	runProfileName          string
	clientProfileName       string
	platformSession         *platform.Session
	platformResolver        platform.CredentialResolver
	platformResolverReady   bool
	platformAnalytics       *platform.AnalyticsDeclaration
	platformGateError       error
	platformMetadataWriter  io.Writer
	receiptEnabled          bool
	receiptFile             string
	auditDir                string
	receiptWriter           *platform.ReceiptWriter
	platformMetadataEmitted bool
	deliverSpec             string
	timeout                 time.Duration
	timeoutExplicit         bool
	rateLimit               float64
	maxAge                  time.Duration
	dataSource              string
	agentSource             string
	freshnessMeta           any
}

// novelCommandHooks are optional hooks for hand-authored command extensions.
// A markerless file in package cli may register one from init without editing
// this generated root, so force regeneration preserves both the source and
// wiring. Hooks run after generated novel parent groups are attached so a
// hook can Find a novel parent and add children. Registration is additive:
// independent extensions never replace one another, except that a real
// command replaces a TODO scaffold with the same name.
var novelCommandHooks []func(root *cobra.Command, flags *rootFlags)

func registerNovelCommand(hook func(root *cobra.Command, flags *rootFlags)) {
	novelCommandHooks = append(novelCommandHooks, hook)
}

const novelScaffoldAnnotation = "pp:novel-scaffold"

func isNovelScaffoldCommand(cmd *cobra.Command) bool {
	return cmd != nil && cmd.Annotations[novelScaffoldAnnotation] == "true"
}

func addNovelCommandIfAbsent(parent *cobra.Command, candidate *cobra.Command) {
	if parent == nil || candidate == nil {
		return
	}
	for _, existing := range parent.Commands() {
		if existing.Name() != candidate.Name() {
			continue
		}
		if isNovelScaffoldCommand(existing) && !isNovelScaffoldCommand(candidate) {
			parent.RemoveCommand(existing)
			parent.AddCommand(candidate)
		}
		return
	}
	parent.AddCommand(candidate)
}

func preferImplementedNovelCommands(cmd *cobra.Command) {
	if cmd == nil {
		return
	}
	byName := map[string][]*cobra.Command{}
	for _, child := range cmd.Commands() {
		byName[child.Name()] = append(byName[child.Name()], child)
	}
	for _, group := range byName {
		var keep *cobra.Command
		for _, child := range group {
			if !isNovelScaffoldCommand(child) {
				keep = child
				break
			}
		}
		if keep == nil {
			continue
		}
		for _, child := range group {
			if child != keep && isNovelScaffoldCommand(child) {
				cmd.RemoveCommand(child)
			}
		}
	}
	for _, child := range cmd.Commands() {
		preferImplementedNovelCommands(child)
	}
}

// clientHooks let preserved package-local extensions configure a newly-created
// client without editing generated code. Hooks are additive and run once per
// client construction; they must not perform provider-specific behavior here.
var clientHooks []func(*client.Client) error

func registerClientHook(hook func(*client.Client) error) {
	clientHooks = append(clientHooks, hook)
}

// Keeps preserved post-construction setup consistent across interactive CLI
// and MCP clients.
func ApplyClientHooks(c *client.Client) error {
	for _, hook := range clientHooks {
		if err := hook(c); err != nil {
			return err
		}
	}
	return nil
}

// RootCmd returns the Cobra command tree without executing it. The MCP server
// uses this to mirror every user-facing command as an agent tool.
func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
// The named return feeds the deferred journal write: one site after
// ExecuteC returns covers every outcome, including RunE errors (a
// Cobra PostRun hook would be skipped on RunE error, so none is used).
func Execute() (retErr error) {
	var flags rootFlags
	rootCmd := newRootCmd(&flags)
	defer finalizePlatformInvocation(&flags, &retErr)

	err := rootCmd.Execute()
	if errors.Is(err, pflag.ErrHelp) {
		return nil
	}
	if err != nil && strings.Contains(err.Error(), "unknown flag") {
		msg := err.Error()
		// Extract the flag name from the error message (e.g., "unknown flag: --foob")
		if idx := strings.Index(msg, "unknown flag: "); idx >= 0 {
			flagStr := strings.TrimSpace(msg[idx+len("unknown flag: "):])
			if suggestion := suggestFlag(flagStr, rootCmd); suggestion != "" {
				// Cobra already printed `Error: unknown flag: --foob` before
				// returning; the wrap below attaches the hint to err.Error()
				// for downstream consumers and exit-code classification, but
				// would never reach stderr now that main.go no longer prints
				// err. Emit the hint explicitly so the suggestion still
				// shows up under Cobra's error line.
				fmt.Fprintf(os.Stderr, "hint: did you mean --%s?\n", suggestion)
				err = fmt.Errorf("%w\nhint: did you mean --%s?", err, suggestion)
			}
		}
	}
	if err != nil && isCobraUsageError(err) {
		// Cobra/pflag pre-RunE errors (unknown flag, unknown command,
		// missing required, etc.) never flow through usageErr() because
		// they originate inside rootCmd.Execute() before any user RunE
		// runs. Without this wrap, ExitCode() falls through to the
		// default and emits 1 — clobbering the conventional code-2 for
		// usage errors that the helpers.go contract already promises.
		return usageErr(err)
	}
	return err
}

// isCobraUsageError reports whether err matches one of Cobra/pflag's
// pre-RunE usage-error shapes. Detection is by message prefix to match
// the same approach the unknown-flag hint path uses above; neither
// Cobra nor pflag exports typed sentinels for these.
//
// Patterns are anchored to the literal punctuation Cobra and pflag
// emit so an application's own RunE error that happens to contain the
// substring "required flag" or "invalid argument" doesn't get
// misclassified as a usage error.
//
// Patterns covered (Cobra v1.x + pflag v1.x as of 2026-05):
//   - "unknown flag: --foo"                            (pflag)
//   - "unknown shorthand flag: 'x' in -x"              (pflag)
//   - "unknown command \"foo\" for ..."                (Cobra)
//   - "required flag \"foo\" not set"                  (Cobra, single missing)
//   - "required flag(s) \"foo\" not set"               (Cobra, multiple missing)
//   - "flag needs an argument: --foo"                  (pflag, missing value)
//   - "invalid argument \"x\" for \"--y\" flag: ..."   (pflag, parse failure)
//
// Cobra emits the singular form ("required flag") when exactly one
// MarkFlagRequired flag is missing, and the plural form ("required
// flag(s)") only when multiple are missing on the same command. Both
// shapes must be anchored to avoid matching app-level errors that
// happen to mention "required flag" as prose; the trailing space + quote
// (`required flag "`) is the literal punctuation cobra emits.
//
// Returns false for nil err.
func isCobraUsageError(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	return strings.HasPrefix(msg, "unknown flag") ||
		strings.HasPrefix(msg, "unknown shorthand flag") ||
		strings.HasPrefix(msg, "unknown command") ||
		strings.HasPrefix(msg, `required flag "`) ||
		strings.HasPrefix(msg, `required flag(s) "`) ||
		strings.HasPrefix(msg, "flag needs an argument:") ||
		strings.HasPrefix(msg, `invalid argument "`)
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "tickertape-pp-cli",
		Short: `Research Indian and US stocks, mutual funds, ETFs, indices, screen metadata, scorecards, market mood, and deal ideas from live Tickertape endpoints without storing domain data locally.`,
		Long: `Research Indian and US stocks, mutual funds, ETFs, indices, screen metadata, scorecards, market mood, and deal ideas from live Tickertape endpoints without storing domain data locally.

Highlights (not in the official API docs):
  • company scorecard   Show Tickertape score dimensions, locked fields, entry-point signals, and red flags without silently dropping premium data.
  • company timeline   Combine live company events, news, results, and investor-presentation metadata into a dated source-labelled stream.
  • lookup   Triages Indian stocks, mutual funds, ETFs, indices, and US securities through one live command while retaining source-specific identity fields.
  • inspect access   Explain source host, route, observation time, entity identity, lock state, and entitlement errors for any live result.
  • market brief   Turn the live Market Mood Index payload into a concise timestamped brief of fear/greed, FII, momentum, volatility, and component signals.
  • company brief   Compose live company identity, summary, scorecard, reports, and access state into one bounded triage response.
  • screen catalog   Organize equity and mutual-fund filters, categories, universes, and prebuilt screens while preserving premium markers.

Agent mode: add --agent to any command for JSON output + non-interactive mode.
Health check: run 'tickertape-pp-cli doctor' to verify connectivity.
See README.md or the bundled SKILL.md for recipes.`,
		SilenceUsage: true,
		Version:      version,
	}
	rootCmd.SetVersionTemplate("tickertape-pp-cli {{ .Version }}\n")

	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.compact, "compact", false, "Return only key fields (id, name, status, timestamps) for minimal token usage")
	rootCmd.PersistentFlags().BoolVar(&flags.csv, "csv", false, "Output as CSV (table and array responses)")
	rootCmd.PersistentFlags().BoolVar(&flags.plain, "plain", false, "Output as plain tab-separated text")
	rootCmd.PersistentFlags().BoolVar(&flags.quiet, "quiet", false, "Bare output, one value per line")
	rootCmd.PersistentFlags().StringVar(&flags.configPath, "config", "", "Config file path")
	rootCmd.PersistentFlags().DurationVar(&flags.timeout, "timeout", 60*time.Second, "Request timeout")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Show request without sending")
	rootCmd.PersistentFlags().BoolVar(&flags.noInput, "no-input", false, "Disable all interactive prompts (for CI/agents)")
	rootCmd.PersistentFlags().StringVar(&flags.selectFields, "select", "", "Comma-separated fields to include in output")
	rootCmd.PersistentFlags().BoolVar(&flags.yes, "yes", false, "Skip confirmation prompts (explicit confirmation for scripts)")
	rootCmd.PersistentFlags().BoolVar(&noColor, "no-color", false, "Disable colored output")
	rootCmd.PersistentFlags().BoolVar(&humanFriendly, "human-friendly", false, "Enable colored output and rich formatting")
	rootCmd.PersistentFlags().BoolVar(&flags.agent, "agent", false, "Set agent-friendly output defaults (--json --compact --no-input --no-color)")
	rootCmd.PersistentFlags().BoolVar(&flags.allowPartialFailure, "allow-partial-failure", false, "Downgrade response-body partial-failure to a warning instead of a non-zero exit")
	rootCmd.PersistentFlags().Float64Var(&flags.rateLimit, "rate-limit", client.RateLimitAuto, "Max requests per second (0 to disable; default auto — pace to server rate-limit headers)")
	if f := rootCmd.PersistentFlags().Lookup("rate-limit"); f != nil {
		f.DefValue = "auto"
	}

	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		for index, arg := range args {
			if strings.Contains(arg, "__printing_press_invalid__") {
				return usageErr(fmt.Errorf("argument %d is invalid", index+1))
			}
		}
		if err := enforceMCPBoundProfile(cmd, flags); err != nil {
			return err
		}

		if platformCommandNeedsGate(cmd) {
			if err := preparePlatformSession(flags); err != nil {
				return err
			}
			cmd.SetContext(platform.ContextWithSession(cmd.Context(), flags.platformSession))
			if err := validatePlatformLegacyInputs(cmd, flags); err != nil {
				return err
			}
			if err := initializePlatformReceipt(cmd, flags); err != nil {
				return err
			}
			if err := adoptPlatformCommandWindow(cmd, flags); err != nil {
				return err
			}
			flags.platformMetadataWriter = cmd.ErrOrStderr()
			if err := verifyPlatformSession(cmd.Context(), flags); err != nil {
				if platformCommandIsDoctor(cmd) {
					flags.platformGateError = err
				} else {
					return err
				}
			}
		}
		if flags.agent {
			if !cmd.Flags().Changed("json") {
				flags.asJSON = true
			}
			if !cmd.Flags().Changed("compact") {
				flags.compact = true
			}
			if !cmd.Flags().Changed("no-input") {
				flags.noInput = true
			}
			if !cmd.Flags().Changed("no-color") {
				noColor = true
			}
		}
		flags.timeoutExplicit = timeoutExplicitFrom(cmd)
		flags.agentSource = declaredAgentSource(cmd, flags)
		return nil
	}
	rootCmd.AddCommand(newCompanyCmd(flags))
	rootCmd.AddCommand(newDealsCmd(flags))
	rootCmd.AddCommand(newMarketCmd(flags))
	rootCmd.AddCommand(newMutualfundCmd(flags))
	rootCmd.AddCommand(newScreenerCmd(flags))
	rootCmd.AddCommand(newUsCmd(flags))
	rootCmd.AddCommand(newDoctorCmd(flags))
	rootCmd.AddCommand(newAuthCmd(flags))
	rootCmd.AddCommand(newUserCmd(flags))
	rootCmd.AddCommand(newCreditCmd(flags))
	rootCmd.AddCommand(newPortfolioCmd(flags))
	if registeredPlatformSource != nil {
		attachPlatformClientCommands(rootCmd, flags)
	}
	rootCmd.AddCommand(newAgentContextCmd(rootCmd))
	rootCmd.AddCommand(newWhichCmd(flags))
	rootCmd.AddCommand(newLiveSearchCmd(flags))
	rootCmd.AddCommand(newHomepagePromotedCmd(flags))
	rootCmd.AddCommand(newSearchResourcePromotedCmd(flags))
	rootCmd.AddCommand(newVersionCmd())
	addNovelCommandIfAbsent(rootCmd, newNovelInspectCmd(flags))
	addNovelCommandIfAbsent(rootCmd, newNovelLookupCmd(flags))
	addNovelCommandIfAbsent(rootCmd, newNovelScreenCmd(flags))
	for _, hook := range novelCommandHooks {
		hook(rootCmd, flags)
	}
	preferImplementedNovelCommands(rootCmd)
	// Attach the conditional platform identity command last so ordinary,
	// promoted, and novel API-owned `whoami` commands all win the name.
	if registeredPlatformSource != nil {
		attachPlatformWhoamiCommand(rootCmd, flags)
	}
	ensureCommandExamples(rootCmd)

	return rootCmd
}

// ensureCommandExamples keeps generated leaf help actionable even when an
// endpoint spec omitted an example. It only fills empty Examples fields and
// never replaces hand-authored research recipes.
func ensureCommandExamples(root *cobra.Command) {
	var walk func(*cobra.Command)
	walk = func(parent *cobra.Command) {
		for _, cmd := range parent.Commands() {
			if cmd.Example == "" && cmd.RunE != nil && !cmd.Hidden {
				parts := strings.Fields(cmd.CommandPath())
				useParts := strings.Fields(cmd.Use)
				for _, token := range useParts[1:] {
					if token == "[flags]" || token == "[flag]" {
						continue
					}
					parts = append(parts, exampleValue(token))
				}
				parts = append(parts, "--agent")
				cmd.Example = "  " + strings.Join(parts, " ")
			}
			walk(cmd)
		}
	}
	walk(root)
}

func exampleValue(token string) string {
	name := strings.ToLower(strings.Trim(token, "[]<>"))
	switch {
	case strings.Contains(name, "sid"), strings.Contains(name, "stock"):
		return "RELI"
	case strings.Contains(name, "mf") || strings.Contains(name, "fund"):
		return "MF001"
	case strings.Contains(name, "ticker") || strings.Contains(name, "security"):
		return "VOO"
	case strings.Contains(name, "statement"):
		return "income"
	case strings.Contains(name, "period"):
		return "annual"
	case strings.Contains(name, "view"):
		return "absolute"
	default:
		return "example"
	}
}

func timeoutExplicitFrom(cmd *cobra.Command) bool {
	return cmd != nil && cmd.Flags().Changed("timeout")
}

func ExitCode(err error) int {
	var codeErr *cliError
	if As(err, &codeErr) {
		return codeErr.code
	}
	return 1
}

func (f *rootFlags) newClient() (*client.Client, error) {
	cfg, err := config.Load(f.configPath)
	if err != nil {
		return nil, configErr(err)
	}
	c := client.New(cfg, f.timeout, f.rateLimit)
	if f.timeoutExplicit {
		c.SetTimeoutExplicit(true)
	}
	c.DryRun = f.dryRun
	if err := bindPlatformClient(c, f); err != nil {
		return nil, err
	}
	if err := ApplyClientHooks(c); err != nil {
		return nil, err
	}
	return c, nil
}

func (f *rootFlags) printJSON(w *cobra.Command, v any) error {
	return printJSONFiltered(w.OutOrStdout(), v, f)
}

func (f *rootFlags) printTable(w *cobra.Command, headers []string, rows [][]string) error {
	if f.asJSON {
		return fmt.Errorf("use printJSON for JSON output")
	}
	tw := tabwriter.NewWriter(w.OutOrStdout(), 2, 4, 2, ' ', 0)
	header := ""
	for i, h := range headers {
		if i > 0 {
			header += "\t"
		}
		header += h
	}
	fmt.Fprintln(tw, header)
	for _, row := range rows {
		line := ""
		for i, cell := range row {
			if i > 0 {
				line += "\t"
			}
			line += cell
		}
		fmt.Fprintln(tw, line)
	}
	return tw.Flush()
}
