// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newScreenerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "screener",
		Short:       "Equity and mutual-fund filter catalogs, prebuilt screens, universes, and optional queries.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newScreenerEquityFiltersCmd(flags))
	cmd.AddCommand(newScreenerEquityPrebuiltCmd(flags))
	cmd.AddCommand(newScreenerEquityQueryCmd(flags))
	cmd.AddCommand(newScreenerEquityUniversesCmd(flags))
	cmd.AddCommand(newScreenerMfFiltersCmd(flags))
	cmd.AddCommand(newScreenerMfPrebuiltCmd(flags))
	cmd.AddCommand(newScreenerMfQueryCmd(flags))
	cmd.AddCommand(newScreenerMfUniversesCmd(flags))
	return cmd
}
