// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "us",
		Short:       "US security and ETF research through Tickertape's global market service.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUsChartCmd(flags))
	cmd.AddCommand(newUsEtfInfoCmd(flags))
	cmd.AddCommand(newUsEtfOverviewCmd(flags))
	cmd.AddCommand(newUsFiltersCmd(flags))
	cmd.AddCommand(newUsFinancialsCmd(flags))
	cmd.AddCommand(newUsSecurityInfoCmd(flags))
	cmd.AddCommand(newUsSecurityOverviewCmd(flags))
	return cmd
}
