// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Author struct {
	Role     string          `json:"role"`
	Name     string          `json:"name"`
	Metadata json.RawMessage `json:"metadata"`
}

type ChatRequirements struct {
	Persona     string          `json:"persona"`
	Token       string          `json:"token"`
	ExpireAfter int             `json:"expire_after"`
	Proofofwork json.RawMessage `json:"proofofwork"`
	Turnstile   json.RawMessage `json:"turnstile"`
}

type ConduitPrepare struct {
	Status       string `json:"status"`
	ConduitToken string `json:"conduit_token"`
}

type Content struct {
	ContentType string `json:"content_type"`
	Parts       string `json:"parts"`
}

type Conversation struct {
	Title            string   `json:"title"`
	CreateTime       float64  `json:"create_time"`
	UpdateTime       float64  `json:"update_time"`
	ConversationId   string   `json:"conversation_id"`
	DefaultModelSlug string   `json:"default_model_slug"`
	IsArchived       bool     `json:"is_archived"`
	IsStarred        bool     `json:"is_starred"`
	MemoryScope      string   `json:"memory_scope"`
	Messages         string   `json:"messages"`
	CurrentNode      string   `json:"current_node"`
	PageInfo         PageInfo `json:"page_info"`
	SafeUrls         string   `json:"safe_urls"`
}

type ConversationList struct {
	Items  string `json:"items"`
	Total  int    `json:"total"`
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
}

type ConversationListItem struct {
	Id                           string          `json:"id"`
	Title                        string          `json:"title"`
	CreateTime                   string          `json:"create_time"`
	UpdateTime                   string          `json:"update_time"`
	LatestAssistantTurnCreatedAt string          `json:"latest_assistant_turn_created_at"`
	PinnedTime                   string          `json:"pinned_time"`
	IsArchived                   bool            `json:"is_archived"`
	IsStarred                    bool            `json:"is_starred"`
	IsTemporaryChat              bool            `json:"is_temporary_chat"`
	IsDoNotRemember              bool            `json:"is_do_not_remember"`
	MemoryScope                  string          `json:"memory_scope"`
	WorkspaceId                  string          `json:"workspace_id"`
	Snippet                      string          `json:"snippet"`
	SummaryMetadata              json.RawMessage `json:"summary_metadata"`
	ConversationOrigin           string          `json:"conversation_origin"`
}

type ConversationTree struct {
	Title            string  `json:"title"`
	CreateTime       float64 `json:"create_time"`
	UpdateTime       float64 `json:"update_time"`
	Mapping          string  `json:"mapping"`
	CurrentNode      string  `json:"current_node"`
	DefaultModelSlug string  `json:"default_model_slug"`
}

type GlobalSearchItem struct {
	Id         string          `json:"id"`
	SourceType string          `json:"source_type"`
	Title      string          `json:"title"`
	Snippet    string          `json:"snippet"`
	UpdateTime float64         `json:"update_time"`
	MatchKind  string          `json:"match_kind"`
	Payload    json.RawMessage `json:"payload"`
}

type GlobalSearchResults struct {
	Items          string `json:"items"`
	Cursor         string `json:"cursor"`
	PartialResults bool   `json:"partial_results"`
	SourceStatuses string `json:"source_statuses"`
}

type MappingNode struct {
	Id       string  `json:"id"`
	Message  Message `json:"message"`
	Parent   string  `json:"parent"`
	Children string  `json:"children"`
}

type Message struct {
	Id         string          `json:"id"`
	Author     Author          `json:"author"`
	CreateTime float64         `json:"create_time"`
	UpdateTime float64         `json:"update_time"`
	Content    Content         `json:"content"`
	Status     string          `json:"status"`
	EndTurn    bool            `json:"end_turn"`
	Weight     int             `json:"weight"`
	Recipient  string          `json:"recipient"`
	Metadata   MessageMetadata `json:"metadata"`
}

type MessageMetadata struct {
	RequestId                        string `json:"request_id"`
	TurnId                           string `json:"turn_id"`
	TurnExchangeId                   string `json:"turn_exchange_id"`
	ModelSlug                        string `json:"model_slug"`
	MessageType                      string `json:"message_type"`
	IsVisuallyHiddenFromConversation bool   `json:"is_visually_hidden_from_conversation"`
}

type MessagesPage struct {
	Messages    string   `json:"messages"`
	SafeUrls    string   `json:"safe_urls"`
	BlockedUrls string   `json:"blocked_urls"`
	PageInfo    PageInfo `json:"page_info"`
}

type ModelInfo struct {
	Slug                       string `json:"slug"`
	Title                      string `json:"title"`
	Description                string `json:"description"`
	Tags                       string `json:"tags"`
	MaxTokens                  int    `json:"max_tokens"`
	ReasoningType              string `json:"reasoning_type"`
	ConfigurableThinkingEffort bool   `json:"configurable_thinking_effort"`
	ThinkingEfforts            string `json:"thinking_efforts"`
}

type ModelsResponse struct {
	DefaultModelSlug   string `json:"default_model_slug"`
	ModelPickerVersion int    `json:"model_picker_version"`
	Models             string `json:"models"`
}

type PageInfo struct {
	StartCursor     string `json:"start_cursor"`
	EndCursor       string `json:"end_cursor"`
	HasPreviousPage bool   `json:"has_previous_page"`
	HasNextPage     bool   `json:"has_next_page"`
}

type SearchHit struct {
	ConversationId string          `json:"conversation_id"`
	CurrentNodeId  string          `json:"current_node_id"`
	Title          string          `json:"title"`
	IsArchived     bool            `json:"is_archived"`
	UpdateTime     float64         `json:"update_time"`
	Payload        json.RawMessage `json:"payload"`
}

type SearchResults struct {
	Items  string `json:"items"`
	Cursor string `json:"cursor"`
}

type Session struct {
	User         json.RawMessage `json:"user"`
	Expires      string          `json:"expires"`
	AccessToken  string          `json:"accessToken"`
	AuthProvider string          `json:"authProvider"`
}

type SourceStatus struct {
	SourceType string  `json:"source_type"`
	Status     string  `json:"status"`
	HasMore    bool    `json:"has_more"`
	DurationMs float64 `json:"duration_ms"`
	ErrorCode  string  `json:"error_code"`
}

type StreamStatus struct {
	Status string `json:"status"`
}
