// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "account",
		Short:       "Optional authenticated Moneycontrol account and Pro reads. Read-only only.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountAlertsCmd(flags))
	cmd.AddCommand(newAccountEntitlementStatusCmd(flags))
	cmd.AddCommand(newAccountPortfolioCmd(flags))
	cmd.AddCommand(newAccountProStocklistCmd(flags))
	cmd.AddCommand(newAccountUserDetailsCmd(flags))
	cmd.AddCommand(newAccountWatchlistCmd(flags))
	return cmd
}
