// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMarketsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "markets",
		Short:       "Financial market pages and institutional activity.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMarketsCommoditiesCmd(flags))
	cmd.AddCommand(newMarketsCorporateActionsCmd(flags))
	cmd.AddCommand(newMarketsEarningsCmd(flags))
	cmd.AddCommand(newMarketsFiiDiiCmd(flags))
	cmd.AddCommand(newMarketsFnoCmd(flags))
	cmd.AddCommand(newMarketsForexCmd(flags))
	cmd.AddCommand(newMarketsIndicesTableCmd(flags))
	cmd.AddCommand(newMarketsIpoCmd(flags))
	cmd.AddCommand(newMarketsMutualFundsCmd(flags))
	return cmd
}
