// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newResearchCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "research",
		Short:       "Company research pages and stock scanners.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newResearchEquityResearchCmd(flags))
	cmd.AddCommand(newResearchFilingsCmd(flags))
	cmd.AddCommand(newResearchFundamentalScannerCmd(flags))
	cmd.AddCommand(newResearchTechnicalScannerCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelResearchPacketCmd(flags))
	return cmd
}
