// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"kite-zerodha-pp-cli/internal/cliutil"
	"kite-zerodha-pp-cli/internal/config"
)

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "auth",
		Short:       "Manage authentication for Kite by Zerodha",
		Annotations: map[string]string{"pp:parent-group": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthLoginCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthSetTokenCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

// newAuthSetupCmd prints the exact local setup handoff. It never asks for or
// prints an API secret. The secret is read from a 0600 file by auth login.
func newAuthSetupCmd(_ *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Guide secure Kite Connect Personal API setup",
		Example: "  kite-zerodha-pp-cli auth setup\n  kite-zerodha-pp-cli auth setup --launch",
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "1. Create a free Personal app at https://developers.kite.trade/create.")
			fmt.Fprintln(w, "2. Register this exact redirect URL: http://127.0.0.1:8765/callback")
			fmt.Fprintln(w, "3. Leave Postback URL blank; this CLI has no order-update listener.")
			fmt.Fprintln(w, "4. Save the API key and secret in private local files (mode 600). Do not paste either into chat or a command argument.")
			fmt.Fprintln(w, "5. Run the official manual login flow:")
			fmt.Fprintln(w, "   kite-zerodha-pp-cli auth login --api-key <api-key> --api-secret-file <0600-file> --launch")
			fmt.Fprintln(w, "   The request token is exchanged immediately and the composite token is stored in the private credentials file.")
			fmt.Fprintln(w, "6. Check the sanitized result: kite-zerodha-pp-cli auth status --json")
			if !launch {
				return nil
			}
			if cliutil.IsAnyHarness() {
				return authErr(errors.New("browser launch is disabled under a verification harness; rerun setup without the harness"))
			}
			if err := openKiteURL("https://developers.kite.trade/create"); err != nil {
				return authErr(fmt.Errorf("opening developer app page: %w", err))
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Open the official developer app page in the default browser")
	return cmd
}

const defaultKiteRedirectURI = "http://127.0.0.1:8765/callback"

// newAuthLoginCmd implements Kite's documented request-token flow. The API
// secret is read from a private file or the existing private credentials store;
// it never appears in an argument, URL, log, or output envelope.
func newAuthLoginCmd(flags *rootFlags) *cobra.Command {
	var (
		apiKey           string
		apiSecretFile    string
		requestTokenFile string
		redirectURI      string
		launch           bool
	)
	cmd := &cobra.Command{
		Use:   "login",
		Short: "Complete the official Kite Connect request-token login",
		Long: "Complete the official Kite Connect request-token login.\n\n" +
			"By default this starts a loopback listener at the registered redirect URL. " +
			"For a secure manual fallback, pass --request-token-file with a 0600 file containing only the one-time request_token.",
		Example: "  kite-zerodha-pp-cli auth login --api-key <api-key> --api-secret-file /path/to/secret --launch\n" +
			"  kite-zerodha-pp-cli auth login --request-token-file /path/to/request-token",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			key := strings.TrimSpace(apiKey)
			if key == "" {
				key = strings.TrimSpace(cfg.ClientID)
			}
			if key == "" {
				return authErr(errors.New("Kite API key is required; pass --api-key or run auth setup"))
			}
			if !isKiteCredentialPart(key) {
				return authErr(errors.New("Kite API key contains unsupported characters"))
			}

			secret := strings.TrimSpace(cfg.ClientSecret)
			if apiSecretFile != "" {
				secret, err = readPrivateAuthFile(apiSecretFile, "API secret")
				if err != nil {
					return authErr(err)
				}
			}
			if secret == "" {
				return authErr(errors.New("Kite API secret is not configured; pass --api-secret-file with a 0600 file"))
			}
			if !isKiteCredentialPart(secret) {
				return authErr(errors.New("Kite API secret contains unsupported characters"))
			}

			if flags.dryRun {
				out := map[string]any{
					"ready":                 true,
					"api_key_configured":    key != "",
					"api_secret_configured": secret != "",
					"access_token_present":  strings.TrimSpace(cfg.AuthHeader()) != "",
					"transport":             "official Kite Connect request-token exchange",
				}
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), out, flags)
				}
				fmt.Fprintln(cmd.OutOrStdout(), "Kite auth inputs are configured; dry-run made no network request and saved nothing.")
				return nil
			}

			var requestToken string
			if requestTokenFile != "" {
				if launch {
					return authErr(errors.New("--launch cannot be combined with --request-token-file"))
				}
				requestToken, err = readPrivateAuthFile(requestTokenFile, "request token")
				if err != nil {
					return authErr(err)
				}
			} else {
				redirect := strings.TrimSpace(redirectURI)
				if redirect == "" {
					redirect = defaultKiteRedirectURI
				}
				if err := validateKiteRedirectURI(redirect); err != nil {
					return authErr(err)
				}
				loginURL, err := kiteLoginURL(key)
				if err != nil {
					return authErr(err)
				}
				requestToken, err = waitForKiteCallback(cmd.Context(), cmd.OutOrStdout(), redirect, loginURL, launch, flags.timeout)
				if err != nil {
					return authErr(err)
				}
			}

			accessToken, err := exchangeKiteRequestToken(cmd.Context(), cfg.BaseURL, key, secret, requestToken)
			if err != nil {
				return authErr(err)
			}
			// Persist the API key and secret alongside the composite token in the
			// private credentials store. They are never printed or placed in an
			// argument; the secret is needed for the next day's login exchange.
			cfg.ClientID = key
			cfg.ClientSecret = secret
			if err := cfg.SaveKiteConnectToken(key, accessToken); err != nil {
				return configErr(fmt.Errorf("saving Kite credentials: %w", err))
			}
			if flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"authenticated": true,
					"saved":         true,
					"source":        cfg.AuthSource,
				}, flags)
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Kite authentication completed; access token saved securely.")
			return nil
		},
	}
	cmd.Flags().StringVar(&apiKey, "api-key", "", "Kite API key (public identifier; omitted when already stored securely)")
	cmd.Flags().StringVar(&apiSecretFile, "api-secret-file", "", "0600 file containing only the Kite API secret")
	cmd.Flags().StringVar(&requestTokenFile, "request-token-file", "", "0600 file containing only the one-time request token (manual fallback)")
	cmd.Flags().StringVar(&redirectURI, "redirect-uri", defaultKiteRedirectURI, "Registered loopback redirect URL")
	cmd.Flags().BoolVar(&launch, "launch", false, "Open the official Kite login URL after starting the callback listener")
	return cmd
}

func isKiteCredentialPart(value string) bool {
	if value == "" || len(value) > 256 {
		return false
	}
	for _, r := range value {
		if (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && (r < '0' || r > '9') && r != '_' && r != '-' {
			return false
		}
	}
	return true
}

func readPrivateAuthFile(path, label string) (string, error) {
	path = strings.TrimSpace(path)
	if path == "" {
		return "", fmt.Errorf("%s file path is empty", label)
	}
	path, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve %s file: %w", label, err)
	}
	info, err := os.Lstat(path)
	if err != nil {
		return "", fmt.Errorf("stat %s file: %w", label, err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return "", fmt.Errorf("refusing symlinked %s file", label)
	}
	if err := cliutil.VerifyCredsPerms(path); err != nil {
		return "", fmt.Errorf("unsafe %s file: %w", label, err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s file: %w", label, err)
	}
	value := strings.TrimSpace(string(data))
	if value == "" {
		return "", fmt.Errorf("%s file is empty", label)
	}
	if len(value) > maxSecretFromStdin {
		return "", fmt.Errorf("%s file is too large", label)
	}
	return value, nil
}

func validateKiteRedirectURI(raw string) error {
	u, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || u.Scheme != "http" || u.Hostname() == "" || u.Port() == "" || u.Path == "" || u.RawQuery != "" || u.Fragment != "" {
		return errors.New("redirect URI must be an http loopback URL with an explicit port and no query or fragment")
	}
	host := strings.ToLower(u.Hostname())
	if host != "127.0.0.1" && host != "localhost" && host != "::1" {
		return errors.New("redirect URI must target localhost, 127.0.0.1, or ::1")
	}
	return nil
}

func kiteLoginURL(apiKey string) (string, error) {
	if !isKiteCredentialPart(apiKey) {
		return "", errors.New("invalid Kite API key")
	}
	values := url.Values{}
	values.Set("v", "3")
	values.Set("api_key", apiKey)
	return "https://kite.zerodha.com/connect/login?" + values.Encode(), nil
}

func waitForKiteCallback(ctx context.Context, out io.Writer, redirect, loginURL string, launch bool, timeout time.Duration) (string, error) {
	u, err := url.Parse(redirect)
	if err != nil {
		return "", err
	}
	listener, err := net.Listen("tcp", u.Host)
	if err != nil {
		return "", fmt.Errorf("listen on registered redirect URI: %w", err)
	}
	defer listener.Close()

	result := make(chan string, 1)
	server := &http.Server{Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != u.Path {
			http.NotFound(w, r)
			return
		}
		token := strings.TrimSpace(r.URL.Query().Get("request_token"))
		status := strings.TrimSpace(r.URL.Query().Get("status"))
		if token == "" {
			w.WriteHeader(http.StatusBadRequest)
			_, _ = io.WriteString(w, "Kite login callback did not contain a request token. You may close this window.\n")
			return
		}
		w.WriteHeader(http.StatusOK)
		_, _ = io.WriteString(w, "Kite login captured. You may close this window.\n")
		if status != "" && status != "success" {
			return
		}
		select {
		case result <- token:
		default:
		}
	})}
	serveErr := make(chan error, 1)
	go func() { serveErr <- server.Serve(listener) }()

	if launch {
		if cliutil.IsAnyHarness() {
			_ = server.Shutdown(context.Background())
			return "", errors.New("browser launch is disabled under a verification harness; rerun auth login without the harness")
		}
		if err := openKiteURL(loginURL); err != nil {
			_ = server.Shutdown(context.Background())
			return "", fmt.Errorf("open Kite login URL: %w", err)
		}
	} else {
		fmt.Fprintf(out, "Open the official Kite login URL in a browser: %s\n", loginURL)
	}
	if timeout <= 0 {
		timeout = 60 * time.Second
	}
	waitCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	select {
	case token := <-result:
		_ = server.Shutdown(context.Background())
		return token, nil
	case <-waitCtx.Done():
		_ = server.Shutdown(context.Background())
		if errors.Is(waitCtx.Err(), context.DeadlineExceeded) {
			return "", errors.New("timed out waiting for the Kite login callback")
		}
		return "", waitCtx.Err()
	case err := <-serveErr:
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			return "", fmt.Errorf("Kite callback listener stopped: %w", err)
		}
		return "", errors.New("Kite callback listener stopped before receiving a request token")
	}
}

func openKiteURL(target string) error {
	var name string
	var args []string
	switch runtime.GOOS {
	case "darwin":
		name, args = "open", []string{target}
	case "linux":
		name, args = "xdg-open", []string{target}
	case "windows":
		name, args = "rundll32", []string{"url.dll,FileProtocolHandler", target}
	default:
		return fmt.Errorf("unsupported browser launcher on %s", runtime.GOOS)
	}
	cmd := exec.Command(name, args...)
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard
	return cmd.Run()
}

type kiteSessionEnvelope struct {
	Status string `json:"status"`
	Data   struct {
		AccessToken string `json:"access_token"`
	} `json:"data"`
}

func exchangeKiteRequestToken(ctx context.Context, baseURL, apiKey, apiSecret, requestToken string) (string, error) {
	baseURL = strings.TrimRight(strings.TrimSpace(baseURL), "/")
	if baseURL == "" {
		baseURL = "https://api.kite.trade"
	}
	checksum := sha256.Sum256([]byte(apiKey + requestToken + apiSecret))
	form := url.Values{}
	form.Set("api_key", apiKey)
	form.Set("request_token", requestToken)
	form.Set("checksum", hex.EncodeToString(checksum[:]))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, baseURL+"/session/token", strings.NewReader(form.Encode()))
	if err != nil {
		return "", fmt.Errorf("build Kite session exchange: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("X-Kite-Version", "3")
	req.Header.Set("Accept", "application/json")
	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return "", fmt.Errorf("Kite session exchange failed: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", fmt.Errorf("read Kite session response: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", fmt.Errorf("Kite session exchange failed with HTTP %d", resp.StatusCode)
	}
	var envelope kiteSessionEnvelope
	if err := json.Unmarshal(body, &envelope); err != nil {
		return "", errors.New("Kite session exchange returned an invalid response")
	}
	if envelope.Status != "success" || strings.TrimSpace(envelope.Data.AccessToken) == "" {
		return "", errors.New("Kite session exchange did not return an access token")
	}
	return strings.TrimSpace(envelope.Data.AccessToken), nil
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  kite-zerodha-pp-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			authed := header != ""
			refusals := cfg.CredentialRefusalSummaries()
			credentialRefused := len(refusals) > 0
			// JSON envelope: {authenticated, verified, source, config}. When not
			// authenticated, write the envelope first then return authErr
			// so exit code carries the auth-failure signal.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"verified":      false,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				if credentialRefused {
					out["credential_refused"] = true
					out["credential_refusals"] = refusals
				}
				if authed {
					if expiresAt, _, expired, ok := jwtCredentialExpiry(jwtExpirySource(cfg)); ok {
						out["token_expires"] = expiresAt
						out["token_expired"] = expired
					}
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !authed && credentialRefused {
					return authErr(cfg.CredentialRefusalError())
				}
				if !authed {
					return authErr(fmt.Errorf("no credentials configured"))
				}
				return nil
			}
			if !authed && credentialRefused {
				fmt.Fprintln(w, red("Credentials present but refused"))
				for _, refusal := range refusals {
					fmt.Fprintf(w, "  %s\n", refusal)
				}
				return authErr(cfg.CredentialRefusalError())
			}
			if !authed {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Set your token:")
				fmt.Fprintln(w, "  export KITE_CONNECT_TOKEN=\"your-token-here\"")
				fmt.Fprintf(w, "  echo \"$TOKEN\" | kite-zerodha-pp-cli auth set-token\n")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Credentials present (not verified)"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			if _, line, expired, ok := jwtCredentialExpiry(jwtExpirySource(cfg)); ok {
				fmt.Fprintf(w, "  Token expires: %s\n", line)
				if expired {
					fmt.Fprintf(w, "  %s\n", "Set it with: echo \"$TOKEN\" | kite-zerodha-pp-cli auth set-token or export KITE_CONNECT_TOKEN=\"your-token-here\"")
				}
			}
			return nil
		},
	}
}

func newAuthSetTokenCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "set-token",
		Short: "Save an API token to the credentials file",
		Long: "Save an API token to the credentials file.\n\n" +
			"The token is read from stdin so it never appears in process arguments or shell history.",
		Example: "  echo \"$TOKEN\" | kite-zerodha-pp-cli auth set-token\n  kite-zerodha-pp-cli auth set-token < token-file",
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			token, err := readSecretFromStdin(cmd.InOrStdin())
			if err != nil {
				return authErr(err)
			}

			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			// Clear any legacy auth_header so AuthHeader() falls through to
			// the newly-saved credential. Without this, a pre-existing
			// auth_header value (common after regenerate) shadows the saved
			// token and set-token silently has no effect. Silent clear (no
			// log line): a masked-tail variant could leak token bytes through
			// scripted dogfood that captures stderr.
			cfg.AuthHeaderVal = ""
			if err := cfg.SaveTokens("", "", token, "", cfg.TokenExpiry); err != nil {
				return configErr(fmt.Errorf("saving token: %w", err))
			}

			savePath := credentialSavePath(cfg)
			// JSON envelope: {saved, config_path, credentials_path}.
			if flags.asJSON {
				out := map[string]any{
					"saved":       true,
					"config_path": cfg.Path,
				}
				if !cfg.AgentcookieManagedByExternalStore() {
					out["credentials_path"] = savePath
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Token saved to %s\n", savePath)
			return nil
		},
	}
}

func credentialSavePath(cfg *config.Config) string {
	if cfg != nil && cfg.AgentcookieManagedByExternalStore() {
		return cfg.Path
	}
	if path, err := cliutil.CredentialsFilePath(); err == nil {
		return path
	}
	if cfg != nil {
		return cfg.Path
	}
	return ""
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  kite-zerodha-pp-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("KITE_CONNECT_TOKEN") != "" {
				envStillSet = "KITE_CONNECT_TOKEN"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}
