// Copyright 2026 dev-abhirup-sc and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMarginsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "margins",
		Short:       "Current account margin and funds state",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMarginsGetCmd(flags))
	cmd.AddCommand(newMarginsListCmd(flags))
	return cmd
}
